### ISSUE TITLE
Feature Suggestion: Add Zone Id Lookup to DNS providers

### ISSUE THREAD

**Issue by webprofusion-chrisc** [rmbolger/Posh-ACME#108]
This is probably quite a big ask: currently most of the DNS providers identify the DNS zone by domain matching. This is potentially error prone depending on the robustness of the provider and how many similar zones you have hosted. Ideally instead of having to match on domain the user could optionally provide a zone id (provider specific). Providing a zone id lookup method (listing the zones available to the given set of credentials) per provider would help with this.

We do this with Certify (https://github.com/webprofusion/certify) and let the user pick the correct zone from a dropdown while they are configuring the DSN API, but we only have a limited set of DNS providers so it would be great if we could share DNS providers so we only have one set of bugs. 

It's possible that we may end up providing a hosted API for DNS updates (specifically for LE validation), so the powershell providers could be a good fit (we have other options with Python/nodes libraries etc but Posh-ACME seems quite active).

**Comment by rmbolger** [comment]
Hi Chris! Love the project. Let me make sure I understand what you're asking.

You want all of the plugins/providers to explicitly implement a "Get all zones" function which would return a list of zones and some sort of per-zone unique identifier for that provider? And then add that ID value as a required argument to the Add/Remove functions?

Assuming that's correct, it seems like a lot of work for not a whole lot of benefit. But it's possible I just haven't seen/heard of many issues with the existing domain matching. Granted, the domain matching code is *really* similar between plugins. But to-date, I've not heard of it being wrong except in one case in Route53 where the account was hosting split-brain copies (one internal, one external) of the same zone. But that was a pretty simple fix to exclude the internal zones.

I also wonder about scale issues on accounts that have lots and lots of zones. Depending on the provider, you get into hassles like paging (at best), limits on the number of results (forcing you to make up your own based on filters), or just errors because the provider didn't plan for large result sets.

Ultimately, I think I just dislike the general algorithm of:

- get all zones
- find/pick the one you want or error with no matches
- make updates

I'd rather it be more like the way I've been doing it in the plugins:

- loop from deep to shallow the sub-zones that make up the TXT record
  - check if zone exists and return it
- error if no zone found
- make updates

The latter is potentially more round trips to the API particularly on deep sub-zones. But it's simpler to implement/maintain and less likely to have issues between providers. It's also potentially more bandwidth efficient for large accounts.

Taking a step back though. Ever since I started the project, I thought it would be great to have a .NET-friendly equivalent of [Lexicon](https://github.com/AnalogJ/lexicon). But that's a huge undertaking even if all you tried to do was port things directly from it. A hosted API for something like that is definitely an interesting idea. But I wonder how supportable that would be in an ecosystem where most of the consumers expect the solutions to be free. It also adds an external dependency where there isn't one today which is added risk.

Apologies, I'm not exactly sure where I'm going with this and I ended up rambling a bit. At the moment, I'm not convinced. But I'm still open to more discussion especially if I misunderstood something about your suggestion.

**Comment by webprofusion-chrisc** [comment]
@rmbolger thanks, yes I did think it would be a bit of stretch from what you're currently doing :) - so the idea is that you determine the expected zone id once (when configuring the job) and being able to lookup the zone list helps with that (saving a trip to the control panel and figuring out which part would be considered the 'id', often it's the domain name itself, other times it's a number of other identifier).

The hosted API idea is one I'm still debating over as it requires that people share their DNS credentials to perform the work, which isn't ideal. It could alternatively be a managed cname service for redirected challenge TXT records (point your _acme-challenge here and forget about it), then an API does all the other work, which would solve the problem of developing lots of providers. Still thinking about..

**Comment by webprofusion-chrisc** [comment]
Anyway, don't worry about this topic - I'll close it for now as I do agree it's off-topic from your current path.

**Comment by rmbolger** [comment]
The ID value may not even be a single piece of data. The AutoDNS plugin I just added actually needs both the zone name and a nameserver reference to modify records in the zone.

The managed alias target definitely sounds more doable. I’m sure you’ve seen it before, but there’s even a Go-based implementation of the idea, [acme-dns](https://github.com/joohoi/acme-dns). The author hosts a usable public instance, but recommends people host their own due to the trust issues involved.
