### ISSUE TITLE
Is a new private key generated on each certificate renewal?

### ISSUE THREAD

**Issue by marshallford** [rmbolger/Posh-ACME#113]
I recently stumbled onto [LE's statement on 90-day cert lifetimes](https://letsencrypt.org/2015/11/09/why-90-days.html) and the first advantage listed got me thinking about the security benefits of short lived certificates.

> They limit damage from key compromise and mis-issuance.

Which led me to ask myself if certbot during renewals is regenerating private keys in addition to public keys. To answer my own question -- yes, according to [this forum thread](https://community.letsencrypt.org/t/do-new-private-keys-get-regenerated-on-certificate-renewal/21486) certbot will, by default, create a new private key. Which gets me to my question: Is Posh-ACME also doing this? I do see a reference to `NewCertKey` as it relates to CSRs but I could use a better explanation on what is happening beyond the changelog bullet point.

Thank you!

**Comment by rmbolger** [comment]
For basic renewals via `Submit-Renewal`, no. New orders created with the exact same parameters as previous orders should attempt to re-use the existing private key. However, you can force a key change by renewing via `New-PACertificate` and using the `-NewCertKey` switch that you saw. The only other parameter you would need is `-Domain` so it can fetch the old order details and fill in the rest automatically. A new key will also be created if you change the key type or size via `-CertKeyLength`. So if you're migrating from RSA to ECC, a new key gets created. Or if you're moving from RSA 2048 to RSA 4096 or one ECC curve to another, a new key is created. The same things happen with direct calls to `New-PAOrder` using `-NewKey` and `-KeyLength`.

Early in the development of the module, I was looking at some other Windows based ACME clients for inspiration and one of them had a fairly unique feature that enabled non-disruptive (e.g. no need to update IIS bindings) renewals by keeping the same private key. And while that feature never actually made it into Posh-ACME, it seemed logical that not always generating new private keys would be less disruptive in general. But I can definitely see the arguments both ways. I'm not sure it's worth changing at this point though.

It should be noted that the *account* key can also be changed via `Set-PAAccount` with `-KeyRollover` and optionally `-AccountKeyLength`.

**Comment by marshallford** [comment]
>  I'm not sure it's worth changing at this point though.

Would you accept a PR for adding a `NewCertKey` switch to `Submit-Renewal` that is false by default? For my use case I was calling `New-PACertificate` explicitly for renewals so enabling the switch was easy, however providing the option to folks using `Submit-Renewal` would be a opt-in security win.

**Comment by marshallford** [comment]
Not sure how I managed to miss this but `Submit-Renewal` does have a parameter for `NewKey` already.

**Comment by rmbolger** [comment]
To be honest, I had forgotten as well. 😂 It’s definitely an on-demand thing though. There’s currently no way to ask the module to always generate a new key aside from specifying the param every time.

**Comment by marshallford** [comment]
Hmm that is an interesting point. I'm fairly new to powershell myself, is there any precedent for saving persistent PS module settings to the registry? If so, might that break cross platform support? (Thinking out loud here)

**Comment by rmbolger** [comment]
The lazy part of me thinks adding `-NewKey` to the scheduled task (or whatever) isn't terribly cumbersome. But it would make it harder if you have multiple certs renewing and you don't want all of them generating new keys each time.

The registry is pretty much a no-go for persisting state across platforms. The typical way you'd save/persist personal PowerShell settings is via a [profile](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-5.1). And in that profile, you could use [`$PSDefaultParameterValues`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_parameters_default_values?view=powershell-5.1) to always send `-NewKey` to `Submit-Renewal` like this:

```powershell
$PSDefaultParameterValues = @{
    "Submit-Renewal:NewKey"=$true
}
```

However, that also suffers from the same problem as just including it in your scheduled task.

Honestly, it wouldn't be too hard to tack another property onto the order object that would effectively be a flag to always generate a new key. It could have an associated parameter like `-AlwaysNewKey` to indicate you wanted it set on a particular order.

**Comment by ravensorb** [comment]
Checking in on this -- I am using a simple Submit-Renewal and it is generating a new key and thumbprint on each actual renewal which is causing a lot of manual work as I need to update multiple config files with each new thumbprint.  Are there ANY workarounds to this even if they are temp ones while a fix is being worked on?

**Comment by rmbolger** [comment]
Hi @ravensorb. I think you might be confused about some terms. This issue is specifically about the private key which is unrelated to the certificate thumbprint.

The private key doesn't change by default on a renewal. You can force the private key to change with `-NewCertKey` on either `New-PAOrder` or `New-PACertificate`. This functionality is actually different to certbot which chooses to always generate a new private key unless you tell it not to.

The thumbprint is basically a SHA1 hash of the public certificate as a whole. And all renewals generate a new public certificate. There's no way around that. Even if all the names and keys stay the same, the change in valid dates will inevitably change the hash of the renewed certificate and thus, the thumbprint.

**Comment by ravensorb** [comment]
Hmm, OK so the question I have is, if I generate a csr based request and renewal and install the cert on a windows box, it just updates the existing cert and all of my sites work.  If I do this with the powershell commands a  ew cert is created and I need to edit every site to use the new cert.  Any idea why there is a difference?

**Comment by rmbolger** [comment]
Is the CSR based request also using Posh-ACME? Or is that a renewal via an internal Windows certificate authority?

There shouldn't be any difference when using Posh-ACME for both. But if you're comparing the renewal process against a Windows CA, there's some magic there that might enable the auto-replacement of the old one without affecting dependent apps. It's also likely to dependent on the app. I honestly don't know if it's possible to replicate via PowerShell though.

**Comment by ravensorb** [comment]
This is in reference to any CSR based renewal (godaddy, verisign, comodo, etc).  If I generate a renewal request and submit it, the cert that I get back can be imported into the certificate store and it replaces the existing cert (no need to update any of the websites that are using the cert).  

The issue I am running into is that I have a set of windows servers that are hosting 20 to 30 sites all with lets encrypt certs.  If I use the renewal process from this library I end up with a new certificate for each site added to the store every 60 days at which point I need to go an update 20 to 30 sites manually to use the new cert.  My expectation would be that the renewed cert would automatically be associated with the corresponding website.  Which has me wondering if I am missing something?

**Comment by rmbolger** [comment]
Yeah, there's definitely some sort of additional processing that happens when you initiate a cert renewal directly from the certificates snap-in. But like I said, I have no idea how that process actually works or whether there's a way to replicate it from PowerShell. My fear is that it requires using the legacy COM based [Cert Enrollment API](https://docs.microsoft.com/en-us/windows/win32/seccertenroll/certenroll-portal) and I purposefully avoided going down that road when I started this project.

That said, if you can find a way to automate the process of initiating that renewal from the snap-in and generating the updated CSR, sending it to Posh-ACME and importing the resulting cert should "just work". Though you likely can't use Posh-ACME's import process because it's importing the full PFX rather than just the signed cert.

The other option (which is better supported/easier in my opinion) is to automate the cert replacement on the IIS sites. Presumably, you've already got a scheduled task or something similar running the renewal commands. You just augment that script with some additional code to update the sites. I've got a (still in development) companion module to this one called [Posh-ACME.Deploy](https://github.com/rmbolger/Posh-ACME.Deploy) with a function called `Set-IISCertificate` that can make this easier. You might use it something like this:

```powershell
Set-PAOrder example.com
Submit-Renewal | Set-IISCertificate -SiteName 'Default Web Site' -Port 443 -HostHeader 'example.com' -RequireSNI
```

The Submit-Renewal function only returns something if the cert was actually renewed. So the Set-IISCertificate will have nothing to do most of the time. The only reason I haven't released the module officially yet is mostly documentation and some final polish. The code for the functions that exist seem to be working for me.

**Comment by ravensorb** [comment]
The idea of the Set-IISCertificate looks great!  I just did something similar :) One suggestion, it would useful if the module could search through all of the sites at associate the cert to any site that had a hostheader that matched one of the names in the ssl cert (subject or dnsnamelist).

**Comment by rmbolger** [comment]
Hey @ravensorb, feel free to submit an issue on the Posh-ACME.Deploy project with the suggestion. I'm gonna close this issue because it's kind of drifted off topic.
