### ISSUE TITLE
Allow alternative config location

### ISSUE THREAD

**Issue by thetrav** [rmbolger/Posh-ACME#118]
First of all, thanks for making this client, it's quite good!

I've noticed that the client config is stored on disk relative to %LOCALAPPDATA% I have a use case where I would like it to be available to multiple different users.

It would be really nice if I could specify a -configRoot or similar parameter

**Comment by rmbolger** [comment]
There's one big problem that makes implementing this feature troublesome (at least on Windows). Most of the plugins have at least one "secure" parameter for the token/password/api key for that service. And on Windows, those secure parameters are stored encrypted in such a way that only the current user on the current computer can decrypt them.

So even if there was a way to specify an alternate config location, the other users on the system couldn't effectively use that config because they can't decrypt the data.

Ironically, this isn't a problem on non-Windows because PowerShell Core hasn't implemented the necessary encryption stuff (yet). So in order to use the plugins at all, you have to use "insecure" versions of the secure parameters. And while you could choose to use the insecure versions on Windows as well, the feature still has to account for the people using secure versions.

Out of curiosity, in your use case would you be willing to store your DNS credentials unencrypted so that all users (with permissions to the location) could potentially read them?

As an alternative, you might consider designating a dedicated service account to run the module as that multiple people can access as necessary. If the system is running in an AD domain, you could even use a [gMSA](https://docs.microsoft.com/en-us/windows-server/security/group-managed-service-accounts/group-managed-service-accounts-overview) so people can just launch a prompt as the user without needing to know a specific password.

**Comment by thetrav** [comment]
Thanks for the details.

In my use case I wasn't even aware that encryption was in play, so yes I've no problem with users who have read-access to the files being able to access those details

A bit more specifics for my scenario:
* I have an Azure Resource Management Template creating a new VM and DNS entry for a server
* Within the template I'm using a custom script (https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/custom-script-windows) to provision the server with a letsencrypt certificate
* Once the machine is provisioned I have other tooling (mostly ansible) for orchestrating the machine that needs to perform operations on the cert (mostly renewals and configuring things like IIS, RDSWeb etc.)

My current stumbling block is that I don't actually know which user/service principal azure is initially running as.  Once I figure that out I can hopefully re-use it.  
There are a few other potential work-arounds I can examine as well, I'm very much in the explore phase here

**Comment by rmbolger** [comment]
I just thought of a way I might be able to make this work without too much extra effort. It doesn’t solve the multi-user encryption problem. But ultimately you can work around it if you just use the insecure parameter options in whatever plugin you’re using.

What if the config location defaults to `%LOCALAPPDATA%` unless a specific environment variable exists like `%POSHACME_HOME%`? If it does, it’ll use that as the base path for the config. It would only be read when the module is imported. So you couldn’t change it on the fly without re-running `Import-Module Posh-Acme -Force`. But it’s probably good enough for most use cases.

**Comment by thetrav** [comment]
I haven't played with environment variables, but I expect I could set them from in the powershell script before invoking the module, so that would certainly work.

FWIW I'm using the Azure DNS plugin, additionally I'm using Managed Identity, so the server running the script doesn't actually need/use credentials to talk to azure services

**Comment by rmbolger** [comment]
Ok, I've got first stab at an implementation of this in the master branch now. The module will now use a path defined by the `POSHACME_HOME` environment if it exists instead of the default location.

You can either set it using whatever config management tool is deploying your VMs or you can just run something like the following before running your code:

```powershell
$env:POSHACME_HOME = 'C:\my\path'
Import-Module Posh-ACME -Force
```

Feel free to give it a shot.

**Comment by thetrav** [comment]
Thanks, I'll give it a shot and let you know how it goes

**Comment by rmbolger** [comment]
This is now live in the 3.2.0 release.

**Comment by thetrav** [comment]
Still haven't gotten around to trying it yet, but will comment when I do

**Comment by thetrav** [comment]
Ok, finally got around to trying this, apologies for the delay:
https://gist.github.com/thetrav/3d3f71a463b1b44e4b09eff5981014c2 is the context of my execution.

It is being executed by the system user, which by default stores files under `C:\windows\system32\config\systemprofile\Appdata` which took me a while to find/figure out.

Now that I've found the files it's not such a major issue for me, but I thought it worth mentioning that simply pasting in the line you recommend:
`$env:POSHACME_HOME = 'C:\my\path'` has not worked, it's still saving to the users appdata folder
