### ISSUE TITLE
Error when using Clouflare.ps1 functions outside of the module

### ISSUE THREAD

**Issue by abulgatz** [rmbolger/Posh-ACME#123]
There's an issue in `Cloudflare.ps1` on line 191 `Invoke-RestMethod`. The `@script:UseBasic` is always null, causing the following:

~~~
Invoke-RestMethod : A positional parameter cannot be found that accepts argument '$null'.
At C:\acme\Cloudflare.ps1:191 char:21
+ ... $response = Invoke-RestMethod "$apiRoot/?name=$zoneTest" -Headers $au ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-RestMethod], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
~~~

I am running `Cloudflare.ps1` directly from a powershell console with `Import-Module` and calling the function `Add-DnsTxtCloudflare` directly.

**Comment by rmbolger** [comment]
The DNS plugin files aren't intended to run outside of the module's scope and they aren't modules all by themselves. `$script:UseBasic` is defined in the module's PSM1 file which wouldn't be loaded if you're just dot sourcing the plugin file or using `Import-Module` directly on the plugin file.

If you really need to run the functions in the plugin manually, you'll have to initialize that variable manually for your session. It would look something like this:

```powershell
$script:UseBasic = @{UseBasicParsing=$true}
```

But I can't guarantee this won't break in the future if the plugin architecture changes in some way. You'd be better off calling the plugin functions via `Publish-DNSChallenge`, `Unpublish-DNSChallenge`, and `Save-DNSChallenge`.

**Comment by abulgatz** [comment]
Thanks for the response!

Am I able to call `Publish-DNSChallenge`, etc. from another script?

If my understanding is correct, `UseBasicParsing` the default on `Invoke-RestMethod` (and `Invoke-WebRequest`) since Powershell 6 (see [here](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-restmethod?view=powershell-6)).

There are also some misspelled variable names in Cloudflare.ps1 that are preventing the script from working. I will make a pull-request with fixed spelling.

**Comment by rmbolger** [comment]
> Am I able to call `Publish-DNSChallenge`, etc. from another script?

Yep, all the public functions in the module are usable from wherever. In your script, you might want to include a [Requires](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_requires) line at the top if it depends on functions from the module like this:

```powershell
#Requires -Modules Posh-ACME
```

And yes, `UseBasicParsing` is the default functionality in PowerShell 6 and beyond. It's also deprecated and may not exist in future versions. But the module supports PowerShell 5.1 on Windows where it's not set by default and causes issues in some environments if it's not set. So the `$script:UseBasic` hashtable is basically me trying to future proof the code so that it's always set in environments that have it as an option and doesn't break in future PowerShell versions where it may not exist anymore.
