### ISSUE TITLE
Intermediate and CA Cert in PFX file

### ISSUE THREAD

**Issue by rian-hout** [rmbolger/Posh-ACME#13]
Can the PFX creation be updated to include the intermediate and root certs?

**Comment by rmbolger** [comment]
I'm pretty sure it can be done. I'd love your opinion on how it should work though.

In particular, I still want the default functionality to be that the PFX only includes the cert/key because that seems like the more common use case on Windows systems. Do you think I should add a second PFX (fullchain.pfx?) that contains everything by default as well ? Or should this be a switch (-PfxFullChain?) that you can set per certificate that adds the chain only as necessary?

**Comment by rian-hout** [comment]
I've run in to several issues in the past where importing a pfx file to a windows server leads to a chaining issue if the intermediate certs are not in the pfx file.  I've also referenced pfx files directly from tomcat instances where there would be a chaining issue if the intermediate and root certs weren't included.  I've made it a habit to always include that intermediate in the pfx so that it is available if the server doesn't already have it installed.

I think that either a switch or just providing the fullchain.pfx would be sufficient, so long as it's an option.  As the script already provides the fullchain.cer and chain.cer, I think just providing the fullchain.pfx would be inline with what you already have.  

On another note, is there a way to set a password on the pfx or will it always be blank?

**Comment by rmbolger** [comment]
When you import a pfx with chain certs into Windows, don't the chain certs end up in the Personal store rather than Intermediate or Trusted Roots where they belong? I swear I've had this happen in the past and it was annoying. But it's also quite possible I didn't know what I was doing back then.

I agree that just including a fullchain.pfx by default is probably the easiest way to go. More switches on a function that's already pretty heavy from a parameter perspective will likely confuse more than help people.

As for the Pfx password, it will always be blank in the current release. The irony is that when I first started writing the module, I had fully planned on being able to specify a Pfx password. I also toyed around with generating a random password. But then it was going to be cumbersome to securely save that password for renewals. Encrypting it using PowerShell native methods would also make the local config non-portable to other systems (or even other profiles on the same machine). So I figured that since the unencrypted private key was already sitting in the folder next to the Pfx, adding a Pfx password wasn't gaining anything from a security perspective (or so it seemed at the time).

In retrospect, I'm guessing there are probably tools out there that break if a Pfx *doesn't* have a password. And I didn't really thing about the case where an automation hook might be copying just the Pfx to a less secure location. So I should probably add that back in. Do you think people will care if the Pfx password is saved in clear text in the order.json? Or should I try to get it encrypted which is more secure but breaks config portability?

**Comment by rian-hout** [comment]
When I import the pfx, I choose the option to let the wizard automatically select the store that a cert goes in to.  I have seen intermediates end up in the personal store, but normally the do end up where they need to go.  

For my automation, I am planning on copying out the pfx file to web servers so it would be great to encrypt that with a password.  I imagine some would have an issue storing the pfx password clear text in the order.json, but like you said, the unencrypted private key is setting there in the same folder.  Also, if the password is autogenerated, it has to be retrieved from somewhere.  

A better option may be to default the pfx password to be blank and adding a switch so that if the user wants to add a password, they can.  Then their is no need for you to autogenerate one and no need for the user to go retrieve the password.  I don't think you necessarily need to store the password either as a new pfx will be generated each time the cert is renewed.  The user will just need to add the pfxpassword switch with the submit-renewal.

**Comment by rmbolger** [comment]
I created a new issue to continue the PFX password conversation in issue #16.

**Comment by rmbolger** [comment]
This is now merged into master pending release with v1.2
