### ISSUE TITLE
Question: Automating wildcard deployment to other servers

### ISSUE THREAD

**Issue by NibblesJabroni** [rmbolger/Posh-ACME#131]
I have a fair amount of experience with automating servers with PowerShell. I would like to automate the deployment of a wildcard cert once it is downloaded onto my management server. 

Is there a file or other data point that is changed when a certificate has been successfully renewed? I can setup another scheduled task to run shortly after the one I'll use for Posh-ACME, which can check if a renewal has occurred, I just need to know what to check. I can pull the ValidFrom property from the cert.cer and compare to the current date, which would trigger a re-deploy of the renewed wildcard cert, but I am wondering if there is a better way?

Also considering adding a small piece of code to New-PACertificate.ps1 on line 239 (after Get-PACertificate) which could set a registry entry indicating a new certificate has been downloaded. 

Thanks so much for your work on this module, it is incredible!

**Comment by rmbolger** [comment]
Glad to hear you're enjoying the module!

`Submit-Renewal` and `New-PACertificate` both call and return the output of `Get-PACertificate` when a new cert has been successfully processed. So if you have a scheduled task calling `Submit-Renewal` daily, you can basically assume that if the function returns nothing, there's no new cert. But if you get a non-null value, it's your new cert details and you can proceed with whatever additional tasks need to be done in order to deploy it.

You can run something like `Get-PACertificate | fl` to get an idea of the properties you can work from. I tried to include everything someone might need like the absolute paths to the files, pfx password, subject, dates, thumbprint, etc.

The way I typically use it is that the deployment code is all part of the same scheduled task as the renewal code. So something like this:

```powershell
$cert = Submit-Renewal; if ($cert) { "Do deploy stuff" } else { "No new cert" }
```

If you definitely want to make them separate, it probably wouldn't be too hard to just append your registry writing idea to the end of the first task's command(s). You might also just be able to key off of the `NotBefore` property of the cert as that should be pretty close to when the renewal happened. Though Let's Encrypt might back date their certs by a bit. I'm not positive on that.

**Comment by NibblesJabroni** [comment]
> But if you get a non-null value, it's your new cert details and you can proceed with whatever additional tasks need to be done in order to deploy it.

Ah! That is brilliant. There was no other reason of keeping it separate other than my own ignorance on how to do it this way.  That is definitely what I'm going to do.  Thanks again for your expertise and especially for your prompt reply!
