### ISSUE TITLE
New-PACertificate fails if -DnsAlias is set to acme.sub1.example.net with Route53

### ISSUE THREAD

**Issue by AlexKichkailo** [rmbolger/Posh-ACME#136]
New-PACertificate fails if -DnsAlias is set to acme.sub1.example.net and the IAM user does not have route53:ListResourceRecordSets permission for sub1.example.net hosted zone.

Obviously, it tries to create a TXT record in sub1.example.net hosted zone which is what I am trying to avoid with the additional hosted zone. 

The issue seems to be in the Get-R53ZoneId function in Route53.  It always ignores the first subdomain since the "i" variable in the "for" loop starts from 1 instead of 0.

**Comment by rmbolger** [comment]
I *think* I understand what's going on. But let me make sure.

The name you're generating a cert for is `sub1.example.net` which is the root of a hosted zone. But you don't want to give Posh-ACME write access to that zone (totally fine). So you have an `acme.sub1.example.net` zone to use for ACME challenge aliases which Posh-ACME does have write access to. So you've created a CNAME of `_acme-challenge.sub1.example.net` that points to `_acme-challenge.acme.sub1.example.net` and you're running something like this to generate a cert:

```
New-PACertificate 'real.example.net' -DnsPlugin Route53 -PluginArgs @{'blah'='blah'} -DnsAlias 'acme.sub1.example.net`
```

Assuming all that is right, I think the problem is that you assumed the alias parameter would prefix `_acme-challenge` to the record it tries to write. But it doesn't. You need to explicitly specify the FQDN of the alias record. So if your CNAME points to `_acme-challenge.acme.sub1.example.net`, the DnsAlias parameter must be identical.

By setting DnsAlias to `acme.sub1.example.net`, it will try to create that exact TXT record which would get created in the protected `sub1.example.net` zone.

**Comment by AlexKichkailo** [comment]
@rmbolger thank you for the detailed answer. Your assumption is correct. The only thing is that I am generating a cert for *.sub1.example.**com**. I am using .net for the separated hosted zone because the responsibility delegation for acme.sub1.example.net is implemented in sub1.example.net. I cannot do it in sub1.example.com. 
If I specify _acme-challenge.acme.sub1.example.net as DnsAlias, then I get the following error

>...
 VERBOSE: Sleeping for 120 seconds while DNS change(s) propagate
VERBOSE: Requesting challenge validations
VERBOSE: POST https://acme-staging-v02.api.letsencrypt.org/acme/challenge/sadadasd/asdads with -1-byte
 payload
VERBOSE: received 229-byte response of content type application/json
VERBOSE: Attempting to find hosted zone for _acme-challenge.acme.sub1.example.net
VERBOSE: Invoking Amazon Route 53 operation 'ListResourceRecordSets' in region 'us-east-1'
VERBOSE: Removing the record from zone ID /hostedzone/asdasdasd
VERBOSE: Invoking Amazon Route 53 operation 'ChangeResourceRecordSets' in region 'us-east-1'
VERBOSE: Saving changes for Route53 plugin
Authorization invalid for *.sub1.example.com: No TXT record found at _acme-challenge.sub1.example.com
At C:\Users\myuser\Documents\WindowsPowerShell\Modules\Posh-ACME\3.3.0\Private\Wait-AuthValidation.ps1:34 char:17
+ ...             throw "Authorization invalid for $($auth.fqdn): $message" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Authorization i...ticaconnect.com:String) [], RuntimeException
    + FullyQualifiedErrorId : Authorization invalid for *.sub1.example.com: No TXT record found at _acme-challenge.sub1.example.com


If I just change i=1 to i=0 in line 539 in Route53.ps1 and pass acme.sub1.example.net as DnsAlias everything works fine.

**Comment by AlexKichkailo** [comment]
ok, looks like I've figured this out. I had CNAME record pointing to acme.sub1.example.net. Changing it to _acme-challenge.acme.sub1.example.net  resolved the issue.

**Comment by AlexKichkailo** [comment]
just a note. the tutorial might be out of date. Regarding CNAME Target, it says "It doesn't really matter as long as the ACME server can query it from the Internet and Posh-ACME can create the necessary records there" so I was assuming that acme.sub1.example.net should work  fine.

**Comment by rmbolger** [comment]
Having the CNAME and DnsAlias parameter pointing to `acme.sub1.example.net` should work. But it means you're creating an `acme` TXT record in the `sub1.example.net` zone. So if `acme.sub1.example.net` is actually a zone where you intend to put other ACME challenge records as well, you'd need to make your CNAMEs and DnsAlias parameters point to `<something>.acme.sub1.example.net` instead of the zone root.

I'll review the tutorial and see if I can make it more clear. Glad you got things working though.
