### ISSUE TITLE
Question: Submit-Renewal without plugindata.xml

### ISSUE THREAD

**Issue by clatini** [rmbolger/Posh-ACME#141]
The Submit-Renewal method without plugindata.xml previously saved, requests for every SAN present in certificate the same PluginArgs:
    
```
PS C:\> Submit-Renewal -MainDomain demo1.sampledomain.com -Force

cmdlet Add-DnsTxtAzure at command pipeline position 1
Supply values for the following parameters:
AZSubscriptionId: 12345678-1234-5678-1234-123456789abc
AZTenantId: 12345678-1234-5678-1234-123456789abc
AZAppCred

cmdlet Add-DnsTxtAzure at command pipeline position 1
Supply values for the following parameters:
AZSubscriptionId:
...
```
Seems that after inserting the PluginArgs manually these are not persisted and not reused.

Any workaround?

**Comment by rmbolger** [comment]
The mechanism that is prompting for the parameters is the native PowerShell parameter validation on the plugin's function parameters. So the only code that has the data is that call's instance of the function. In order to then save the data, the plugin (all plugins to make it always work) would have to then be responsible for re-saving the parameters that were passed to them. I don't think I want to shift the param persistence responsibility to the plugins like that.

Do you have a use-case that prevents you from sending the required plugin parameters with the original call to `New-PACertificate` (so they're saved normally to plugindata.xml)? Or is this more of a security requirement where you don't want those credentials persisted on disk?

**Comment by clatini** [comment]
I needed to move the Posh-ACME folder between different computers and this caused plugindata.xml to become invalid, so I had to delete it.
Another situation is that the DNS Provider credentials have changed between renewals;  also in this case the existent plugindata.xml becomes invalid. A possible solution, could be to add the PluginArgs parameter to Submit-Renewal.

**Comment by rmbolger** [comment]
Instead of running `Submit-Renewal`, you should just re-run the `New-PACertificate` command with the plugin arguments you passed originally. This will re-save the values for plugindata.xml as necessary. This would work for changed credentials as well. The new `PluginArgs` would overwrite the old ones for that particular plugin. 

If you're worried about the difference between getting a new cert and renewing an old cert, don't be. There's actually no difference from an ACME server perspective.

**Comment by clatini** [comment]
OK, thanks for your support.
