### ISSUE TITLE
Support FreeDNS

### ISSUE THREAD

**Issue by yuljk** [rmbolger/Posh-ACME#143]
Hi guys - Would be great to get PowerShell support for FreeDNS domains.  I'm using acme.sh for my Linux hosts which has a shell script for reference.

https://github.com/Neilpang/acme.sh/blob/master/dnsapi/dns_freedns.sh

This would be awesome to get working for my IIS hosts.

Kind Regards
Chris

**Comment by rmbolger** [comment]
This one isn't quite as straightforward as other plugins because they don't actually have a REST API. The acme.sh plugin is basically parsing HTML and programmatically submitting form fields. Not impossible to deal with obviously, but might take me a bit to get started because I'm working on some other stuff at the moment.

**Comment by yuljk** [comment]
Many thanks for the response rmbolger.  Much appreciated.

**Comment by rmbolger** [comment]
I just realized that FreeDNS prevents automated record adding with a CAPTCHA challenge for public zones and I don't currently have any private ones with them. So I can't actually test things myself. I presume you have private zones to test against?

**Comment by rmbolger** [comment]
It turns out the CAPTCHA challenge only applies to domains you don't own on free accounts. Also regardless of your account type, you can't create records that begin with `_` unless you own the domain. In any case, the plugin is complete and has been merged into the master branch pending inclusion in the next release. Feel free to try it out when you get a chance.
