### ISSUE TITLE
Renewal without DNSPlugin

### ISSUE THREAD

**Issue by pedrofernandesfilho** [rmbolger/Posh-ACME#148]
Hello!

If I created a certificate without DNSPlugin (because DNSServer do not have API), is possible use the Renewal command? If yes, how? If no, when the certificate expire, the one way is create a new certificate manually?

**Comment by rmbolger** [comment]
Unfortunately not. The `Submit-Renewal` command skips orders that do not have a DNSPlugin associated with them because they require user interaction. Instead, you can run the same `New-PACertificate` command again to renew.

There is actually no difference between a new and renewed certificate. All `Submit-Renewal` is doing is re-running `New-PACertificate` for you using saved values.

**Comment by pedrofernandesfilho** [comment]
Ok. Thanks by explanation.
