### ISSUE TITLE
Feature Request: Automatic Renewal

### ISSUE THREAD

**Issue by alexbeeston** [rmbolger/Posh-ACME#156]
I've browsed the repository, but I can't find indications that this program supports certificate auto-renewal. Can you please confirm that it does not exist or show me where in the documentation I can learn about this feature? If it's not currently supported, is this something you would consider? Thanks.

**Comment by rmbolger** [comment]
PowerShell doesn't have any built-in way to run recurring tasks. You'd have to rely on the OS specific scheduling utilities such as Task Scheduler, cron, etc. to setup a daily task to run the appropriate `Submit-Renewal` function for your configuration. There's a bit more explanation about it in the [Renewing A Certificate](https://github.com/rmbolger/Posh-ACME/blob/master/Tutorial.md#renewing-a-certificate) section of the tutorial. Re-reading that section now, it could probably use some additional guidance around how best to setup a task.

Specifically, you should generally run the `Submit-Renewal` function once or twice a day at an ideally random time. The function will throw a warning but otherwise return nothing while the certificate hasn't reached its renewal window yet. Once it does, it will attempt to renew the certificate and if successful, it will return the cert details the same way `Get-PACertificate` returns them.

So a renewal script might look something like this:

```powershell
Set-PAOrder example.com
$cert = Submit-Renewal
if ($cert) {
  # do additional cert replacement stuff if necessary
}
```

**Comment by mikes-gh** [comment]
Can you add this to the docs
This is the only place I could find this info and it is a common scenario to do something when the cert is renewed 👍

**Comment by rmbolger** [comment]
Yes! Totally meant to earlier and keep forgetting. Gonna go do it now.

**Comment by Zerorigin** [comment]
Make automatic renewal more easily, just like [acme.sh](https://github.com/acmesh-official/acme.sh).
For Windows, we can use this module: [ScheduledTasks](https://learn.microsoft.com/en-us/powershell/module/scheduledtasks/).
For Linux there is also another module: [CronTab](https://github.com/PowerShell/PowerShell/tree/master/demos/crontab).
