### ISSUE TITLE
Question about windows DNS option and possible DNS plugin request - ENOM

### ISSUE THREAD

**Issue by Zrowsdower** [rmbolger/Posh-ACME#158]
Would i be able to use the windows DNS plugin and utilize my internal AD/DNS server by creating a zone for the domain i intend to create a cert for? if so i wouldn't necessarily need the ENOM plugin.

but if not, I'd like to request a DNS plugin for registrar/host enom.com

**Comment by rmbolger** [comment]
You can only use you Windows DNS server if it is the authoritative nameserver for your internet facing DNS zone. It would also work if it is a master server that you have other internet facing nameservers setup to slave against.

I quickly scanned Enom's support site and while they do have some sort of API, it appears to be geared towards reselling domains and doesn't seem to have any functions for DNS record management which is a requirement in order to create a plugin. However, there's no reason you need to keep using Enom's DNS hosting. You could move it to another provider that already has a plugin and just keep using Enom as the registrar.
