### ISSUE TITLE
Cloudflare Dns Plugin has error when following API Secure Token steps

### ISSUE THREAD

**Issue by smapty** [rmbolger/Posh-ACME#175]
When I tried to use the secure token in order to do DNS authentication with Cloudflare, I receive the following error.
```
`Invoke-RestMethod : Specified value has invalid Control characters.
Parameter name: value
At C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\3.6.0\DnsPlugins\Cloudflare.ps1:244 char:21
+ ... $response = Invoke-RestMethod "$apiRoot/?name=$zoneTest" -Headers $Au ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-RestMethod], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand`
```

**Comment by rmbolger** [comment]
Hey @smapty. Sorry to hear you're having trouble. I can't say I've seen that error before. But the message makes it sound like maybe you accidentally copied some invalid characters into your token variable or the domain name.

There were actually some typo's in the Cloudflare usage guide that got reported and fixed by another user earlier today. But even if you were using the bad version, it wouldn't have generated this error. It would just prompt for the CFAuthEmail and CFAuthKey parameters in the default parameter set for the plugin.

I'm trying to see if I can reproduce the problem on my end by purposefully adding control characters to various things. But no luck so far. In the mean time, double check your string values for the domain names and token variable to make sure there's no invisible control characters in them. Sometimes I'll copy things into Notepad first and then re-select, copy, and paste.
