### ISSUE TITLE
Existing certificate is not installed when using -install parameter

### ISSUE THREAD

**Issue by wiseleaf23** [rmbolger/Posh-ACME#180]
So I was testing this very nice PS module to automate some server task. The first command I ran was the following:
New-PACertificate rd.contoso.com -AcceptTOS

I then did some more research into where the certificate would be placed, and use the command again, but with the -Install switch
New-PACertificate rd.timmermans.family -AcceptTOS -Install

According to the documentation, this uses the current certificate if it has not expired yet, but the certificate was not installed. After I used the command with the -Contact parameter, a new request was done and the cert was publish to the certificate store.

Please note that I used no DNS plugin at the moment, just manual.

**Comment by rmbolger** [comment]
Hi @wiseleaf23. Thanks for the report. Can you post a link to the documentation you were reading and roughly where it talked about using the current certificate? I want to double check it and maybe clarify a misunderstanding.

Once `New-PACertificate` has completed an certificate order, it won't let you make a new request with the same details unless you use the `-Force` switch or the previous order has reached the suggested renewal window. There's a message about it if you use the `-Verbose` flag, but in retrospect, this should probably be a warning messages so it's always shown in the console.

If all you want to do is install the certificate you already got because you forgot the `-Install` flag originally, there's a separate command that can do it called `Install-PACertificate`. However, this doesn't update the order details to then always install it in the future. And at the moment, there's no obvious way to do that without actually getting a new certificate which definitely seems like a limitation worth fixing. I'll probably make this an optional parameter in `Set-PAOrder` so that you can do something like `Set-PAOrder -Install` to toggle on or off the auto-install option for that cert.

**Comment by rmbolger** [comment]
Commit 8ebfa4f contains the changes to Set-PAOrder that would allow you to modify things like the Install property on an existing order. For `-Install` specifically, it will not immediately install the cert. You'd still need to run `Install-PACertificate` manually. But it will automatically install the cert on subsequent renewals.

**Comment by wiseleaf23** [comment]
Hi @rmbolger ,

Thank you for the quick response. I read in Get-Help New-PACertificate -Detailed (-Force parameter) that the existing order would be used, but I interpreted it like a new certificate would be requested, with that existing order. To my understanding, running the command with the -Install switch would've installed that "New" certificate but I didn't, and the cmdlet did not produce any output (without -Verbose).

Seeing the "Install-PACertificate" cmdlet, using that makes way more sense. Maybe you can put a warning in the script that nothing will happen if you run the New-PACertificate cmdlet for the same domain to confirm that nothing will be done.

Thank you for all the work on the module, I really like it!
