### ISSUE TITLE
Install Certificate Location

### ISSUE THREAD

**Issue by MetUys** [rmbolger/Posh-ACME#193]
Firstly beautiful module, great work here.
I know the specific implementation on each setup is outside the scope of this project, however I see in the "Import-PfxCertInternal" function you declare $StoreName and $StoreLoc. Would you ever consider exposing that to allow for the 'WebHosting' store to be used?
maybe an optional parameter to invoke the Webhosting store as the install location?

i.e. New-PACertificate example.com -Install WebHosting

and hopefully store that so the renewal uses that too?

**Comment by rmbolger** [comment]
I have actually considered it. My fear is complicating the parameters in New-PACertificate too much. I've also considered removing the `-Install` switch entirely now that `Install-PACertificate` exists and maybe just fleshing out the parameters on it instead. Allowing import into the user store rather than the system store is also something I wanted to enable.

The `-Install` parameter on `New-PACertificate` never really felt right since it only works on Windows and generally the module tries to focus on getting the certs rather than deploying them. But the soonest it would ever go away is 4.x.

Would an expanded version of `Install-PACertificate` work for your purposes?

**Comment by MetUys** [comment]
Hi,

The expanded version of Install-PACertificate would work for me.
Having a parameter on that for cert location also makes sense with that
flow.

I also agree with the idea of stripping the -install out of
New-PACertificate entirely, sperating the certificate generation from the
install.

**Comment by rmbolger** [comment]
Just pushed an update to dev/master with expanded functionality for `Install-PACertificate`. Give it a whirl and see if it works for you.

**Comment by MetUys** [comment]
Works Great!

**Comment by MetUys** [comment]
Can you push this into the main master branch, so that we can look at using it production roll outs?
Right now we have to grab the dev-master, and if that step is forgotten then it wont understand the parameters.

PS: Again that's for a great product, it meets all our needs now. and is in the process of becoming our own ACME client. Good job.

**Comment by rmbolger** [comment]
The change is included in the 3.11.0 release I just pushed out.
