### ISSUE TITLE
ECC Certificate Install doesn't allow quick export from IIS Manager

### ISSUE THREAD

**Issue by MetUys** [rmbolger/Posh-ACME#196]
Hi,

If I issue New-PACertificate example.com -Install
Im able to export the installed certificate from Certificate Store in IIS

But if I issue New-PACertificate example.com **-CertKeyLength ec-256** -Install
Im unable to export the certificate from the Certificate store in IIS.

How can I get the ECC certificate to be exportable?

**Comment by rmbolger** [comment]
This is definitely not intended. And it's the same code that ultimately imports the cert for either type, so I'm not sure why exporting wouldn't work for ECC certs. I'll take a look and see if I can verify and figure out what the issue is.

**Comment by rmbolger** [comment]
Just to clarify, you're trying to export directly from the IIS Manager rather than the the Certificates snap-in in an MMC instance? Also, what OS is this on?

**Comment by rmbolger** [comment]
After testing a bit with IIS on my end, I think I understand what's going on.  From the IIS Manager, you're looking at the `Server Certificates` section, right? And when you select or right-click on an RSA based cert, you get an option to "Export". But that option is missing for the ECC certs? At least that's what I'm seeing on a Server 2016 test box.

RSA cert ![image](https://user-images.githubusercontent.com/2327255/68419437-1257a780-014f-11ea-9da1-32cbdccacc9c.png) versus ECC cert ![image](https://user-images.githubusercontent.com/2327255/68419466-226f8700-014f-11ea-93dc-bca448ab4886.png)


Honestly, I have no idea why IIS is treating those ECC certs differently and preventing the "quick" export functionality. It's likely a deficiency in the IIS manager code though.

However, you can still export those certs. You just have to do it slightly differently so that you get the native Windows cert export wizard instead of the IIS quick one. 

- Select the `View` action on the cert to bring up the cert details
- Select the `Details` tab
- Click the `Copy to File...` button at the bottom
- This should bring up the standard Windows Certificate Export Wizard which should give you the option to export the cert with the private key.

**Comment by MetUys** [comment]
Hi,
Sorry for the late reply.
100% correct.
I also did a bit of playing around myself, even with the powershell
commands and got the same odd result.
So I agree, doesn't seem to be a problem with the Posh-ACME system, but
rather IIS manager.
I will look into it more tomorrow, as the export was only a 'known symptom'
that prevents a different service from using the certificate correctly, so
when I noticed the option missing I just raised a concern. so I need to see
if that other system works regardless of the ECC certificate showing export
in IIS or not.

I'm also glad to know that my results are replicatable on other systems, so
not something I am doing wrong either.

I think we close this now as you mentioned there is no difference in code
at least between what is done with an RSA VS ECC certicate install.
