### ISSUE TITLE
Root Certificate

### ISSUE THREAD

**Issue by omarc1492** [rmbolger/Posh-ACME#198]
Similar to this [issue](https://github.com/rmbolger/Posh-ACME/issues/13).

Is it possible to create the PFX container with the root certificate included? Right now the certificate path for the PFX container includes only "Lets Encrypt Authority X3" but not "DST Root CA X3" unless it's modified.

Original
![original](https://user-images.githubusercontent.com/10967529/68638501-5d631900-04c7-11ea-921f-970dd2c4e70c.jpg)

Modified
![modified](https://user-images.githubusercontent.com/10967529/68638500-5d631900-04c7-11ea-986e-d70ade13545b.jpg)

**Comment by rmbolger** [comment]
The root certificate is not provided by the ACME server in the chain that gets downloaded as part of the protocol. It's not something that is generally needed because clients already have the root in their trust store. If they didn't, they wouldn't trust the cert even if the root was included in the PFX.

The issue you linked to makes more sense because servers generally do need to send the intermediate cert chain along with the leaf certificate for clients to more easily validate the trust chain if they only currently trust the root.

Why do you think you need the root in the PFX?

**Comment by omarc1492** [comment]
@rmbolger Thanks for the info. I need them for the Window Servers that will host a new ERP system. One of the requirements is to have a PFX container with the root certificate and all other certificates. Right now the current PFX certificate has to be imported and then exported to include the root certificate.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rmbolger** [comment]
Unfortunately, there's no easy way to get the root certificate in an ACME server agnostic fashion. Let's Encrypt isn't the only ACME based CA out there and Posh-ACME is designed to be compatible with all of them.

For Let's Encrypt specifically, it's also complicated because there are multiple roots available due to [cross-signing](https://letsencrypt.org/certificates/).

I could possibly add a function that makes it easier to import and then re-export like you're already doing manually. But I can't make things like `New-PACertificate` or `Submit-Renewal` do that by default because it relies on Windows-only functionality.

As an aside, I might also ask your ERP vendor why their software needs the root included in the leaf's PFX rather than just importing it separately to a trusted root store if it doesn't already have it.

**Comment by omarc1492** [comment]
Could you please create such a function? Having it automated would save time. 

I’ll ask the ERP vendor, thank you.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rmbolger** [comment]
I'll see what I can come up with. Dealing with the Windows cert store has historically been...more trouble than it should be. heh

**Comment by rmbolger** [comment]
It looks like Microsoft beat me to it with [Export-PfxCertificate](https://docs.microsoft.com/en-us/powershell/module/pkiclient/export-pfxcertificate). It appears to be usable in Windows Server 2012 or later and Windows 10.

Here's how you might use it. I'll assume you've already imported the cert via `New-PACertificate -Install` or `Install-PACertificate`.

```powershell
# get a reference to the imported cert
$cert = Get-Item "Cert:\LocalMachine\My\$((Get-PACertificate).Thumbprint)"

# convert the PfxPass to a SecureString
# (or use whatever value you want)
$secPass = ConvertTo-SecureString (Get-PAOrder).PfxPass -AsPlainText -Force

# export the cert with the full chain including the root
$cert | Export-PfxCertificate -FilePath .\cert.pfx -ChainOption BuildChain -Password $secPass
```
