### ISSUE TITLE
Godaddy challenge update

### ISSUE THREAD

**Issue by yuvraj-clover** [rmbolger/Posh-ACME#202]
Hi,
I am new to this so forgive me if its a noob question.

I have been trying to renew my certificate. When I run Submit-Renewal command it generates a new certificate but it does not update the new challenges on godaddy. It will clear the previous record with a null value but it wont update the new value or it wont output the new values. It worked fine when I created the certificate. 

This is the command I am using- Submit-Renewal 'testa.xxxxxxx.com' -PluginArgs $ParamsGD -Verbose -Force

**Comment by rmbolger** [comment]
Hi @yuvraj-clover. No worries at all. This whole process can definitely be confusing when you're first getting started.

How long has it been since the first certificate was created? The authorizations for the names you use in the certificate get cached by Let's Encrypt for about 30 days. In other words, you've already proved you control `example.com`, so they don't make you re-prove it for at least 30 days. So if you force a renewal before then, the client doesn't need to re-validate those authorizations which means no new TXT record creation is necessary.

If you're looking to perform a more real test of the renewal process without having to wait for the 30 day cache to expire, you can (since version Posh-ACME 3.11.0) revoke those authorizations and then try forcing the renewal. Here's the simplest way to revoke the authorizations in your order.

```powershell
Get-PAOrder | Revoke-PAAuthorization
```

**Comment by yuvraj-clover** [comment]
That worked. Thanks a lot for your prompt reply. I was testing it that is why I tried to renew before 30 days.
Just one more question- Is going to renew the next one by itself and update the records on GoDaddy or I have to manually run Submit-Renewal command.

**Comment by rmbolger** [comment]
Something has to run the renewal command. You can choose to do it manually or setup something like a scheduled task to do it for you. I actually recently added some guidance about this in the [Renewals and Deployment](https://github.com/rmbolger/Posh-ACME/blob/master/Tutorial.md#renewals-and-deployment) section of the tutorial.

**Comment by yuvraj-clover** [comment]
Ok Thanks a lot for developing this, saves a lot of time and works great.
