### ISSUE TITLE
New-AzureRmWebAppSSLBinding : Operation returned an invalid status code 'NotFound'

### ISSUE THREAD

**Issue by modemgeek** [rmbolger/Posh-ACME#203]
Odd issue here.  I wrote the code, excerpt below, and everything works fine.  I gave the same code to a collegue.  He gets an error when trying to bind the certificate to an azure webapp.  we have been troubleshooting for weeks now.  Here's what we do know.  We are running the same version of Azure PS.  We have the same version of Posh-Acme.  The content of the script are identical.  When he runs, he gets a certificate could not be found.

If he gives me the same certificate and I try to bind from my computer, it fails too.  However if I give him the certificate file from my computer and he runs the binding cmdlet it installs fine.

So, where does it leave us?  why would his computer and another one we tried create a "bad certificate"?  to complicate the issue, if we upload the certificate through the azure portal, we dont get an error and we can bind.

Does anyone have any suggestions?

New-PACertificate -Domain $domain -FriendlyName $Alias -PfxPass $PfxPass -DnsAlias $domain -force 

New-AzureRmWebAppSSLBinding -WebAppName $WebApp -ResourceGroupName $resourcegroupname -Name $domain `
        -CertificateFilePath "$path\$domain-fullchain.pfx" -CertificatePassword $PfxPass -SslState SniEnabled

**Comment by rmbolger** [comment]
This is definitely an odd one. Can you post the full error text you get from the `New-AzureRmWebAppSSLBinding` command? Is it possible the variables like `$path` in your parameters are different and end up wrong for the "bad" certificate? Are there any non-ascii characters in the domain names that might be triggering a weird edge case?

Side note: Why are you specifying a `-DnsAlias` parameter that uses the same value as `-Domain`? DnsAlias isn't necessary unless you're using [CNAME challenge aliases](https://github.com/rmbolger/Posh-ACME/blob/master/Tutorial.md#advanced-dns-challenge-aliases) and in that case, the alias value should be different from the domain value. I don't think it's negatively affecting things in this case, but it shouldn't be necessary.

**Comment by modemgeek** [comment]
Operation returned an invalid status code 'NotFound' is the full error.  

However, we tried an older version of the cmdlet and it gives a little more detail.  

Certificate D27EE1A8955625902B2E355B4A2F7C2E577E00D4 was not found.

This is the same error that shows up in our Azure log. The New-AzureRmWebAppSSLBinding is supposed to upload the certificate and bind it.  I believe we get the error because it cant upload successfully or cant be found once uploaded. I believe it is the former because the cery never shows up in our account. I can remove -dnsalias but it doesn't make a difference.  It was leftover when i was testing with AWS Dns. No strange characters.  On the computer it works i can generate for multiple domains, no issue.  On the computer it fails, it fails for all.  If it helps i can send you a "good" cert and a "bad cert". We have opened a case with Azure as well, but that didn't go anywhere. They are always quick to point the finger at 3rd party software.  Is there any other dependencies that could affect how the certificate gets created?  I checked .net versions as well and we are on the same version.

**Comment by rmbolger** [comment]
There's a crypto library it depends on called BouncyCastle, but it's included with the module. So nothing external. However, another user ran into an issue (#201) recently where another app on the machine had installed an older version of BouncyCastle into the .NET GAC which PowerShell was using instead of the version included with the module. Something similar could be going on here because that library is responsible for creating the PFX files. But I would think things would be more broken if that was the case (like not being able to even generate the cert at all).

On the bad machine after generating a cert, try running the following to see where BouncyCastle was loaded from. It should be within the module's path and the GAC column should be `False`.

```powershell
[System.AppDomain]::CurrentDomain.GetAssemblies() | ?{ $_.Location -like '*Bouncy*' }
```

Coincidentally, I'm very likely going to be renaming the module's copy of the DLL in the next version to try and avoid these GAC conflicts in the future.

If you want to send me copies of the good/bad cert, I'd be happy to try and do some parallel research as well. *z97y9drumh at snkmail.com*

Another thing I just thought of. Is it possible to separate the upload of the cert from the binding of the cert? Like perhaps a separate upload command would at least generate a more enlightening error? I'm surprised the Azure support team didn't make you try using the Az module instead of the older AzureRm modules? Have you tried that yet just as a stab in the dark?

**Comment by modemgeek** [comment]
Subject                    NotAfter             KeyLength Thumbprint                               AllSANs                  
-------                    --------             --------- ----------                               -------                  
CN=www.joaosite.dx1app.com 2/20/2020 4:26:03 PM 2048      37D6299A979CFDFF40738D2CC4F6869995729F18 {www.joaosite.dx1app.com}



PS C:\Windows\system32> [System.AppDomain]::CurrentDomain.GetAssemblies() | ?{ $_.Location -like '*Bouncy*' }

GAC    Version        Location                                                                                                                                                                
---    -------        --------                                                                                                                                                                
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\3.8.0\lib\BouncyCastle.Crypto.dll   

there isn't a cmdlet to upload separately.  you can manual upload via azure portal.  if we do that and bind using the thumbprint, that works.  MS did ask us to try Az, since they said they wouldn't fix any bugs with Rm cmdlets.  I tried running on a clean install of Az and posh-acme and it did work.

**Comment by rmbolger** [comment]
So I tried using `New-AzureRmWebAppSSLBinding` just like you did with the certs you sent me against a test web app I spun up in my own portal. Unfortunately, both generated a "Conflict" error because my web app's hostname doesn't match the cert's hostname. However, both appear to have been successfully uploaded to my account in the web app's PFX list. I was using the latest version of the AzureRm.Websites module, 5.2.0.

I did this with debug logging enabled which was actually quite verbose and might be useful for further narrowing down your "NotFound" error. Try running `$DebugPreference='Continue'` before calling the binding function and see what you get.

On the other hand, if the newer Az module is working even on the machine that's usually failing, it might be worth migrating to it just to get past this weird blocker for your project. I can't find any obvious differences between the good and bad PFX files other than things that should be different because they're different certs.
