### ISSUE TITLE
Dealing with new certs after they are generated

### ISSUE THREAD

**Issue by kquamme-bcycle** [rmbolger/Posh-ACME#204]
Hi,

I'm working on replacing an ACMEv1 implementation with Posh-ACME. We had the original implementation set up to use a specific ACME vault and it would drop all of the certs into one vault and name them with the domain they were for. I have followed the tutorial and got Posh-ACME working, but I haven't figured out these additional steps. Has anyone else come up with a good way to deal with something like this?

**Comment by rmbolger** [comment]
Hi @kquamme-bcycle. Happy to try and help guide your migration. I'm not sure what you mean by "vault" in this context though. Are you talking about an enterprise password vault like Hashicorp, CyberArk, etc.?

**Comment by kquamme-bcycle** [comment]
Thanks @rmbolger. We were previously using the ACMESharp PowerShell client which stored new certs in a "vault". There was a command that made it possible to specify the directory location and name of the new cert, so we could drop all of them in one directory and append the domain name to the cert name to find them. Here's a link to some documentation from that project: https://github.com/ebekker/ACMESharp/wiki/%5BWIP%5D-Installation:-ACMESharp-PowerShell-client

Is there a way to replicate this behavior with Posh-ACME? Maybe just a way to grab the cert location after generation and use that to copy it to another location?

**Comment by rmbolger** [comment]
Gotcha. Yes. When `New-PACertificate` and `Submit-Renewal` succesfully generate a new certificate, the cert details are returned as an object to the pipeline that contains properties like Subject, NotAfter, and Thumbprint as well as a number of properties that contain the full paths to the various files that were created. It's the same output you get from the `Get-PACertificate` command. As easy way to see what's returned is just running

```powershell
Get-PACertificate | Format-List
```

When automating the deployment on subsequent renewals, the typical daily renewal script might look something like this. `Submit-Renewal` returns nothing when it skips a renewal because the suggested renewal window hasn't been reached yet. So nothing will happen until it actually does renew the cert.

```powershell
Set-PAOrder example.com
if ($cert = Submit-Renewal) {
    # do stuff with $cert to deploy it
}
```

In your case, copying some of the cert files to a new location would just be a matter of building your destination path variable and using `Copy-Item` with something like `$cert.FullChainFile` and `$cert.KeyFile`

**Comment by kquamme-bcycle** [comment]
Thanks for the help; got this working today!
