### ISSUE TITLE
BIND/RFC2136 Plugin Request

### ISSUE THREAD

**Issue by nodrogneirbo** [rmbolger/Posh-ACME#210]
Are there any plans to implement a DNS Plugin for a BIND server or is there another plugin that works with BIND (nameD)?

**Comment by rmbolger** [comment]
Hi @nodrogneirbo. I'd actually love to get a BIND plugin working. The problem is that the only supported way to update a BIND server remotely that I know of involves using the Dynamic DNS protocol (RFC2136). And PowerShell's native DNS client support is rather limited and doesn't have a good way to send arbitrary DDNS updates. Even outside of PowerShell, there are no built-in tools I know of that can send arbitrary DDNS updates from Windows.

A while back I had found a [third party .NET DNS library](https://github.com/alexreinert/ARSoft.Tools.Net) that might have worked. But it seems to be abandoned now and doesn't support .NET Core. So it would be a bad choice to rely on unless the project is actively maintained again.

It might be possible to put something together that uses BIND's nsupdate. But users would have to install it first and calling out to external utilities isn't the cleanest thing to code against. I'm guessing the plugin would be fairly brittle.

Are you planning on running this from Windows? If so, have you been able to do any sort of DDNS updates against your BIND server manually?

**Comment by nodrogneirbo** [comment]
Thanks for your reply @rmbolger 
I haven't tinkered with DDNS updates yet. I thought about using SSH to write to the zone files and reload BIND but that is overkill given BIND now supports dynamic updates.
I am just investigating how we could use LetsEncrypt to provide certificates for our numerous Windows Domain Controllers so that we can use LDAPS using our public FQDN given the looming switch-over from Microsoft to only use Schannel for LDAP queries.
I figured Posh-Acme might be just the job if we can get our BIND server to update.

**Comment by rmbolger** [comment]
Coincidentally, I recently authored a blog post on this very topic!
https://www.dvolve.net/blog/2019/12/using-lets-encrypt-for-active-directory-domain-controller-certificates/

In your case, it sounds like the only problem is that your public facing DNS zones are on BIND and there's currently no DDNS/RFC2136 plugin available. In lieu of figuring out a way to do DDNS updates directly to your public BIND servers, you might also consider using [challenge aliases](https://github.com/rmbolger/Posh-ACME/blob/master/Tutorial.md#advanced-dns-challenge-aliases). It allows you to effectively redirect the DNS challenge records to another zone that is hosted on a provider/platform that there is a plugin for.

**Comment by nodrogneirbo** [comment]
It was that blog which brought me here ;-)
I guess challenge aliases is the simplest way forward.
Time to start playing!
thank you.

**Comment by rmbolger** [comment]
The initial setup is a bit more cumbersome with having to create the CNAMEs. But once that's done, it works just like a regular setup with regards to automated renewals. Let me know if you have any trouble.

I'm gonna leave this issue open just as a reminder to keep looking for good way to do RFC2136.

**Comment by rmbolger** [comment]
Got antsy during quarantine and whipped up an RFC2136 plugin that utilizes an external copy of `nsupdate`. It's not ideal, but it's less brittle than I thought it would be and it's definitely better than nothing. It should be included in the next release.
