### ISSUE TITLE
Trouble using Godaddy plugin

### ISSUE THREAD

**Issue by fnahum** [rmbolger/Posh-ACME#214]
(translated from original issue title)

I am having trouble trying to verify the certificate with Godaddy's plugin. I have already added the TXT record and CNAME record in my DNS. But I'm still having the same error. Any suggestion to fix this?

**Comment by rmbolger** [comment]
Hi @fnahum. Sorry to hear you're having difficulties. In order to help, I'm going to need a bit more detail on your problem. You mentioned getting an error, but you didn't say what it was. 

Can you post the text of that error? It would also help if you could post the command you tried to run that generated the error.

You mentioned using a CNAME, but normally that's not necessary if your hosting provider is Godaddy. Can you elaborate on what the CNAME was for?

**Comment by fnahum** [comment]
Hi, thanks for your response, the error I am getting is "Unable to find matching zone for _acme-challenge.test.esdigital.mx."

**Comment by rmbolger** [comment]
Perfect. That narrows it down a bit. Can you run the following and post the output so I can try to debug what's doing wrong?

```powershell
# turn on debug logging
$DebugPreference = 'Continue'

# use your own key/secret here
$pArgs = @{GDKey='xxxxx';GDSecret='xxxxx'}

# attempt to publish a fake challenge
Publish-DnsChallenge test.esdigital.mx (Get-PAAccount) fake GoDaddy $pArgs -Verbose
```
