### ISSUE TITLE
Azure DNS Plugin: Restrict DNS record search to a particular resource group. 

### ISSUE THREAD

**Issue by rbruelisauer** [rmbolger/Posh-ACME#229]
It would be great if the resource group to be searched could be limited.

New-PACertificate ... -AZSubscriptionId ... -AZTenantId ... **-AZResourceGroup 'my-az-resourcegroup'**

**Comment by rmbolger** [comment]
Hi @rbruelisauer. Can you explain the use-case for this over the existing "search everything" method? I'm not opposed to the idea, I'm just trying to understand better. Do you have multiple copies of the same public zone in different resource groups that are breaking the zone search function? Is it a performance thing because the initial query for all zones takes too long because there are so many?

The only downside to adding this is that it's saved at the ACME account level. So it will then restrict you to zones in that resource group for all certificates you request from the current account. For a mandatory parameter, that would likely be a problem. But since it's optional, it's probably ok as long as we call it out in the readme.

**Comment by rbruelisauer** [comment]
Hello Ryan.

Thanks for reaching out to me.

I started the pull request, because I got a case where I only have
Contributor Rights on the Resource Group, but not on Subscription Level.
If I use the PoshACME DNS Plugin from current master, I get a "Access
denied" because currently it tries to search all DNS zones in the
subscription.

With the proposed code change, PoshACME also works when you have
"Contributor" permission to a particular resource group only, but no access
on the subscription level.

Best regards

Ramon Brülisauer.

Principal DevOps Engineer.

Ingenieur FH


--

*DevOps. Continuous Integration. Sauber. Automatisch. Zuverlässig. *
*Namics.*

A Merkle Company

Namics AG – A Merkle Company

Unterstrasse 12, CH-9000 St. Gallen

Telefon +41 (0)71 228 67 77

Mobile +41 (0)79 628 94 01

ramon.bruelisauer@namics.com


namics.com
<http://www.namics.com/?utm_source=Mailfooter&utm_medium=Mail&utm_term=&utm_content=Website&utm_campaign=Mailfooter>
, blog.namics.com
<http://blog.namics.com/?utm_source=Mailfooter&utm_medium=Mail&utm_term=&utm_content=Blog.Namics&utm_campaign=Mailfooter>
, twitter.com/namics


--


Am Di., 17. März 2020 um 16:28 Uhr schrieb Ryan Bolger <
notifications@github.com>:

**Comment by rmbolger** [comment]
Oh interesting. That makes sense. How likely do you think it is that someone might be in a similar situation, but have access to multiple different resource groups (yet still not all of them). Do you think it's worth allowing `AZResourceGroup` to take multiple values (as an array or just comma delimited)? Just wondering how likely it would be for someone to want a cert that contains multiple names from zones in different resource groups.

After revisiting the code, I also recall thinking there might be a more efficient way to find the zone if you already know the resource group.

**Comment by rbruelisauer** [comment]
Hi Ryan.

Do you think it's worth allowing AZResourceGroup to take multiple values
> (as an array or just comma delimited)?

Just wondering how likely it would be for someone to want a cert that
> contains multiple names from zones in different resource groups.


Hmmm.... That's a rather good question.
Currently, you just need subscription rights to do so, right?
So it should be possible.

After revisiting the code, I also recall thinking there might be a more
> efficient way to find the zone if you already know the resource group.


The search part is straightforward. The REST Method URL to query a zone in
a particular resource group is basically the same as for subscription
level, you just need to add "/resourceGroup/$(resourceGroupName)".
I'd loop the resource groups, since I did not find any better API methods
in the docs (https://docs.microsoft.com/en-us/rest/api/dns/).

Best regards

Ramon Brülisauer.

Principal DevOps Engineer.

Ingenieur FH


--

*DevOps. Continuous Integration. Sauber. Automatisch. Zuverlässig. *
*Namics.*

A Merkle Company

Namics AG – A Merkle Company

Unterstrasse 12, CH-9000 St. Gallen

Telefon +41 (0)71 228 67 77

Mobile +41 (0)79 628 94 01

ramon.bruelisauer@namics.com


namics.com
<http://www.namics.com/?utm_source=Mailfooter&utm_medium=Mail&utm_term=&utm_content=Website&utm_campaign=Mailfooter>
, blog.namics.com
<http://blog.namics.com/?utm_source=Mailfooter&utm_medium=Mail&utm_term=&utm_content=Blog.Namics&utm_campaign=Mailfooter>
, twitter.com/namics


--


Am Mi., 18. März 2020 um 16:47 Uhr schrieb Ryan Bolger <
notifications@github.com>:

**Comment by rmbolger** [comment]
I'm having trouble reproducing the access denied situation you described in my own environment. I've created multiple resource groups each with its own DNS zone in it. I've created an app registration and associated service principal and only given it the Contributor role on one of the resource groups.

When I try to use `Publish-DnsChallenge` against a zone in the resource group it has permissions for, it works. When I try to do the same thing against a zone in one of the other resource groups, it fails, but not with an access denied error. It fails because it can't find the zone among the ones it was able to query.

Are there any other permissions in place that you know of which would be preventing you from querying the subscription-wide DNS zones endpoint? It seems like this should work (only returning the zones you have access to read) unless there's some other permission stuff going on.
