### ISSUE TITLE
Server Authentication key usage

### ISSUE THREAD

**Issue by osagiz9** [rmbolger/Posh-ACME#235]
hey i'll needed certificate with Server Authentication purposes only.

how it possible ?

**Comment by rmbolger** [comment]
It is unlikely you need a certificate that **only** includes the Server Authentication key usage. You likely need one that has **at least** that usage. Let's Encrypt certificates include Server Authentication, Client Authentication, Digital Signature, and Key Encipherment usages.

If you're looking for a guide on how to get a certificate using this software, I'd start with the [Tutorial](https://github.com/rmbolger/Posh-ACME/blob/master/Tutorial.md). Otherwise, you might be better served over at the [Let's Encrypt Community)[https://community.letsencrypt.org/] forum.
