### ISSUE TITLE
Wildcard order issues

### ISSUE THREAD

**Issue by rmoreRojoli** [rmbolger/Posh-ACME#240]
Hello,

I am trying to use the New-PAOrder functionality for a wildcard domain like so:
`New-PAOrder "*.example.com"`
Then when I am trying to start the listener for the verification process with
`Invoke-HttpChallengeListener -Verbose` it says:
**WARNING: No pending authorizations found for Domain "*.example.com"**

Am I missing something or is this an issue?

**Comment by rmbolger** [comment]
Unfortunately, Let's Encrypt's policy requires using DNS challenges to validate wildcard names in a certificate.
https://letsencrypt.org/docs/faq/#does-let-s-encrypt-issue-wildcard-certificates

The HttpChallengeListener is not working because the order doesn't contain any challenges that have `http-01` as a valid challenge type.

**Comment by rmoreRojoli** [comment]
I see. Thank you!
