### ISSUE TITLE
 UnoEuro changed its name to Simply.com

### ISSUE THREAD

**Issue by emilstahl** [rmbolger/Posh-ACME#246]
Hi

I would like to update [UnoEuro.ps1](https://github.com/rmbolger/Posh-ACME/blob/master/Posh-ACME/DnsPlugins/UnoEuro.ps1) and [UnoEuro-Readme.md](https://github.com/rmbolger/Posh-ACME/blob/master/Posh-ACME/DnsPlugins/UnoEuro-Readme.md) as UnoEuro recently changed its name to Simply.com. New API hostname is api.simply.com.

I don't want to break any existing use of the UnoEuro/Simply.com DNS plugin – what is recommended way? Create new files named Simply.com with updated content and keep the UnoEuro.ps1 file and just update the name and hostname in the existing file? Or can I rename the file without breaking current use of the DNS plugin?

**Comment by rmbolger** [comment]
Is the old API host still active? Or are people using the plugin currently broken because they took it offline?

If the old API host is still active, I would probably leave the existing plugin as-is and just make a new one with the new API hostname and differently named parameters. I can put a warning on the DNS plugins page and the old usage guide that the plugin is deprecated and may stop working once Simply.com turns off the old hostname.

If the old API host is down, I would still create a new plugin as described above. But if the new API host works exactly the same as the only one, I would also update just that value in the old plugin so that people who are broken get fixed (at least for now).

**Comment by emilstahl** [comment]
@rmbolger Sorry I was not clear. The old API endpoint is **still active** and will continue to work.

**Comment by rmbolger** [comment]
Cool. Then yeah. Feel free to submit a new plugin that's basically a clone of the old one with new parameter names. Once it's merged, I'll add the deprecation warnings on the old stuff. Do you know if Simply.com is sending notifications to their users about the change?

**Comment by rmbolger** [comment]
I was just looking at the API docs for simply.com and it appears they're still referencing the `https://api.unoeuro.com` endpoint.

https://www.simply.com/en/docs/api/

**Comment by rmbolger** [comment]
Hey @emilstahl, I took the liberty of copying the UnoEuro plugin into a new Simply plugin. But I don't have an account to test it against and it looks like the cheapest domain registration would cost me about 15 EUR to register including DNS setup. Can you see if it works for you?

**Comment by rmbolger** [comment]
The new Simply plugin is now live in 3.19.0
