### ISSUE TITLE
GoDaddy plugin doesn't work with DNS Only hosting

### ISSUE THREAD

**Issue by jrbarrick** [rmbolger/Posh-ACME#254]
I've got a few domains hosted with GoDaddy that are DNS Only, so actual registration is with another provider.  The Find-GDZone function fails with error "Unable to find matching zone for $RecordName".  I ran through the code manually, and found that the $domain.status for these DNS Only domains is not ACTIVE, but is PENDING_DNS_ACTIVE.

Changed that line in the code to this for testing, and it created the certificate fine:
if ($domain.status -eq 'ACTIVE' -or $domain.status -eq 'PENDING_DNS_ACTIVE') {

The GoDaddy API reference doesn't even list PENDING_DNS_ACTIVE as a valid status, but apparently it's what they return for this type of domain.

**Comment by rmbolger** [comment]
That's weird. I didn't even realize GoDaddy would do DNS hosting without transferring the registration to them. When I tried adding a zone to my own account, the resulting page mentioned that "Zones not associated with a product will be deleted after 30 days." Out of curiosity, do you have another product associated with your zone that has the PENDING_DNS_ACTIVE status?

I'm also curious if the pending part is just temporary. I'm sure their domain transfer process is used to having to wait for DNS propagation. Perhaps there's some background task waiting to validate the TLD nameservers are pointing your domain to their NS records?

Their API docs page does list that status in a huge list of other statuses available for the `GET /v1/domains` endpoint. But it doesn't give any context on what it's supposed to mean.

In any case, the fix is easy as you found. I'll see about adding it soon.

**Comment by jrbarrick** [comment]
I'm not actually sure how long this domain has been with set up with DNS Only at GoDaddy, but it's been at least a couple years, likely longer, so doesn't look like this status is temporary.  We've got 5 other domains set up the same way, and they all show the same status as well.  Could be some weird legacy product they don't offer anymore, not really sure.
