### ISSUE TITLE
OVH: Work with access tokens that have more limited permissions

### ISSUE THREAD

**Issue by grzegor** [rmbolger/Posh-ACME#256]
I'm using OVH as backend. Unfortunately OVH API has no way of limiting adding zone record to just TXT, so basically I have to make token that, when stolen in an unlikely event, can be used to reroute all my domain "A" records to attacker servers, which poses a huge security risk.

I can propose a nice solution, when somoene already created _acme-challenge record and generated access token with minimal permissions like:
`https://eu.api.ovh.com/createToken/index.cgi?GET=/domain/zone/$ZONE/record*&PUT=/domain/zone/$ZONE/record/$RECORD_ID&POST=/domain/zone/$ZONE/refresh`

So the user ends up with only:
- read access to a specified zone record info and its records: /domain/zone/$ZONE/record*
- alter access to a specified record ($RECORD_ID should point to _acme-challange.subdomain record): /domain/zone/$ZONE/record/$RECORD_ID
- refresh specified zone rights: /domain/zone/$ZONE/refresh

(they are sufficient and work just fine with my modified [acme.sh](https://github.com/acmesh-official/acme.sh) code)

In your script, when adding record fails with "access denied" message assume that it may be the case of limited credentials and just additionally:
- search if acme record already exists with GET /domain/zone/$ZONE/record?fieldType=TXT&subDomain="_acme-challenge.+$SUBDOMAIN" and if it's not empty get "target" value of first returned RECORD_ID
- try to alter it with PUT /domain/zone/$ZONE/record/$RECORD_ID" with same parameters as in adding new record

In delete record function, when removal fails (due to lack of DELETE permission) try to alter /domain/zone/$ZONE/record/$RECORD_ID with blank target to sanitze record a little bit (but it's not neccasary as existing token is expired by then so useless to anyone, it's just for aesthetics). Actually you may have to set target as a single space character, bacause I see that some value of "target" is required by API.

Also in line 337 `Invoke-OvhRest GET "$($script:OVHCreds.ApiBase)/domain/zone/$zoneTest` you may want to test against '/domain/zone/$zoneTest/record' path instead, this way we can further limit required GET permissions from /domain/zone/* to just /domain/zone/$ZONE/record* (so the potential attacker won't see the whole list of current domains which in my case are essentionally a list of my clients).

**Comment by rmbolger** [comment]
This is great, @grzegor. Thanks! I didn't realize you could get that granular with the token permissions. I will definitely try to make this go and maybe even augment the usage guide with instructions on how to setup the more limited permissions.

**Comment by grzegor** [comment]
Glad you like it! Their API is superb, just wish they would include filtering by parameters as well.

> maybe even augment the usage guide with instructions on how to setup the more limited permissions.

For sake of anyone rading it, please do! Creating a wildcard OVH token is exceptionally bad idea! I mean $$$ with many zeroes bad idea because of this:
`https://eu.api.ovh.com/console/#/me/order/%7BorderId%7D/payWithRegisteredPaymentMean#POST`
and this
`https://eu.api.ovh.com/console/#/me/order/%7BorderId%7D/pay#POST`

Somone with access to this token can spawn multiple NVIDIA Tesla V100 machines and start digging bitcoins with just one script.

The permissions your code in it's current form require to work should be:
`GET=/domain/zone/*
POST=/domain/zone/$ZONE/record
POST=/domain/zone/$ZONE/refresh
DELETE=/domain/zone/$ZONE/record/*`
I think that's all but havent really tested it

So updating the creation links with:
`?GET=/domain/zone/*&POST=/domain/zone/CHANGE_ME/record&POST=/domain/zone/CHANGE_ME/refresh&DELETE=/domain/zone/CHANGE_ME/record/*`
and instructing users which part to change on OVH form might be a really good idea :)

**Comment by rmbolger** [comment]
Ok, so I have a preliminary version I'm testing that is now working for the case where a user wants to limit the key scope to one or more zones without giving access to all zones on the account. Essentially, the `Invoke-OVHSetup` function now has an optional `-Zone` parameter that takes an array of zone names and builds the access rule list like this:

```
GET    /domain/zone/$z/record
GET    /domain/zone/$z/record/*
POST   /domain/zone/$z/record
DELETE /domain/zone/$z/record/*
POST   /domain/zone/$z/refresh
```

The GET `/record/*` seemed to be needed in addition to `/record` because without it, I couldn't get the target details. The `Find-OVHDomain` function now checks `/domain/zone/$z/record?fieldType=TXT` instead of just `/domain/zone/$z` and allows for 403 errors in addition to 404 errors to indicate the zone either doesn't exist or hasn't been granted access.

I'm going to have to think a bit more on the specific record access and modifying it with PUT. The potential problem is how to deal with the case where multiple TXT records for the same name need to be created like in the case of a cert having both `example.com` and `*.example.com`. I also have to account for other existing TXT records already existing with those names and how to decide which one(s) to modify.

**Comment by grzegor** [comment]
This is great, thank you!
Also instead of
`GET    /domain/zone/$z/record`
`GET    /domain/zone/$z/record/*`
you can just do
`GET    /domain/zone/$z/record*`
which handles both cases

**Comment by grzegor** [comment]
> The potential problem is how to deal with the case where multiple TXT records for the same name need to be created like in the case of a cert having both example.com and *.example.com.

If there are many "_acme-challange.subdomain" records just pick the first one. ACME checks all of them and picks the correct one automtically. Also you're wildcard case is exactly what record's subdomain part is for if I understand your problem correctly. 

For example if you want to issue cert for "xxx.yyy.zzz.com" and the zone in DNS is just "zzz.com" and not "yyy.zzz.com" then 
when you filter GET with "?fieldType=TXT&subDomain=_acme-challange.yyy" you should only get all records for this exact domain.

**Comment by rmbolger** [comment]
Let me see if I can explain in more detail just to clarify my own thinking.

When you ask for a new cert that contains (for example) `example.com` and `*.example.com`, the ACME server is going to need to validate two different TXT record values with the same FQDN. In this case, `_acme-challenge.example.com`. Some providers treat a TXT record with multiple values as a single "record" object that just has an array of values. Others, like OVH in this case, treat it as two completely separate record objects. And for OVH specifically, each record has a different ID as well.

So in the case where a user wants to limit a token's access to edit only the specific TXT records needed for the cert, they'll need to pre-create both of those empty TXT records and then grant access to both of them via the record ID. We need two because Posh-ACME tries to create all the TXT records in an order before asking the ACME server to validate any of them. So we can't write one, validate it, then write the other, and validate it without a huge architectural change to the module. *BTW, is there an easy way to check the record ID of a given record from the web control panel without looking at the HTML source?*

Now, let's say the user has pre-created the two empty records and properly granted access to them for a given set of credentials. When they ask Posh-ACME to get a cert containing the two names, each name will have a random value to use for the TXT record sent by the ACME server. Posh-ACME then calls `Publish-DNSChallenge` serially for each of those values which gets translated into two separate calls to `Add-DnsTxtOVH` that look more or less like this.

```
Add-DnsTxtOVH '_acme-challenge.example.com' 'value1' ...additional api cred params...
Add-DnsTxtOVH '_acme-challenge.example.com' 'value2' ...additional api cred params...
```

For each call, the `Find-OVHDomain` function is able to determine that it's trying to add a TXT record for `_acme-challenge` in the `example.com` domain. No problem so far.

Next, it will check for existing TXT record values using `GET /domain/zone/example.com/record?fieldType=TXT&subDomain=_acme-challenge`. This returns two ID values for our pre-created records that we then get the details for with `GET /domain/zone/example.com/record/ID`. Importantly, we have no guarantee from the API that these IDs are returned in any sort of predictable order. The plugin also currently has no idea whether the credential it's using has create/delete rights to all records in the zone or just modify rights to these particular records.

In the the first call to `Add-DnsTxtOVH`, we'll see the two records are either empty or have other garbage data that doesn't match the TXT value we're trying to write in this call. In the second call, we'll see the same thing except we won't know that the value in one of those records was just written by the previous call. It doesn't even know it's the second call, so we can't just tell it to modify the first record on the first call and the second record on the second call.

So at the very least, we're going to need to add some code to remember what we've already written. This shouldn't be too bad. I can abuse the `Save-DnsTxtOVH` function in the plugin to do housekeeping type stuff because we know it gets called once after all of the Adds are done and again after all of the Removes are done. There are a couple other plugins that do this for similar reasons.

However, we only need to save state when we need to modify existing records as opposed to create/delete. So it probably makes sense to add some sort of check that tests our permissions within the zone so we know which model to use.

I'm gonna stop here because I think I've got the beginnings of a plan to make this work. But hopefully this has clarified some of the complications with doing this.

**Comment by rmbolger** [comment]
Ok! I just committed a version that seems to be working for me and a greatly expanded readme. If you have a sec, take a look at the updated OVH guide and test out the dev version of the plugin. You can install it using the instructions on the main repo readme.

**Comment by rmbolger** [comment]
Hey @grzegor. Did you get a chance to test the changes?

**Comment by grzegor** [comment]
Apologies for delayed response - I was literally in a cabin in woods for past week. Thanks for all the work you did, I'll test it tomorrow or friday on one of my servers and I'll get back to you.

**Comment by grzegor** [comment]
Unfortunately it either doesn't work correctly or I'm doing something wrong.
I made a domain for testing purposes: `acmetest.xyz` 
I want to issue a certificate for: `host.subdomain.acmetest.xyz` which reflects my real use case.
I created a TXT record `_acme-challenge.host.subdomain` inside `acmetest.xyz` zone and querying nameserver gets the current record value correctly:
```
$ dig +short -t txt _acme-challenge.host.subdomain.acmetest.xyz
"jCd8qYXuLjgT19e4SC-iErQvuiS4yxcusJyRYIqIUrs"
```
Value of the record is already populated, because I tested it earlier with my modified `acme.sh` script by executing
`./acme.sh --issue --dns dns_ovh -d host.subdomain.acmetest.xyz --accountemail "acmetest@vewku.com" --staging`
and it issued a correct staging cert, so the credentials and permissions have to be sufficient. They were made with:
`https://eu.api.ovh.com/createToken/index.cgi?GET=/domain/zone/acmetest.xyz/record*&POST=/domain/zone/acmetest.xyz/refresh&PUT=/domain/zone/acmetest.xyz/record/5123530085`

Now I want to issue cert with Posh-ACME on Windows machine installed with:
```
git clone https://github.com/rmbolger/Posh-ACME.git
cd Posh-ACME
Import-Module -Name .\Posh-ACME -Force
```

Now, I'm trying to get cert with:
```
$DebugPreference = 'Continue'
Set-PAServer LE_STAGE
$pArgs = @{
     OVHAppKey = '*****'
     OVHAppSecretInsecure = '*****'
     OVHConsumerKeyInsecure = '*****'
     OVHRegion = 'ovh-eu'
     OVHUseModify = $true
}
New-PACertificate host.subdomain.acmetest.xyz -AcceptTOS -Contact acmetest@vewku.com -DnsPlugin OVH -PluginArgs $pArgs
```

unfortunately it exits with error:
```
DEBUG: DnsPlugin: OVH
DEBUG: DnsAlias:
DEBUG: Loading PAAccount list from disk
DEBUG: Loading saved plugin data
DEBUG: New args for OVH found.
DEBUG: Removing old value for OVHUseModify
DEBUG: Removing old value for OVHAppKey
DEBUG: Removing old value for OVHAppSecretInsecure
DEBUG: Removing old value for OVHConsumerKeyInsecure
DEBUG: Removing old value for OVHRegion
DEBUG: Adding new value for OVHUseModify
DEBUG: Adding new value for OVHAppKey
DEBUG: Adding new value for OVHAppSecretInsecure
DEBUG: Adding new value for OVHConsumerKeyInsecure
DEBUG: Adding new value for OVHRegion
DEBUG: Loading PAAccount list from disk
DEBUG: Loading saved plugin data
DEBUG: Loading PAAccount list from disk
DEBUG: Calling OVH plugin to add _acme-challenge.host.subdomain.acmetest.xyz TXT with value
arGrbwyn39IpKT7KhTyb9W5KbPOQxzhJT_GwI4illmk
DEBUG: Checking host.subdomain.acmetest.xyz
DEBUG: host.subdomain.acmetest.xyz either doesn't exist or our credentials haven't been given read access to it.
DEBUG: Checking subdomain.acmetest.xyz
DEBUG: subdomain.acmetest.xyz either doesn't exist or our credentials haven't been given read access to it.
DEBUG: Checking acmetest.xyz
No existing records were found to modify in acmetest.xyz that haven't already been modified.
At C:\Users\grzegor\Devel\Posh-ACME\Posh-ACME\DnsPlugins\OVH.ps1:64 char:13
+             throw "No existing records were found to modify in $domai ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (No existing rec... been modified.:String) [], RuntimeException
    + FullyQualifiedErrorId : No existing records were found to modify in acmetest.xyz that haven't already been modified.
```

I'm sending you the unmasked version of issued command to your email address, feel free to use my credentials if you like - I made this domain just to test your script.

**Comment by rmbolger** [comment]
From a fresh PowerShell session, I ran the unmasked command you sent verbatim and it worked. But I have a theory on what might have happened in your case. Had you previously run a `Publish-DnsChallenge` command in the same session to test things before you ran the `New-PACertificate` command?

Essentially the plugin keeps a list of previously modified record IDs in an array and adds to it each time `Publish-DnsChallenge` is called. If you're creating a wildcard cert that needs two different values set for the same record name, this prevents it from overwriting the first value with the second value. That "modified" list only gets cleared in the following cases.

- `Save-DnsChallenge` is called against the plugin
- The module is re-imported using `Import-Module Posh-ACME -Force`
- The PowerShell session exits

I just some additional debug statements to the dev branch that should show the list of previously modified record IDs just before it tries to find one to modify. Give it another try with that version and see how it goes. If you get the same error, there would theoretically be debug line just before the error that looks like this:

> DEBUG: Checking for records to modify from the list: 5123530085
> DEBUG: Ignoring previously modified IDs: 5123530085

**Comment by grzegor** [comment]
Ok, this is strange, still failing. To say that I'm not very proficient in dealing with Windows servers or PowerShell tooling is a gross understatment, but I really think this should reset everything to clean slate condition with current dev branch installed locally; after closing all terminal windows and starting a new one:
```
# this should clear Posh-ACME cache
Remove-Item –Path "$env:LOCALAPPDATA\Posh-ACME" –Recurse
# this should remove previous dev installment
Remove-Item –Path $HOME\Documents\WindowsPowerShell\Modules\Posh-ACME
# for some reason I don't have user module dir in path, probably because I'm running as admin and/or it's Windows Server, so:
$Env:PSModulePath=$Env:PSModulePath + ";$HOME\Documents\WindowsPowerShell\Modules"
# getting lastest Posh-ACME
iex (irm https://raw.githubusercontent.com/rmbolger/Posh-ACME/master/instdev.ps1)
Import-Module -Name Posh-ACME -Force
$lastExitCode # returns 0
```

Let's see what we have:
```
> $PSVersionTable.PSVersion
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      17763  1007

> (Get-ItemProperty "HKLM:SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full").Release
461814  # according to MS this means dotnet 4.7.2

> Get-Module -ListAvailable -Name Posh-ACME

    Directory: C:\Users\Administrator\Documents\WindowsPowerShell\Modules

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     3.14.0     Posh-ACME                           {Get-DnsPluginHelp, Get-DnsPlugins, Get-KeyAuthorization, ...

> ls $env:LOCALAPPDATA\Posh-ACME
ls : Cannot find path 'C:\Users\Administrator\AppData\Local\Posh-ACME' because it does not exist.[...]
```
So let's close again all terminal windows just to be sure, and do the magic in a fresh one:
```
$Env:PSModulePath=$Env:PSModulePath + ";$HOME\Documents\WindowsPowerShell\Modules"
Import-Module -Name Posh-ACME -Force
$DebugPreference = 'Continue'
Set-PAServer LE_STAGE
$pArgs = @{
    OVHAppKey = '****'
    OVHAppSecretInsecure = '****'
    OVHConsumerKeyInsecure = '****'
    OVHRegion = 'ovh-eu'
    OVHUseModify = $true
}
New-PACertificate host.subdomain.acmetest.xyz -AcceptTOS -Contact acmetest@vewku.com -DnsPlugin OVH -PluginArgs $pArgs
```
this is the full output with my IP and tokens redacted (wasn't sure which one held the link to the response with my server IP so I got rid of all of them as it's the same IP as my production environment):
```
DEBUG: Updating directory info from https://acme-staging-v02.api.letsencrypt.org/directory
DEBUG: Requesting nonce from https://acme-staging-v02.api.letsencrypt.org/acme/new-nonce
DEBUG: Saving PAServer to disk
DEBUG: Refreshing valid accounts
DEBUG: Loading PAAccount list from disk
DEBUG: Loading PAAccount list from disk
DEBUG: Refreshing valid accounts
DEBUG: Loading PAAccount list from disk
DEBUG: Loading PAAccount list from disk
DEBUG: Creating new ec-256 account with contact: mailto:acmetest@vewku.com
DEBUG: Creating new EC 256 key
DEBUG: Header: {
    "nonce":  "*****",
    "alg":  "ES256",
    "jwk":  {
                "crv":  "P-256",
                "kty":  "EC",
                "x":  "*****",
                "y":  "*****"
            },
    "url":  "https://acme-staging-v02.api.letsencrypt.org/acme/new-acct"
}
DEBUG: Payload: {"contact":["mailto:acmetest@vewku.com"],"termsOfServiceAgreed":true}
DEBUG: Signing message using ES256
DEBUG: Updating nonce: *****
DEBUG: Response: {
  "key": {
    "kty": "EC",
    "crv": "P-256",
    "x": "*****",
    "y": "*****"
  },
  "contact": [
    "mailto:acmetest@vewku.com"
  ],
  "initialIp": "*****",
  "createdAt": "2020-06-20T17:46:42.253816728Z",
  "status": "valid"
}
DEBUG: Creating new 2048 order with domains: host.subdomain.acmetest.xyz
DEBUG: Header: {
    "kid":  "https://acme-staging-v02.api.letsencrypt.org/acme/acct/14266***",
    "alg":  "ES256",
    "nonce":  "*****",
    "url":  "https://acme-staging-v02.api.letsencrypt.org/acme/new-order"
}
DEBUG: Payload: {"identifiers":[{"value":"host.subdomain.acmetest.xyz","type":"dns"}]}
DEBUG: Signing message using ES256
DEBUG: Updating nonce: *****
DEBUG: Response: {
  "status": "pending",
  "expires": "2020-06-27T17:46:42.663096713Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "host.subdomain.acmetest.xyz"
    }
  ],
  "authorizations": [
    "https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/67215***"
  ],
  "finalize": "https://acme-staging-v02.api.letsencrypt.org/acme/finalize/14266***/104055***"
}
DEBUG: Header: {
    "kid":  "https://acme-staging-v02.api.letsencrypt.org/acme/acct/14266***",
    "alg":  "ES256",
    "nonce":  "*****",
    "url":  "https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/67215***"
}
DEBUG: Payload:
DEBUG: Signing message using ES256
DEBUG: Updating nonce: *****
DEBUG: Response: {
    "identifier":  {
                       "type":  "dns",
                       "value":  "host.subdomain.acmetest.xyz"
                   },
    "status":  "pending",
    "expires":  "2020-06-27T17:46:42Z",
    "challenges":  [
                       {
                           "type":  "http-01",
                           "status":  "pending",
                           "url":  "https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/67215***/n_6***",
                           "token":  "*****"
                       },
                       {
                           "type":  "dns-01",
                           "status":  "pending",
                           "url":  "https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/67215***/axz***",
                           "token":  "*****"
                       },
                       {
                           "type":  "tls-alpn-01",
                           "status":  "pending",
                           "url":  "https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/67215***/76I***",
                           "token":  "*****"
                       }
                   ]
}
DEBUG: Adding location https://acme-staging-v02.api.letsencrypt.org/acme/order/14266***/104055***
DEBUG: Saving validation params to order
DEBUG: Header: {
    "kid":  "https://acme-staging-v02.api.letsencrypt.org/acme/acct/14266***",
    "alg":  "ES256",
    "nonce":  "*****",
    "url":  "https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/67215***"
}
DEBUG: Payload:
DEBUG: Signing message using ES256
DEBUG: Updating nonce: *****
DEBUG: Response: {
    "identifier":  {
                       "type":  "dns",
                       "value":  "host.subdomain.acmetest.xyz"
                   },
    "status":  "pending",
    "expires":  "2020-06-27T17:46:42Z",
    "challenges":  [
                       {
                           "type":  "http-01",
                           "status":  "pending",
                           "url":  "https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/67215***/n_6***",
                           "token":  "*****"
                       },
                       {
                           "type":  "dns-01",
                           "status":  "pending",
                           "url":  "https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/67215***/axz***",
                           "token":  "*****"
                       },
                       {
                           "type":  "tls-alpn-01",
                           "status":  "pending",
                           "url":  "https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/67215***/76I***",
                           "token":  "*****"
                       }
                   ]
}
DEBUG: DnsPlugin: OVH
DEBUG: DnsAlias:
DEBUG: Loading PAAccount list from disk
DEBUG: New args for OVH found.
DEBUG: Adding new value for OVHUseModify
DEBUG: Adding new value for OVHAppKey
DEBUG: Adding new value for OVHAppSecretInsecure
DEBUG: Adding new value for OVHConsumerKeyInsecure
DEBUG: Adding new value for OVHRegion
DEBUG: Loading PAAccount list from disk
DEBUG: Loading saved plugin data
DEBUG: Loading PAAccount list from disk
DEBUG: Calling OVH plugin to add _acme-challenge.host.subdomain.acmetest.xyz TXT with value
*****
DEBUG: Checking host.subdomain.acmetest.xyz
DEBUG: host.subdomain.acmetest.xyz either doesn't exist or our credentials haven't been given read access to it.
DEBUG: Checking subdomain.acmetest.xyz
DEBUG: subdomain.acmetest.xyz either doesn't exist or our credentials haven't been given read access to it.
DEBUG: Checking acmetest.xyz
DEBUG: Checking for records to modify from the list: 5123530085
No existing records were found to modify in acmetest.xyz that haven't already been modified.
At C:\Users\Administrator\Documents\WindowsPowerShell\Modules\Posh-ACME\DnsPlugins\OVH.ps1:72 char:13
+             throw "No existing records were found to modify in $domai ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (No existing rec... been modified.:String) [], RuntimeException
    + FullyQualifiedErrorId : No existing records were found to modify in acmetest.xyz that haven't already been modif
   ied.
```

There is the new debug line: `DEBUG: Checking for records to modify from the list: 5123530085` but instead of `DEBUG: Ignoring previously modified IDs: 5123530085` I get the above error.

**Comment by grzegor** [comment]
Ok, problem solved with
`winget install -e --name PowerShell --version 7.0.2`
and doing everything under `pwsh` shell
I thought that devel version had the same requirements as stable branch (PS >= 5.1).

**Comment by rmbolger** [comment]
Ok, that is super weird. The "Checking for records to modify..." clearly shows that it found the correct record to modify. The lack of "Ignoring..." message means there were no records in the "modified" list to ignore. So it should have used the one that was left.

Looking over the code, it's possible there's some weird edge case thing between PowerShell/.NET versions that changes how arrays are handled. PowerShell tries to help in some cases by "unrolling" arrays that only have one element which could possibly confuse the line that checks what the array count is. I was also testing this on PowerShell 7 this morning rather than the older 5.1. Gimme a sec to add a couple more things that might workaround the inconsistencies.

**Comment by rmbolger** [comment]
Ok, latest commit fixes things for me when running under 5.1 and still works in 7.0.2. Try now.

**Comment by grzegor** [comment]
Now it works great under 5.1 (Win Server 2019) and 7.0.2 (Win 10 Pro v2004). Thank you! 

> none of those ACME token values or IDs in the URLs are particularly sensitive

So I thought, but wasn't sure if any of the intermediate URL responses held my IP in their body. My devLAN shares the same public IP with my company gateway which I'm really oversensitive about as the current work-from-home model is not ideally secure yet with RDP gateway exposed (which had a 0-day in january for example) and only geo-limited to my country. I'm testiting different zero knowledge network proxies right now to fix this, but some of them require a valid host certificate with trusted root CA. I didn't want to expose 80 port on my firewall so here we are, dealing with Posh-ACME DNS plugin to do just that 😃 (for which I owe you at least a decent meal, will fix that in a moment when I'll crack how github donations work).

Offtopic, do you have any information why current Windows ships with so ancient version of PS? Do they intend to stay with built in 5.1 forever for basic admin tasks and current branch for anything else?

**Comment by rmbolger** [comment]
Hooray! Totally my bad for not testing under both. I usually do on new stuff but I must have been rushing for this. And huge thanks for the sponsorship!

The history on PS versions and what gets included in Windows is rather complicated and largely revolves around the split from the Windows-only ".NET Framework" to the cross platform ".NET Core". There are a bunch of libraries from Framework that didn't and likely never will get ported to Core due to their dependence on lower level Windows platform libraries that have no equivalent on other OSes. Consequently, there are a number of PowerShell modules also dependent on those old Framework things that are likely to remain Windows-only for the forseeable future. So MS basically can't get rid of 5.1 until everything built-in that depends on it is capable of running under 7+ natively. All the .NET Core and PS 6+ stuff is also being developed entirely open source and they didn't want to tie the release schedule to the release cadence of Windows versions. So for the time being, it will likely remain a post-install addition. Though it may get easier to install with things like winget or Features on Demand in the future.

**Comment by grzegor** [comment]
Maybe when NET Framework and NET Core gets melted to NET 5 this november the PS department would also gain a little more cosistency. 

Winget is great, unless you try to install it on Windows Server on which there is no Windows Store, so its dependency of 'snowflake' store-only VC runtime will never be satisfied 🙄

Anyway, just tested Posh-ACME with my real domain and LE_PROD. Works as intended! I never closed anything on guthub so allow me :)
