### ISSUE TITLE
Order status invalid with JWS invalid anti-replay nonce when a new certificate is asked

### ISSUE THREAD

**Issue by Teazane** [rmbolger/Posh-ACME#264]
Hello !
I'm using Posh-ACME for several months, and an error is often happening. It was quite rare at the beginning, but now, it happens for every script run. The challenge step fails because of the anti-replay nonce which is "invalid". Here is the raised exception :
```
2020-07-15 09:57:24 L309        Order status is not ready but invalid.
Exception: {
  "type": "urn:ietf:params:acme:error:badNonce",
  "detail": "JWS has an invalid anti-replay nonce: \"0101kuCHLJ8E-RCPeWYHnyCINipBvW93Li_uY3gfSyp9-fc\"",
  "status": 400
} 
```

I don't understand what's going on, I run the script again and again, the error is still here. By the way I don't know the duration of the anti-replay nonce, could it be a point ? 

Here is my code, so you can understand how I use your tool : 
```PowerShell
# Complete procedure to get new certificates
# Doc: https://github.com/rmbolger/Posh-ACME/wiki/%28Advanced%29-Semi-Manual-DNS-Challenge-Validation
Function GetNewCertificate {
	LogInfo $(GetLine) Infos  "New certificate order creation"
	New-PAOrder $CertificateDomains -PfxPass $PFXKeyString
	
	LogInfo $(GetLine) Infos  "DNS records content forged from order values"
	# Get the actual statuses of the actual demand for each SAN
	$auths = Get-PAOrder | Get-PAAuthorizations
	# Construction of DNS challenge txt record
	$toPublish = $auths | Select @{L='TXTName'; E={"_acme-challenge.$($_.fqdn.Replace('*.',''))"}}, @{L='TXTValue';E={Get-KeyAuthorization $_.DNS01Token -ForDNS}}
	# Publish those records on DNS
	LogInfo $(GetLine) Infos  "DNS records updated for ACME challenge"
	foreach($record in $toPublish){
		LogInfo $(GetLine) Infos  "$SAN record is being set..."
		$recordName = $record.TXTName
		$recordValue = $record.TXTValue
		$Content = "server $DNSServerFQDN`r`nzone $DomainFQDN`r`nupdate delete $recordName.`r`nupdate add $recordName. 60 IN TXT `"$recordValue`"`r`nsend`r`nquit"
		LogInfo $(GetLine) Infos  "Configuration sent to the DNS server:`r`n $Content"
		[System.IO.File]::WriteAllLines($DNSFile, $Content)
		& $NsupdatePath -v -k $DNSKeyPath $DNSFile
		Start-Sleep -s 2
	}
	# Wait 5 minutes for the DNS records to be created
	LogInfo $(GetLine) Infos  "Waiting 5 minutes for the records creation..."
	Start-Sleep 300

	# LE check the DNS values
	$auths.DNS01Url | Send-ChallengeAck
	# Check certificate order status (should be "ready")
	$order = Get-PAOrder -Refresh
	if ($order.status -ne "ready"){
		$orderstatus = $order.status
		LogInfo $(GetLine) Error "Order status is not ready but $orderstatus"   # THE ERROR IS RAISED HERE
	}
	# Check challenge status for each domain (should be "valid")
	$orderAuth = Get-PAOrder | Get-PAAuthorizations

	$DNSChallengeStatusOK = $true
	foreach($auth in $orderAuth.DNS01Status){
		if ($auth -ne "valid"){
			$DNSChallengeStatusOK = $false
			LogInfo $(GetLine) Error "Not all DNS challenge status are valid!"
			break
		}
	}

	if ($order.status -eq "ready" -And $DNSChallengeStatusOK){
		# Finish the procedure
		New-PACertificate $CertificateDomains 
		return "OK"
	} else {
		LogInfo $(GetLine) Error  "New certificate creation failed."
		return "No new certificate has been obtained."
	}
}
```

What am I doing wrong ?
Thank you in advance !

**Comment by rmbolger** [comment]
Hey @Teazane. Sorry to hear you're having issues.

The "badNonce" error is not likely what is causing your problem. I'm guessing it just happens to be the last error on the stack prior to your code bailing when it doesn't find the order status it is expecting. The nonce values that the client gets are relatively short lived and the module knows how to retry the requests with a fresh value when it gets that error. They're a relatively normal part of the ACME conversation.

Let's focus on the problem though. After you do the Send-ChallengeAck, you're expecting a "ready" status but instead getting an "invalid" status. Orders that have become invalid due to challenges failing will have the error message/reason queryable in the authorization object. I'm not exactly sure how your log function works, but you'll want to grab the error objects from the authorizations like this.

```powershell
$authErrors = (Get-PAOrder | Get-PAAuthorization).challenges.error
```

It will include one or more objects that each have a `type`, `detail`, and `status` value. My guess is that you'll see errors about the ACME server not finding the TXT record or finding the wrong value in the record. Let's Encrypt is now doing [multi-perspective validation](https://letsencrypt.org/2020/02/19/multi-perspective-validation.html) meaning they now query your records from multiple different clients across the globe. I'm not sure the exact rules, but most or all of these clients need to successfully validate the challenge from their location. But since the DNS changes you made now need to replicate world-wide, your 5 minute wait time may no longer be long enough and some of the more remote clients won't have been updated yet. Assuming that's the case, the nice thing is that the fix is just to wait longer.

Also, if I'm reading your code correctly, it looks like you're using a local copy of nsupdate to effectively do an RFC2136 DDNS update. If you weren't aware, there's actually an RFC2136 plugin now included with Posh-ACME. It will use the copy if nsupdate on your machine and you just have to provide the path in the plugin args or add it to the PATH environment variable. There's more info in the [RFC2136 guide](https://github.com/rmbolger/Posh-ACME/blob/master/Posh-ACME/DnsPlugins/RFC2136-Readme.md), but using the plugin could significantly simplify your script.

**Comment by Teazane** [comment]
Hey @rmbolger !

It seems you're right ! Since I now wait for 15 minutes, it works perfectly. Thank you for the tips concerning RFC2136 plugin. I will take a look at this.

**Comment by rmbolger** [comment]
Excellent! Glad to hear everything is working again.
