### ISSUE TITLE
Omit pfxpass from order.json

### ISSUE THREAD

**Issue by Thacai** [rmbolger/Posh-ACME#265]
Hi.

I'm wondering if there is a way to omit the pfxpass from the order.json file?

Reason being that i'm running this in azure pipelines, and is generating, inserting, and reading the password from azure keyvault, so would prefer if the password didnt exist in 2 places, and i instead simply just had to provide the password as a function parameter, where needed.

**Comment by rmbolger** [comment]
Hi @Thacai. I don't think it will be possible to remove it from the file using built-in module functionality. There are too many pieces particularly around renewal that expect it will be there. However, for your specific use-case depending on how you're doing renewals, there are a couple things you might be able to do.

The `order.json` mostly needs to exist to support the `Submit-Renewal` function. So if you're not actually using `Submit-Renewal`, you can delete `order.json` after you get the finalized cert. The whole order could even be deleted if you've already copied/imported the cert files wherever else they need to go.

If you are using `Submit-Renewal`, the alternative is to just wipe/change the value from `order.json` after the module is done running. But you'll have to put it back prior to running the renewal function, otherwise it will either break or just write your new PFX with the wrong password.
