### ISSUE TITLE
Multiple DNS Plugins for the same name

### ISSUE THREAD

**Issue by strifejester** [rmbolger/Posh-ACME#269]
Is there an option for running multiple DNS providers? The cloudflare outage of course created some hysteria and the powers that be are asking me to maintain our zones on both cloudflare and rackspace. I have created other scripts for adding records that do both providers but was wondering if there is an ability to use 2 providers. If it is not possible I was going to just create a new plugin and pretty much just copy and paste the elements of cloudflare and rackspace into a single custom plugin but thought I would check first before possibly doing a lot of extra work.

**Comment by rmbolger** [comment]
Hey @strifejester. Unfortunately, there's no built-in way to use two different plugins for the same name in a given cert. You *can* use different plugins for different names, but I know that's not exactly what you're looking for. It's also such a rare (at present) config, that it's probably not worth the time and complexity adding support for it.

However, you could fairly easily script up your own solution using the other available public functions like `Publish-DnsChallenge` and `Unpublish-DnsChallenge`. Take a look at the wiki page [(Advanced) Semi Manual DNS Challenge Validation](https://github.com/rmbolger/Posh-ACME/wiki/%28Advanced%29-Semi-Manual-DNS-Challenge-Validation#publishing-a-dns-challenge). When you get to the DNS publishing step, you'd just need to call `Publish-DnsChallenge` for each name in the cert twice...once for each provider with the appropriate plugin arguments. The rest is the same. Renewals would also then have to change from using `Submit-Renewal` to basically a copy of the original script (since a renewal is really just a new order with the same parameters under the hood).

Another option could be to delegate only the TXT records needed for cert validation to another domain that is *not* hosted on multiple providers and use the built-in [challenge alias](https://github.com/rmbolger/Posh-ACME/blob/master/Tutorial.md#advanced-dns-challenge-aliases) support with whatever plugin is necessary for that single provider.
