### ISSUE TITLE
Submit-Renewal : "-NoSkipManualDns" ignored when using the "-AllOrders" switch

### ISSUE THREAD

**Issue by alexpilon666** [rmbolger/Posh-ACME#275]
Hey there,

While building a script on my end, I used thee Manual HTTP challenge validation to setup a new order and whatnot, according to your documentation. Everything went great, until came time to test the renewal.

1. I used `Submit-Renewal`, and it said my order wasn't ready for renewal, to add `-Force`, which I did.
2. It then told me my order was using Manual DNS plugin, to use `-NoSkipManualDns`, so I did, and it worked.
3. I then added the `-AllOrders` to make sure it used all the orders that were there, as I expect many to be added in the future: I got again the message that my order was using Manual DNS plugin, to use `-NoSkipManualDns` to avoid this, even though the switch was already present.

My final command: `Submit-Renewal -Force -AllOrders -NoSkipManualDns`. I tried different switch orders to make sure, even though it shouldn't change anything, and they all came back as if the `-NoSkipManualDns` switch wasn't present.

Is there something I'm missing here ?

Quick note if it changes anything: Using the `LE_STAGE` server since I'm building the script, though this seems to be an issue unrelated to the Let's Encrypt servers at all. 

Thanks in advance!

**Comment by rmbolger** [comment]
Thanks for the detailed report. This is indeed a bug, but the good news is that it has already been fixed in the dev/master branch as part of PR #266 which fixes a similar problem with the `-PluginArgs`.

If you want, you can install the dev copy using the instructions from the readme and verify it fixes the problem. I'm hoping to publish a new release with the fix included soon though.

**Comment by rmbolger** [comment]
Actually, nevermind. I just pushed a 3.16.0 release. So you should be able to just update from the gallery and get the fix.
