### ISSUE TITLE
SSL Certificate does not rebind after renewing

### ISSUE THREAD

**Issue by chrisevans9629** [rmbolger/Posh-ACME#281]
I am using this script to update my SSL certificate in IIS

```powershell
$thumbprint = (Get-PACertificate).Thumbprint
$cert = Submit-Renewal -WarningAction Stop -ErrorAction Stop -Force
         
WriteLog "New certificate installed with thumbprint $($cert.Thumbprint)"
WriteLog "Removing old certificate with thumbprint $thumbprint"
 
Get-ChildItem Cert:\LocalMachine\My |
            Where-Object Thumbprint -eq $thumbprint |
            Remove-Item -ErrorAction Continue
```

but after it runs, it deselects the certificate from my multiple websites:

![image](https://user-images.githubusercontent.com/33850520/93764159-422d6380-fbd8-11ea-9eaa-6a9c07a827f4.png)

And I have automatic rebind turned on for this certificate:
![image](https://user-images.githubusercontent.com/33850520/93764270-6c7f2100-fbd8-11ea-9ac4-6009f963798f.png)

What do I need to do so that this automatically rebinds?  My websites randomly stop working because of this issue.

**Comment by rmbolger** [comment]
Hey @chrisevans9629. Thanks for the report.

I've never actually used the automatic rebinding feature in IIS. But I'd guess the problem revolves around the fact that from a Windows perspective, the certificate is being replaced rather than renewed because that's how the ACME protocol works. A "renewal" is just requesting a new certificate with the same parameters as before. My guess is the automatic rebinding only works with certs that you could use the renew action with directly from the Certificates snap-in which sort of implies a Windows based certificate authority. This is all just an educated guess though.

As an alternative, have you could considered using [Posh-ACME.Deploy](https://github.com/rmbolger/Posh-ACME.Deploy) with its `Set-IISCertificate` function?

**Comment by rmbolger** [comment]
I just did a bit of research on the auto rebinding feature and it looks like when you enable the feature, all it does is create a scheduled task that is triggered on a specific event ID in the CertificateServicesClient event log. The problem is that importing a new certificate into the cert store (which is ultimately all Posh-ACME is doing with the -Install switch) doesn't create the event ID 1001 that the task is looking for. So it never gets triggered. *Interestingly, it doesn't create any events in that log at all at least on the Server 2016 box I'm using to test with.*

However, if you look at the action being run by the scheduled task, it's just running the following command:

```
%SystemRoot%\System32\inetsrv\appcmd.exe renew binding /oldcert:$(OldCertHash) /newcert:$(NewCertHash)
```

I'd guess that you could augment your existing renewal script to end with an equivalent of this command and you'd effectively accomplish the same goal.

**Comment by chrisevans9629** [comment]
@rmbolger thanks for the info!  Let me give adding that to the script a try real quick.

**Comment by chrisevans9629** [comment]
I am getting the error
`Error creating new order :: too many certificates already issued for exact set of domains: *.peerlessproducts.com: see https://letsencrypt.org/docs/rate-limits/`

So I am guessing I'll have to try this tomorrow and let you know then

**Comment by rmbolger** [comment]
There are a couple ways to work around that error if you still want to do more testing today. The best would be to temporarily switch to the staging server assuming your site isn't "live" and having fake certificates won't hurt you. Just run `Set-PAServer LE_STAGE` and keep going. The rate limits in staging are far higher than production.

The other option is to add another name to your cert because the rate limit is only for the exact set of domains in the previous cert. It looks like you're doing a wildcard cert but without also including the non-wildcard root name if I'm reading your error correctly. Most people getting wildcard certs add both `*.example.com` and `example.com` because the wildcard name doesn't actually match the root domain name.

**Comment by chrisevans9629** [comment]
I was able to switch to LE_STAGE and verify that it worked.  Thanks for your help!

**Comment by rmbolger** [comment]
Awesome! Congrats.
