### ISSUE TITLE
Support for DuckDNS

### ISSUE THREAD

**Issue by BVGorp** [rmbolger/Posh-ACME#285]
Hi,

Is it possible to add support for DuckDNS?
acme.sh is already supporting this would be nice to have this on Windows too.
https://github.com/acmesh-official/acme.sh/blob/master/dnsapi/dns_duckdns.sh

Regards,
BVGorp

**Comment by rmbolger** [comment]
Hi @BVGorp. Thanks for the request. I had actually previously looked at implementing DuckDNS before, but they have this weird limitation in their API that you can only set a single TXT record for all names in your zone. That basically means you can only get a cert for a single name at a time using Posh-ACME normally because it tries to create all TXT records required before telling the ACME server to check them.

It's possible to work around that problem with a custom script. But I'm not really planning on adding that sort of functionality to the base module. Is that ok?

**Comment by rmbolger** [comment]
I went ahead and built a draft version of the plugin. See if that works for you.

**Comment by BVGorp** [comment]
Ah i didnt think of that.
In my case i use duckdns as my challenge alias to request a wildcard certificate for my own domain. 
My domain is hosted on a DNS service that has no API to change records. 
So i'm only requesting one hostname (*.example.net) which should be no issue.

I'll try it asap

**Comment by rmbolger** [comment]
This is live now in 3.18.0
