### ISSUE TITLE
Switching ACME DNS plugin to DigitalOcean plugin

### ISSUE THREAD

**Issue by mkanet** [rmbolger/Posh-ACME#295]
A day or so ago, I created a production Certificate for my domain via the ACME DNS plugin; which I manually added a CNAME record for the respective challenge.  However, since my DNS provider is DigitalOcean, I could have just used the DigitalOcean plugin instead.  

I'm curious, is there any benefit at all for me to recreate a new production wildcard certificate using the DigitalOcean plugin this time?  Do both the ACME plugin and DigitalOcean plugin ultimately end up using the same `_acme-challenge.mywebisite.com` CNAME?  I wouldn't mind making another certificate via the DigitalOcean plugin since it's very easy to do; and, I wouldn't hit the rate limit creating a second production certificate.

**Comment by rmbolger** [comment]
Technically, acme-dns and the CNAME is no longer necessary since the Digital Ocean plugin can manipulate the DNS zones directly. If you switch plugins, you'll actually want to delete any challenge CNAME records that exist so they don't interfere with the new challenge TXT records that will get created in Digital Ocean.

The only reason you may want to stick with acme-dns is if you don't want to save your Digital Ocean API token on whatever server is running Posh-ACME since the token can do more than just modify DNS TXT records on your account.

The only benefit I can think of for creating a new certificate now versus when the current one expires is that everything is still fresh in your head. So if you get things squared away now how you want them to be going forward, you'll have less to figure out/remember when it's time to renew.

**Comment by mkanet** [comment]
Thank you for explaining.  I just created a new production certificate using the DigitalOcean plugin; and also had a chance to use part of my `SSL-Certificate-Update.ps1` script to install the new certificate on my webserver.
