### ISSUE TITLE
NameCheap DNS plugin Rate Limiting

### ISSUE THREAD

**Issue by john159753** [rmbolger/Posh-ACME#296]
I am getting rate limited when trying to use the name cheap DNS plugin.

I'm more than willing to help with a PR for the plugin, but i dont know where the backing off should happen. According to their API they dont allow more than 20 requests a min, dont know if thats a rolling limit or anything (they dont provide much detail)
https://www.namecheap.com/support/knowledgebase/article.aspx/9739/63/api--faq#z

Should this limiting function exist only in the plugin ps1 file? Im just cracking open the code, and i dont know exactly where i should start to think about adding in delays/etc

**Comment by rmbolger** [comment]
Hey @john159753. Thanks for the report. I'd definitely handle this within the plugin since it's provider specific. It looks like all of the NameCheap calls are already being wrapped by an internal `Invoke-NCAPI` function. So that's where I'd probably start. The code appears to already even have some retry logic for another sporadic error I was getting. Depending on what the rate limited response looks like, you can probably extend what's there.
