### ISSUE TITLE
Bad Request error when using Cloudflare plugin

### ISSUE THREAD

**Issue by blarg3891** [rmbolger/Posh-ACME#297]
I'm getting the same errors whether i try a new one or try to renew the cert.  When i first created it months ago, all was working fine.

PS C:\scripts> New-PACertificate yy.yy.com -AcceptTOS -Contact xx@xx.net -DNSPlugin Cloudflare -PluginArgs $pArgs -DnsAlias _acme-challenge.xx.xx.net -verbose
VERBOSE: Using directory https://acme-v02.api.letsencrypt.org/directory
VERBOSE: POST https://acme-v02.api.letsencrypt.org/acme/acct/97637496 with -1-byte payload
VERBOSE: received 309-byte response of content type application/json
VERBOSE: Using account 97637496
VERBOSE: POST https://acme-v02.api.letsencrypt.org/acme/order/97637496/6481546568 with -1-byte payload
VERBOSE: received 345-byte response of content type application/json
VERBOSE: Using existing order for lot.urcioloproperties.com with status pending
VERBOSE: POST https://acme-v02.api.letsencrypt.org/acme/authz-v3/8962869309 with -1-byte payload
VERBOSE: received 803-byte response of content type application/json
VERBOSE: Publishing DNS challenge for lot.urcioloproperties.com
VERBOSE: Attempting to find hosted zone for _acme-challenge.lot.beeron.net
VERBOSE: GET https://api.cloudflare.com/client/v4/zones/?name=lot.beeron.net with 0-byte payload
Invoke-RestMethod : The remote server returned an error: (400) Bad Request.
At C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\3.16.0\DnsPlugins\Cloudflare.ps1:291 char:25
+ ... $response = Invoke-RestMethod "$apiRoot/?name=$zoneTest" -Headers $Au ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by rmbolger** [comment]
Hey @blarg3891. Sorry to hear you're having trouble. That error is being returned by the Cloudflare API. It looks like there hasn't been any changes to the Cloudflare plugin since back in September. I did a quick test on my end and it's still working for me on the current Posh-ACME 3.20.0.

Which type of plugin args are you using with Cloudflare? Global Email+Key? CFToken? CFToken + CFTokenReadAll? Has anything changed with your cloudflare account and the keys? I ask because I can get the plugin to produce that same Bad Request error if I purposefully change the CFToken key to something I know is invalid.

So I'm wondering whether your keys have either been changed/revoked/etc or perhaps it's just the saved copy of the keys got changed or wiped or something.

There's a way you can check what is saved for the plugin args, but it's sort of tedious because you have to find the right XML file in your config. Assuming you're using the default config location on Windows, it should be in `C:\Users\USERNAME\AppData\Local\Posh-ACME\acme-v02.api.letsencrypt.org\ACCOUNT_ID\plugindata.xml` where USERNAME is your Windows username and ACCOUNT_ID is the ACME account ID associated with the order. If you don't know the account id, just run `Get-PAAccount` and it should tell you.

Once you have the path to the file, run `Import-CliXml C:\Users\USERNAME\AppData\Local\Posh-ACME\acme-v02.api.letsencrypt.org\ACCOUNT_ID\plugindata.xml` and it'll show you what is saved.

**Comment by blarg3891** [comment]
Really appreciate the response.  While I took notes previously, I must have changed to the global API option but the token was no longer matching the global api key.  I modified the xml and it started working!

Need to update my notes now :)

**Comment by rmbolger** [comment]
Hooray! Glad to hear it was a simple fix.
