### ISSUE TITLE
4.0.0 prevents reading plaintext PfxPass from raw order JSON

### ISSUE THREAD

**Issue by TimZander** [rmbolger/Posh-ACME#302]
I recently noticed that my automated cert renewals were not working and traced it to the 4.0.0 update. Since I did not find this fix in the release notes I figured I would add it here. 

If needing the PfxPass in plaintext form(as was previously stored in order.json) the following powershell code will provide it.

```
$orderData = Get-Content -Path $orderDataPath -Raw | ConvertFrom-Json
$pfxPassB64U = $orderData.PfxPassB64U + "="
$pfxPass = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($pfxPassB64U))
```

**Comment by rmbolger** [comment]
Hi @TimZander. Out of curiosity why do you need to read the PfxPass directly from the JSON? It's available as a normal string in the properties of an order in both 3.x and 4.x. So you can just do:

```powershell
(Get-PAOrder example.com).PfxPass
```

But yes, the PfxPass value is now stored as [base64URL](https://tools.ietf.org/html/rfc4648#section-5) on disk. I chose it over standard base64 because the ACME protocol uses it for a lot of stuff and I already had internal functions to encode and decode it. The code you posted won't actually work as a generic base64url decoder though. The "=" padding you need to add back is variable and there are some characters you need to replace in case they exist in the encoded value.

If you want to just use the internal function, you dot source it like this:

```powershell
. (Join-Path (Get-Module Posh-ACME).ModuleBase "Private\ConvertFrom-Base64Url.ps1")
ConvertFrom-Base64Url 'Zm9vYmFy'
# returns 'foobar'
```

If you still want to use your own decoding code, have a look at the function's source, particularly these lines.

https://github.com/rmbolger/Posh-ACME/blob/afaef019b7776e977725aef2bc58b22a00939656/Posh-ACME/Private/ConvertFrom-Base64Url.ps1#L21-L30

**Comment by TimZander** [comment]
Thanks for the response @rmbolger 

I am using the pfxpass to install the cert into an azure key vault. I'll look into using the code you provided to get the pfxpass directly and hopefully that will work. 

Thanks

**Comment by MaxiPalle** [comment]
> I am using the pfxpass to install the cert into an azure key vault. I'll look into using the code you provided to get the pfxpass directly and hopefully that will work.

Hi @TimZander,
we're using it the same way but haven't figured out, what the best approach would be.
Have you already solved this?
Help appreciated!

**Comment by zerocaps** [comment]
@MaxiPalle try this:
```
$pfxPassSecure = ConvertTo-SecureString -String (Get-PAOrder example.com).PfxPass -AsPlainText -Force
```
and use `$pfxPassSecure` as the password when calling `Import-AzKeyVaultCertificate`

**Comment by MaxiPalle** [comment]
Hi @zerocaps ,
thanks a lot, this did the trick and we were able to solve this issue.

**Comment by rmbolger** [comment]
It should be noted that if you already have the certificate for a given order, the pfx password is also available as a SecureString on the certificate object you get back from `Get-PACertificate` (and `New-PACertificate` during the original request).

```powershell
$pfxPassSecure = (Get-PACertificate).PfxPass
```
