### ISSUE TITLE
DPAPI Error running on Azure Function

### ISSUE THREAD

**Issue by andy968** [rmbolger/Posh-ACME#312]
I am trying to test out generating a certificate using an Azure Powershell Function running Powershell 7. When trying to generate the certificate I am getting the following. It looks like something to do with the securestring for the Cloudflare API token. Any help would be appreciated

`Import-Module Posh-ACME

$Token = "xxxxxxxxxxxxxxxxxxxxxxxxx" | ConvertTo-SecureString -AsPlainText -Force
$pArgs = @{ CFToken = $Token }

New-PACertificate *.domain.co.uk -AcceptTOS -DnsPlugin Cloudflare -PluginArgs $pArgs -Contact hello@domain.com -PfxPass "test"`

`ERROR: Cryptography_DpApi_ProfileMayNotBeLoaded Exception : Type : System.Security.Cryptography.CryptographicException TargetSite : Name : Protect DeclaringType : Microsoft.PowerShell.ProtectedData, System.Management.Automation, Version=7.0.3.0`

**Comment by rmbolger** [comment]
Hey @andy968, that error implies that the Windows DPAPI encryption library can't be loaded from the environment the Azure function is running in. But I have no clue why that might be the case and it's the first time I've seen that error specifically. On non-Windows platforms that don't have DPAPI, PowerShell silently falls back to a cross-platform obfuscation method. So I'm not sure what's going on. However, you might be able to workaround the issue by avoiding the need to use DPAPI.

One option is to switch to using `CFTokenInsecure` which is a standard string rather than a SecureString. All this does is change how the module saves the plugin parameter on disk (clear text vs encrypted). But for an Azure function, would that even matter? There's no change in how the plugin uses the token with Cloudflare.

Another option is new to 4.x and lets you keep using the SecureString version of the token. Before your call to `New-PACertificate`, run this:

```powershell
Set-PAAccount -UseAltPluginEncryption
```

This tells the module to use a generated AES key to encrypt the secure plugin data rather than the system (DPAPI) provided key.

**Comment by andy968** [comment]
That's great, the `Set-PAAccount -UseAltPluginEncryption` did seem to work and allowed the function to run and generate the certificate.

Another question - is it possible to change the path that the orders get downloaded to?

**Comment by rmbolger** [comment]
Awesome! I tried to find an explanation for the DPAPI error, but my google-fu was failing me. Good to know the workaround is sufficient.

You can't change just the order path, but you can change the root config path by setting a `POSHACME_HOME` environment variable prior to importing the module into your PowerShell session (or force a re-import using `Import-Module Posh-ACME -Force`).
