### ISSUE TITLE
renew is now prompting for GDKey & GDSecret

### ISSUE THREAD

**Issue by mcnahum** [rmbolger/Posh-ACME#313]
Hello,
I guess it's a usage question ... 
for months, when I need to renew a certificate I was just doing: Submit-Renewal
and all was automatic but now it's asking for the GDKey & GDSecret
I checked that they are defined by "$pArgs = @{GDKey='xxxxxxxxxxxxxxxx';GDSecret='xxxxxxxxxxxxxxxx'}"
but the usage seams to not be automatic ... 

did I missed a step? 
I did an update to 4.10 recently ..

**Comment by rmbolger** [comment]
Hi @mcnahum, let's see if we can figure out what happened. It looks like haven't been any changes to the GoDaddy plugin specifically since last September. This sounds more like an issue where the saved plugin data got screwed up somehow. Do you recall what version you were on prior to upgrading to 4.1.0?

Normally you can check the plugin args associated with an order using `Get-PAPluginArgs`. For GoDaddy, the output should look like this (order doesn't matter):

```
Name                           Value
----                           -----
GDSecret                       xxxxxxxxxxxxxx
GDKey                          yyyyyyyyyyyyyyyyy
```

If the key/secret is wrong or missing for some reason, you can re-add them to the order like this using your existing `$pArgs` variable.

```powershell
Set-PAOrder -Plugin GoDaddy -PluginArgs $pArgs
```

When you run `Get-PAPluginArgs`, you should see the right output now. And I'm guessing `Submit-Renewal` will stop prompting you for those values.

P.S. If you have multiple different certs/orders using that plugin, you'll have to run the `Set-PAOrder` command once for all of them.

**Comment by mcnahum** [comment]
I was on 3.16 before and yes doing Get-PAPluginArgs give me nothing ... I set it back and it should fix it ... 

Will see in 3 months... thanks for your help

**Comment by rmbolger** [comment]
I'm gonna close this for now. But feel free to re-open if it happens again.
