### ISSUE TITLE
Get-PAAuthorization function not found

### ISSUE THREAD

**Issue by kaspersmjohansen** [rmbolger/Posh-ACME#314]
I am getting this error when requesting a new certificate:
![image](https://user-images.githubusercontent.com/37331486/106649821-663f7f00-6592-11eb-87e2-054813491c2c.png)

**Comment by rmbolger** [comment]
Hi @kaspersmjohansen. Let's see if we can sort this out. How did you install the module? Did you use `Install-Module` or something more manual like downloading the zip from Github? What is the output of `Get-Command -Module Posh-ACME`?

**Comment by kaspersmjohansen** [comment]
I used the Install-Module, but I have both the old v3.19 and the new v4.0 installed:
![image](https://user-images.githubusercontent.com/37331486/106652052-38a80500-6595-11eb-8a05-56521b281d3b.png)

**Comment by rmbolger** [comment]
Generally having both installed doesn't cause a problem because PowerShell will only import the latest unless something specifically told it to import both. But yeah, having both imported at the same time would cause a problem because `Get-PAAuthorizations` was a function in 3.x with an alias of `Get-PAAuthorization`...but they switched in 4.0 so the non-plural is the real function and the plural is the alias.

Try closing out your PowerShell session entirely, opening a new one, and importing the module by name and try again. Theoretically, only the latest version should be imported and the problem should go away. If you want to be sure, you can always remove the older version as well. It's easy enough to get it back if you need to revert.

**Comment by kaspersmjohansen** [comment]
Thank you. That did it. I had to remove v3.19 entirely.

**Comment by rmbolger** [comment]
Weird. Glad to hear it's working now though.
