### ISSUE TITLE
Questions about automatic SSL certificate renewal 

### ISSUE THREAD

**Issue by mkanet** [rmbolger/Posh-ACME#316]
I have a couple of questions about automatic SSL certificate renewal (in anticipation to my certificate's expiration).. in respect to the Posh-AMCE documentation.

------

**Submit-Renewal**
_"The module saves all of the parameters associated with an order and re-uses the same values to renew it. It will throw a warning right now because the cert hasn't reached the suggested renewal window. But you can use -Force to do it anyway if you want to try it. Let's Encrypt currently caches authorizations for roughly 30 days, so the forced renewal won't need to go through validating the challenges again. But you can de-authorize your existing challenges using the following command if you want to test the validation process again."_

------

My production SSL certificate expires 20 days from now.   Currently, when I type the below commands at my PS prompt:

```
import-module -Name Posh-ACME
Set-PAOrder MyDomain.com
```

...it returns the below response _(expecting me to manually supply additional parameters)_

```
WARNING: Fewer DnsPlugin values than names in the order. Using DOcean for the rest.
cmdlet Add-DnsTxtDOcean at command pipeline position 1
Supply values for the following parameters:
DOToken:
```
I would like to be certain that this is normal/expected behavior that's described in the documentation above (due to the cert hasn't reached the suggested renewal window).  I'm confused since I didn't expect it to ask for any parameters.  Also, it didn't specifically warn me about the certificate not reaching the suggested renewal window ..only a warning about DnsPlugin values.  Anyway, if that's not normal behavior, please let me know how to get it working correctly.  Otherwise, Ill move on to my next question...

Considering, the certificate update script `Certificate-Update-Script.ps1` (below) is executed daily.  How can I modify it to pre-emptively force the renewal of my certificate **30 days before it expires** automatically/programmatically?  I'm not sure how to do this since `(Get-PAOrder).CertExpires`  returns an empty value for my certificate:
![Posh-ACME](https://user-images.githubusercontent.com/811008/106670172-8d318d00-6561-11eb-96ef-1a5992c23a2a.png)

**Certificate-Update-Script.ps1**
```
import-module -Name Posh-ACME

$SSL_Cert = $(Get-PACertificate).FullChainFile
$SSL_Key  = $(Get-PACertificate).keyfile

Set-PAOrder MyDomain.com

if ($cert = Submit-Renewal) {

    Copy-Item $SSL_Cert -Destination "C:\Program Files (x86)\...............\...." -Force
    Copy-Item $SSL_Key -Destination "C:\Program Files (x86)\.....................\...." -Force

}
```

**Comment by rmbolger** [comment]
Welcome back, @mkanet. Unfortunately, no. Something likely broke if `Submit-Renewal` is prompting for your token. Just to be clear, the warning about "Fewer DnsPlugin values..." is normal and nothing to worry about. But the prompt for DOToken means for whatever reason the module no longer has that value saved. Another user recently posted about a similar issue with GoDaddy in issue #313. (Makes me wonder whether there's a bug somewhere with regards to saving plugin args that I haven't identified)

In any case, it's easy to fix by telling Posh-ACME to re-save the plugin args like this:

```powershell
Set-PAOrder MyDomain.com -Plugin DOcean -PluginArgs @{DOToken='xxxxxxxx'}
```

Your screenshot indicates the Submit-Renewal has already tried at least once to renew because the order status is "pending". But if it was prompting for the DOToken, it likely just hung or was cancelled.

Also a small tip for your script, I'd probably remove the declaration of `$SSL_Cert` and `$SSL_Key` outside of the if statement and instead use `$cert.FullChainFile` and `$cert.KeyFile` like this:

```powershell
import-module -Name Posh-ACME

Set-PAOrder MyDomain.com

if ($cert = Submit-Renewal) {

    Copy-Item $cert.FullChainFile -Destination "C:\Program Files (x86)\...............\...." -Force
    Copy-Item $cert.KeyFile -Destination "C:\Program Files (x86)\.....................\...." -Force

}
```

**Comment by mkanet** [comment]
@rmbolger Thank you.  Unfortunately, it doesn't look like an easy fix.  This is what's returned:
![Error](https://user-images.githubusercontent.com/811008/106674086-81e16000-6567-11eb-88a4-d380781c1cb9.png)

**Comment by rmbolger** [comment]
So, you only need to specify the primary domain on the order (rather than both of them). And the parameter name is `Plugin` rather than `DnsPlugin` (which is a change in 4.x from 3.x).

**Comment by mkanet** [comment]
Okay, I made progress no errors when using `Set-PAOrder MyDomain.com -Plugin @{DOTOken = 'xxxxxxxxxxx'}`.  Nothing is returned.

Now, when I do  `Get-PAOrder` (by itself)... It still shows status pending with no CertificateExpires value.  Same as before.

**Comment by rmbolger** [comment]
We haven't figured out the original reason why the DOToken was missing. But unless it happens again, there's not much we can do at this point to figure it out. It *shouldn't* happen again if everything is working right. But I can't guarantee it won't if there's a bug somewhere I don't know about.

`Submit-Renewal` is definitely intended for you to run daily (or more often if you wish). It will automatically determine when to start trying to renew based on the `RenewAfter` value (which is derived from `CertExpires`). The current code starts trying to renew when the cert has reached 2/3 of its total lifetime or no more than 30 days before it expires. Generally this means it will have been trying to renew for about 10 days before Let's Encrypt sends you a cert expiration warning email. So if you get that warning email, it's likely something went wrong (leaving you another 20 days to get the problem sorted out). But if you never get the email, everything is working properly.

P.S. Whatever scheduled task you have setup for renewal, it's wise to not have it run precisely on any given hour increment in order to avoid usage spikes on ACME servers. Offset it by 5-15 minutes in either direction or add a random sleep timer in your script like `Start-Sleep (Get-Random 600)`.

**Comment by mkanet** [comment]
Thank you so much for answering all my questions perfectly.  Unfortunately, even if I don't get the issue next time... I'll always be wondering when/if it will happen again.  I'm not entirely confident you'll be able to debug this issue _after_ it occurs.

Anyway, hopefully, I won't get that email from Let's Encrypt again in a couple of months.

**Comment by rmbolger** [comment]
The key to finding (and fixing) bugs is being able to reliably reproduce the problem. I totally get the feeling of uncertainty though. But the cert expiration warning email from Let's Encrypt is a really nice safety net in my opinion.

**Comment by mkanet** [comment]
For the record, below, is the original command I used to create a new cert (with its respective parameters).  

I'm curious.. where are the below parameters stored?  It's possible my PC has a configuration that PoSH-ACME doesn't expect when storing these parameters.

`New-PACertificate mydomain.com, *.mydomain.com -Contact myemail@yahoo.com -DnsPlugin DOcean -PluginArgs @{DOToken = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' } -AcceptTOS`

**Comment by rmbolger** [comment]
Do you recall what version of Posh-ACME you were running when you originally ran that command? I'm wondering if there might be a bug in the migration from 3.x to 4.x.

**Comment by mkanet** [comment]
Sorry, I don't know.  However, you might be able to guess with these clues:

- I installed PoSH-ACME using the command `Install-Module -Name Posh-ACME` on **Nov 24, 2020**.  I ran the `New-PACertificate` command around the same time.
- I haven't updated the module since then.  
- The version I currently have installed is:  **3.19.0**

When do you think I should update PoSh-ACME?

**Comment by rmbolger** [comment]
Doh! For better or worse, the fact that you're not on 4.x yet invalidates my migration bug theory. And 3.19 was the latest release on that date. The current latest is 4.2.0 that I pushed yesterday. It's probably worth upgrading if for no other reason than all the docs on the wiki and such now reference the changes made in 4.0. The only changes you might have to worry about is changing `-DnsPlugin` to `-Plugin` in any of the commands your scripts use.

The upgrade should automatically migrate your plugin args to the new 4.x format. And you can verify they're still saved by running `Get-PAPluginArgs` (which only exists in 4.x).

**Comment by mkanet** [comment]
Thanks.. I just upgraded the module to version 4.2.0.  I ran the command `Get-PAPluginArgs` it returned two items:

```
 Get-PAPluginArgs

Name                           Value
----                           -----
DOToken                        xxxxxxxxxxcxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
ACMEServer                     auth.acme-dns.io
``

I'm guessing I can leave my SSL Certificate update script "as is".  The only changes I made to the script were the suggestions you told me previously (using $cert.FullChainFile and $cert.KeyFile directly in my copy commands; removing unnecessary variable declarations and adding variable time delay).

`Submit-Renewal` returns the correct Warning message now and `Get-PAOrder` returns the correct info.  I think I should be good to go.  Thank you so much for all your time!
