### ISSUE TITLE
Unable to find type [Security.Cryptography.ECCurve+NamedCurves]

### ISSUE THREAD

**Issue by jeffmnall** [rmbolger/Posh-ACME#32]
Working on an Azure Automation Runbook using Posh-ACME 2.2.0.  I obtained Posh-ACME from the powershell gallery in Azure Automation. I'm using the GoDaddy DnsPlugin.  I'm using the  LE_STAGE environment.

```
$PluginArgs = @{}
$PluginArgs.Add("GDKey", $Key)
$PluginArgs.Add("GDSecret", $Secret)

Write-Output $PluginArgs
New-PACertificate <sitename> -AcceptTOS  -Contact <myemail> -DnsPlugin GoDaddy -PluginArgs $PluginArgs -Verbose
```

I always receive this exception:
```
Unable to find type [Security.Cryptography.ECCurve+NamedCurves].
At C:\Modules\User\Posh-ACME\Private\New-PAKey.ps1:31 char:23
 + ...             256 { [Security.Cryptography.ECCurve+NamedCurves]::nistP2 ...
 +                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Security.Crypto...rve+NamedCurves:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
```

I've tried to add-type system.security.cryptography and system.core but no joy.

**Comment by rmbolger** [comment]
I know basically zero about Azure Automation so forgive me if this is a silly question. Which PowerShell edition/version does it run as? Though, it shouldn't technically matter anymore with the 2.2 release that supports PowerShell Core. The [`ECCurve.NamedCurves`](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.eccurve.namedcurves?view=netcore-2.0) class exists on both .NET Core 2.0 and .NET Framework 4.7.1.  Is there a way to take the module out of the equation and just test a one liner that tries to reference it?

```powershell
# fully qualified namespace
$curve = [System.Security.Cryptography.ECCurve+NamedCurves]::nistP256

# skip System. because it's not required in my tests
$curve = [Security.Cryptography.ECCurve+NamedCurves]::nistP256
```

In my quick searching on PowerShell details within Azure Automation, there seem to be some [limitations](https://docs.microsoft.com/en-us/azure/automation/automation-powershell-workflow) that are different than a typical PowerShell environment which I haven't accounted for in the module.

I'll do some more digging as well.

**Comment by rmbolger** [comment]
Can you get the output of the `$PSVersionTable` variable? It should have a CLRVersion entry that we should be able to [determine](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed) the .NET Framework version with. That ECCurve.NamedCurves class has only existed since .NET 4.7 according to its doc page. So if Azure Automation runs on something earlier, you might still be able to get it to work. But you'd have to stick with RSA based keys.

The defaults use an ec-256 key for the ACME account and an 2048 (RSA) key for the certificate. So you'd just have to change the account key setting by adding `-AccountKeyLength 2048` to your `New-PACertificate` command.

**Comment by rmbolger** [comment]
Doh, nevermind about $PSVersionTable, the CLRVersion it returns doesn't have the actual build number in it.  Apparently you have to query the registry instead:

```powershell
Get-ChildItem "HKLM:SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full\" | Get-ItemPropertyValue -Name Release
```

.NET 4.7 would be 460798 or higher.

**Comment by rmbolger** [comment]
If querying the registry does work, I just found [this](https://azure.microsoft.com/en-us/updates/azure-automation-now-supports-net-framework-4-6-when-running-jobs-within-the-service-2/) which implies Azure Automation runs on .NET 4.6 unless it's been updated since February.

Assuming that's the case, definitely try the module again but specifying only RSA keys like I mentioned earlier. I'll see about trying this on my own against a .NET 4.6 box as well.

**Comment by jeffmnall** [comment]
Checking the registry key returned 394806....NET 4.6.2, That's that issue explained.  
I reran `New-PACertificate` with `-AccountKeyLength 2048` and that got me past this exception but tripped another one involving BouncyCastle.  A separate issue.  I'll look at it tomorrow.

Thanks for the help.  This is a great module.

**Comment by rmbolger** [comment]
Not a problem. Glad to help.
