### ISSUE TITLE
[Question] Track multiple certs for same domain

### ISSUE THREAD

**Issue by mbactol3** [rmbolger/Posh-ACME#321]
Hello and thanks for your work on this. I hope this 'issue' area is the right place for a question.

I had a question about creating multiple valid certificates for the same domain.
Seems like the way to do this is to just force a new cert. Lets say I force a renewal / new cert of my domain so I have 2 valid certs like I want (to stage cert rotation or other reason).  It looks like the cert account/order will only track the most recently created certificate.  In terms of Lets Encrypt and how accounts work, is there some method of tracking all created and still valid certificates?  
For a number of purposes, knowing all the valid thumbprints (or how many you have) for a domain cert, or if needing to revoke one for security purposes.

`Get-PAOrder -MainDomain '*.example.com'` -> returns all valid certs for domain

**Comment by rmbolger** [comment]
Hi @mbactol3. You've come to the right place.

The module does create a backup copy of the previous cert when it is renewed. You'll find them named with a .bak extension in the same folder as the new files. However, the module doesn't keep any previous ones around and doesn't really track them over time. The ACME protocol is supposed to allow for querying the orders associated with an account, but Let's Encrypt (not sure about other CAs) hasn't implemented this portion of the spec yet.

If what you want is to effectively have two certs valid for the same name(s) that renew at different intervals, you should be able to make that work by adding a unique name to each one and making that the primary name in the cert. Something like this:

```powershell
New-PACertificate copy1.example.com,example.com,www.example.com
New-PACertificate copy2.example.com,example.com,www.example.com
```

Both will be valid for `example.com` and `www.example.com` and each one will be valid for an additional name that you're not using. The primary name doesn't even need to have an A record in DNS if you're using a DNS plugin for validation.

Technically, there's nothing stopping you (aside from rate limits) from doing this an unlimited number of times where each new cert gets a new unique primary name. The only downside is that Let's Encrypt would send you email expiration warnings for each one because you haven't renewed them with the exact same set of names.

**Comment by mbactol3** [comment]
Thanks @rmbolger ! 
I'll explore this suggestion in my implementation.  (Azure plugin by the way).  
And lastly, to be clear, since this is using a single account, the same private key will be used for these (and on renewal)?

**Comment by rmbolger** [comment]
So there's a difference between the private key associated with the ACME account and the private key associated with each cert. There's only one account key (unless you create multiple accounts). And each cert will generate its own unique private key that won't change on renewal unless you use `Set-PAOrder -AlwaysNewKey` on that order.

But in the example above, each of those certs is unique as far as the module is concerned so they would have different private keys without some additional work up front. The private key for each cert isn't actually created until fairly late in the order process when it has to generate the CSR to send to the ACME server. And if the internal CSR generation function finds an existing key file, it won't generate a new one. So theoretically something like this should work if you want the certs to use the same key. 

Creating the first cert doesn't change.

```powershell
New-PACertificate copy1.example.com,example.com,www.example.com
```

But if you want the second (or any subsequent) cert to use the same private key as the first one, you need to create a basic new order first, copy the old key into the new order's folder, and then proceed with getting the cert. There's not really a nice way to reference a given order's folder on disk. But something like this should work.

```powershell
New-PAOrder copy2.example.com,example.com,www.example.com
$oldKey = (Get-PACertificate copy1.example.com).KeyFile
$newFolder = Join-Path (Get-Item $oldKey).Directory.Parent (Get-PAOrder).MainDomain
Copy-Item $oldKey $newFolder
New-PACertificate copy2.example.com,example.com,www.example.com
```

**Comment by rmbolger** [comment]
The thought occurs to me that perhaps it would be nice if `New-PAOrder` had a parameter that let you import an existing private key similar to how you can with `New-PAAccount`.

**Comment by rmbolger** [comment]
This is now an option in the dev/main branch.
