### ISSUE TITLE
Root Issuer not changing even with -PreferredChain parameter

### ISSUE THREAD

**Issue by lucaz82** [rmbolger/Posh-ACME#328]
Hi, 
we've got an issue after your fix and the Let's Encrypt staging cert changes. Currently using v4.3.2
We found your pull request and changed the PreferredChain parameter as stated. 
https://github.com/rmbolger/Posh-ACME/pull/320

This is the Powershell we run:
```
New-PACertificate `
"importconfigtest-app.*****.net" `
-AcceptTOS `
-PreferredChain '(STAGING) Pretend Pear X1' `
-ErrorAction Stop `
-Force `
-Verbose
```

This is the output we receive:
```
VERBOSE: Using ACME Server https://acme-v02.api.letsencrypt.org/directory
VERBOSE: Using account *****
VERBOSE: Creating a new order for importconfigtest-app.*****.net
VERBOSE: Finalizing the order.
VERBOSE: Creating new certificate request with key length 2048.
VERBOSE: Downloading signed certificate
WARNING: The preferred chain issuer, (STAGING) Pretend Pear X1, was not found. Using the default chain.
VERBOSE: Updating cert expiration and renewal window
VERBOSE: Successfully created certificate.
```

In the end, the certificate still has the wrong Issuer (see screenshot below).
![image](https://user-images.githubusercontent.com/56246539/111288058-20231400-8644-11eb-97c8-6be3c3280d30.png)

According to this post, LE changed the Root Issuer. 
https://community.letsencrypt.org/t/staging-doctored-durian-root-ca-x3-is-expired-breaks-test-environment/145689/23

Can you tell what we're doing wrong?
Thanks in advance.
Lucas

**Comment by rmbolger** [comment]
Hi @lucaz82. The first thing I see doesn't really make sense. The verbose output shows you are running the command against the Let's Encrypt production environment (`https://acme-v02.api.letsencrypt.org/directory`) which explains the warning later about not being about to find `(STAGING) Pretend Pear X1`. But the cert image is clearly a staging cert. Are you sure you were looking at the right cert?

If you want to make sure you're actually running against the staging environment, you either need to run `Set-PAServer LE_STAGE` before your `New-PACertificate` command or add `-DirectoryUrl LE_STAGE` to it.

Assuming you get the preferred chain stuff working properly against the staging server, the Windows cert GUI doesn't necessarily show the actual cert chain that is being presented by your webserver if it had already cached another valid chain. It is better to use something like [ssllabs.com](https://www.ssllabs.com/ssltest/) to see exactly what the server is sending. If your webserver is not on the internet, you can also use [testssl.sh](https://testssl.sh/) instead or even just openssl with the `s_client` option.

**Comment by lucaz82** [comment]
Hi @rmbolger

I added the suggested parameter to the script. I tested a lot back and forth and I am still stuck with an invalid certificate.

```
New-PACertificate `
	"test-lucas.***.net" `
	-AcceptTOS `
	-PreferredChain '(STAGING) Pretend Pear X1' `
	-ErrorAction Stop `
	-Force `
	-DirectoryUrl LE_STAGE `
	-Verbose
	
	
Please review the Terms of Service here: https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
VERBOSE: Using ACME Server https://acme-staging-v02.api.letsencrypt.org/directory
VERBOSE: Creating a new ec-256 account with contact:
WARNING: No email contacts specified for this account. Certificate expiration warnings will not be sent unless you add at least one with Set-PAAccount.
VERBOSE: Using account 18639827
VERBOSE: Creating a new order for test-lucas.***.net
VERBOSE: Publishing challenge for Domain test-lucas.***.net with Token 3h_T_Wv8rooEJKh4leGfvvMm6NLWG2Umy8ai_7dmA-c using Plugin Manual and DnsAlias ''.
VERBOSE: Saving TXT record to display when Save-DnsTxt is called.
VERBOSE: Saving changes for Manual plugin

[...]

VERBOSE: Finalizing the order.
VERBOSE: Creating new certificate request with key length 2048.
VERBOSE: Creating new private key for the certificate request.
VERBOSE: Downloading signed certificate
VERBOSE: Using preferred chain issuer, (STAGING) Pretend Pear X1.
VERBOSE: Updating cert expiration and renewal window
VERBOSE: Successfully created certificate.
```

When looking at the certificate, now the preferred chain is in there, but not as root. 
"This certificate cannot be verified up to a trusted certification authority"
![image](https://user-images.githubusercontent.com/56246539/111649573-c87fd680-8804-11eb-8b28-843ca0a07f74.png)



Your suggested test tools will only work if I get this runbook from azure through without an failure.
This is the failure the runbook returns. This is why I am thinking, that this is not an plain windows viewing issue.


`New-AzResourceGroupDeployment : 2:27:59 PM - The deployment 'ClickOnce-ltest-0318-1427' failed with error(s). Showing 1 out of 1 error(s). Status Message: Expired certificate is not allowed. (Code: BadRequest) - Expired certificate is not allowed. (Code:) - (Code:BadRequest) - (Code:) CorrelationId: 73b3c92a-ae8e-4ee2-91a0-1ca4b26c4ba7 At C:\Temp\wmkx4owd.q2y\Create-ClickOnceWebsite.ps1:77 char:21 + $deploymentResult = New-AzResourceGroupDeployment ` + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : NotSpecified: (:) [New-AzResourceGroupDeployment], Exception + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCmdlet`


Just let me know if you need any more information.
Huge thanks,
Lucas

**Comment by rmbolger** [comment]
The verbose log you posted looks a lot better. The preferred chain option found a match for `(STAGING) Pretend Pear X1` which means the `chain.cer` file (and fullchain.cer, and fullchain.pfx) should only have one CA cert in it instead of two.

Can you give more detail on how you're deploying the cert to Azure?

**Comment by lucaz82** [comment]
We use multiple runbooks. 
First we start a runbook "New Customer" which basically calls "Create-LetsEncryptCertificate".
This runbook checks if there's a cert for this appname in the keyvault and if not, it requests a new one and imports that to the keyvault after successful retrieval.

```
#Requires -Version 5.1
#Requires -Module Az.Resources
#Requires -Module Az.KeyVault
#Requires -Module Az.Accounts
#Requires -Module Posh-ACME

Param(
	[Parameter(Mandatory = $true)]
	[ValidateNotNullOrEmpty()]
	[string] $PublicDnsRecord
)

#Import-Module Posh-ACME -ErrorAction SilentlyContinue

$acmeVaultUrl = Get-AutomationVariable -Name "ACMEVaultUrl"
$acmeVaultRegistrationEmail = Get-AutomationVariable -Name "ACMEVaultRegistrationEmail"
$globalDnsZoneName = Get-AutomationVariable -Name "GlobalDnsZoneName"
$keyVaultName = Get-AutomationVariable -Name "GlobalKeyVaultName"
$certificateMinimumValidDays = Get-AutomationVariable -Name "CertificateMinimumValidDays"
$namePrefix = Get-AutomationVariable -Name  "namePrefix"

Write-Output "Creating LetsEncrypt Certificate..."
Write-Output "  Azure Key Vault:                $keyVaultName"
Write-Output "  ACMEVaultUrl:                   $acmeVaultUrl"
Write-Output "  ACMEVaultRegistrationEmail:     $acmeVaultRegistrationEmail"
Write-Output "  Public DNS Record:              $PublicDnsRecord"
Write-Output "  Global DNS Zone Name:           $globalDnsZoneName"
Write-Output "  Certifiate minimum valid Days:  $certificateMinimumValidDays"

# Connection to azure
.\Connect-Azure.ps1

$keyName = "HttpsCert-$PublicDnsRecord"
$certificateRequired = $true
if (Get-AzKeyVaultCertificate -VaultName $keyVaultName | Where-Object { $_.Name -eq $keyName }) {
	$certificate = Get-AzKeyVaultCertificate -VaultName $keyVaultName -Name $keyName -ErrorAction Stop

	if ($certificate.Certificate.NotAfter -gt (Get-Date).AddDays($certificateMinimumValidDays)) {
		$certificateRequired = $false
		Write-Output "Can use HTTPS Certificate for $PublicDnsRecord, expires $($certificate.Certificate.NotAfter)"
	}
}

if ($certificateRequired) {
	Write-Output "Require new certificate for $PublicDnsRecord..."

	$context = Get-AzContext
	$token = [Microsoft.Azure.Commands.Common.Authentication.AzureSession]::Instance.AuthenticationFactory.Authenticate( `
				$context.Account, `
				$context.Environment, `
				$context.Tenant.Id.ToString(), `
				$null, `
				[Microsoft.Azure.Commands.Common.Authentication.ShowDialog]::Never, `
				$null, `
				"https://management.core.windows.net/").AccessToken

	$azureParams = @{
		AZSubscriptionId = $context.Subscription.Id
		AZAccessToken = $token
	}

	Write-Output "Create new Certificate"
	Set-PAServer $acmeVaultUrl
	if ($namePrefix -ne "***Prod") {


		$cert = New-PACertificate `
			"$PublicDnsRecord.$globalDnsZoneName" `
			-AcceptTOS `
			-Verbose `
			-Contact "mailto:$acmeVaultRegistrationEmail" `
			-DnsPlugin Azure `
			-PreferredChain "(STAGING) Pretend Pear X1" `
			-PluginArgs $azureParams `
			-ErrorAction Stop `
		
		}
		else {
			$cert = New-PACertificate `
			"$PublicDnsRecord.$globalDnsZoneName" `
			-AcceptTOS `
			-Contact "mailto:$acmeVaultRegistrationEmail" `
			-DnsPlugin Azure `
			-PluginArgs $azureParams `
			-ErrorAction Stop `
	
		}
		
	Write-Output $cert

	Write-Output "Import new Certificate to KeyVault"
	Import-AzKeyVaultCertificate -VaultName $keyVaultName -Name $keyName -FilePath $cert.PfxFullChain -Password $cert.PfxPass
}
```

The script "Create-ClickOneWebsite" then build a package for deplyoment with the certificate. Which is this scriptblock:

```
# Create ClickOnce template parameter file
$globalDnsZoneName = Get-AutomationVariable -Name "GlobalDnsZoneName"
$keyVaultName = Get-AutomationVariable -Name "GlobalKeyVaultName"
$keyVault = Get-AzKeyVault -VaultName $keyVaultName -ErrorAction Stop
$publicDnsCertificateCertificateName = "HttpsCert-$($EnvironmentName.ToLowerInvariant())"
$publicDnsCertificateCertificate = Get-AzKeyVaultCertificate -VaultName $keyVaultName -Name $publicDnsCertificateCertificateName -ErrorAction Stop
$templateParameterFileName = "ClickOnceDeployment-$EnvironmentName.parameters.json"
$templateParameterFileContent = @{
	"`$schema" = "http://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#"
	"contentVersion" = "1.0.0.0"
	"parameters" = @{
		"clickOnceWebsiteName" = @{
			"value" = $webAppName
		}
		"publicDnsCertificateSecretName" = @{
			"value" = $publicDnsCertificateCertificate.Name
		}
		"keyVaultResourceId" = @{
			"value" = $keyVault.ResourceId
		}
		"environmentName" = @{
			"value" = $EnvironmentName
		}
		"webDeploymentPackageUrl" = @{
			"value" = "$webDeploymentPackageUrl"
		}
		"globalDnsZoneName" = @{
			"value" = "$globalDnsZoneName"
		}
	}
} | ConvertTo-Json -Depth 5 -Compress
$templateParameterFileContent | Out-File $templateParameterFileName -Force

$errorMessages = @()
$deploymentResult = New-AzResourceGroupDeployment `
						-Name "ClickOnce-$EnvironmentName-$(((Get-Date).ToUniversalTime()).ToString('MMdd-HHmm'))" `
						-ResourceGroupName $LocationManagementResourceGroupName `
						-TemplateUri "https://***.json" `
						-TemplateParameterFile $templateParameterFileName `
						-Force -Verbose `
						-ErrorVariable errorMessages 
```

`$deploymentResult` is line 77 from the error message I posted earlier.
I assume that during the cmdlet `New-AzResourceGroupDeployment` makes additional checks if the certificate is valid

Hope this helps,
Lucas

**Comment by rmbolger** [comment]
Interesting. I would have thought `Import-AzKeyVaultCertificate` would be the place Azure gets whiny about the chain building, but I guess not. Unfortunately, I'm not sure what to recommend as far as the error from `New-AzResourceGroupDeployment`. It's clearly doing some sort of native chain building that you don't have control over (much like the Windows cert GUI).

The root of the problem is that the two chains being offered by the Let's Encrypt staging environment have an identical first level Issuer, `(STAGING) Artificial Apricot R3` which is issued by `(STAGING) Pretend Pear X1`. The default chain also includes the second level issuer `(STAGING) Pretend Pear X1` issued by the purposefully expired `(STAGING) Doctored Durian Root CA X3` root. But a separate self-signed `(STAGING) Pretend Pear X1` certificate exists which is the root for the alternate chain. It's all supposed to mimic the eventual configuration for production as described here:

https://letsencrypt.org/2020/12/21/extending-android-compatibility.html

The staging version of the image on that page looks like this:

![2020 12 21-android-compat-cert-chain-staging](https://user-images.githubusercontent.com/2327255/111679094-2fd66000-87de-11eb-85dc-948e2b5b4eaa.png)

None of the roots are actually supplied via the ACME protocol because generally systems will already have those roots installed in their list of trust anchors. I'm not sure how that works in Azure though particularly for non-publicly trusted roots like those in Let's Encrypt staging. The self-signed Pretend Pear cert can be downloaded from [here](https://letsencrypt.org/certs/staging/letsencrypt-stg-root-x1.pem) though.

It might be worth opening a ticket with Azure support for guidance on how to deal with this.

**Comment by rmbolger** [comment]
Another option if you can't find a way around the Let's Encrypt chain issues is to consider using a different ACME CA for the time being. [BuyPass](https://www.buypass.com/) and [ZeroSSL](https://zerossl.com/documentation/acme/) are two CAs that offer free certs via ACME (though BuyPass doesn't offer wildcard certs).

They both have DirectoryUrl shortcuts in Posh-ACME: BUYPASS_PROD, BUYPASS_TEST, and ZEROSSL_PROD (there's no ZeroSSL test server I know of). Setting up an account with ZeroSSL also takes a bit more effort up front because they require External Account Binding (EAB). Their [ACME documentation](https://zerossl.com/documentation/acme/) page has more details. But essentially you need to generate an EAB Key ID and HMAC value from the website and then use them with `-ExtAcctKID` and `-ExtAcctHMACKey` when you call `New-PAAccount`.
