### ISSUE TITLE
TOTP authentication in AutoDNS plugin

### ISSUE THREAD

**Issue by perler** [rmbolger/Posh-ACME#330]
to use the plugin with [Schlund](https://www.schlundtech.de/services/xml-gateway/) when multi factor authentication is enabled, the support writes..

`Bei der Zwei-Faktor-Authentifizierung muß zusätzlich zu Benutzernamen und Passwort ein sechsstelliger Zahlencode, der sogenannte Token, eingegeben werden.

Der Token wird mit dem Time-based One-time Password Algorithmus (RFC 6238) erzeugt.

Der Token wird im auth-Block im Tag <token> eingegeben.

<auth>
    <user>USER</user>
    <context>CONTEXT</context>
    <password>PASSWORD</password>
    <token>TOKEN</token>
</auth>`

any chance that we get this implemented?

**Comment by rmbolger** [comment]
Hi @perler. Adding a parameter to accept a TOTP code shouldn't be that hard. However, it may not make sense because the whole point of TOTP codes is that they are very short lived. You'd be racing to add the current code to your plugin parameters variable and submit the order before it expired. There's also no way for the module to get an updated code when it's trying to do an automated renewal.

I'm happy to try and add support for it if you're ok with having to manually renew with an updated code every time though.

Alternatively, is there a way to create a dedicated user for DNS updates that doesn't require TOTP?

**Comment by perler** [comment]
I think, using an extra user is the sensible way to go, but I am not sure if Schlund is offering this, I will ask. Alternatively, are there scripts, that create OTPs and feed them to the script?

**Comment by rmbolger** [comment]
If there are scripts for TOTP, I don't know of any. I've only ever used an app on my mobile phone. But it does seem like something that might exist.

I was looking at the AutoDNS API documentation and I noticed they mention authentication via "Trusted application" [here](https://help.internetx.com/display/APIXMLEN/Authentication#Authentication-AuthenticationviaTrustedApplication).

> A "Trusted Application" is an application that you have created in AutoDNS as trustworthy.

I would still have to update the plugin to support it. But this might also be an option.
