### ISSUE TITLE
Constellix DNS provider support

### ISSUE THREAD

**Issue by swinster** [rmbolger/Posh-ACME#331]
Hi, 

We have used DNS Made Easy as a provider for many years with an ACME client that using the PoshACME library, however, the powers that be have decided we need more DNS power but wanted to stick with the same company. Constellix then is the same company that is behind DNS Made Easy, and hopefully, the API is similar/identical.  Is it a possibility that you might support this?

**Comment by swinster** [comment]
https://api-docs.constellix.com/

**Comment by rmbolger** [comment]
Hey @swinster. Thanks for the link to the docs. I skimmed the authentication related bits of the docs and they look *very* similar to how authentication is done with DNS Made Easy...just with different header names. It's probably different enough to make a separate plugin rather than trying to add support for Constellix to the existing plugin. But if the rest of the API is as similar, it should be pretty quick.

It looks like I can get an account with a single domain to test against for about $5 for the first month which should be more than enough time. So I'll try and get that setup and start working on it the next chance I get.

**Comment by rmbolger** [comment]
> But if the rest of the API is as similar, it should be pretty quick.

The rest of the API is unfortunately not similar. And there were more differences in the authentication bits than I originally noticed. So it's good I started making a new plugin. But it's not going to be quite as quick as the glorified find/replace I was hoping it would be.

**Comment by swinster** [comment]
Just as I had my hopes up ;). Ah well, it will still be absolutely worth waiting for. 

Appreciate any effort you put in here. Do you have a beer fund account :)

**Comment by rmbolger** [comment]
I think I've sorted out more or less what needs to change to make it go. So it shouldn't be too long.

I also appreciate the thought on the beer fund. 😁 I've got the GitHub native Sponsors thing [here](https://github.com/sponsors/rmbolger) which is intended to be a monthly recurring thing (though there's nothing stopping someone from cancelling after one month). Or you could also just [PayPal me](https://paypal.me/rmbolger).

**Comment by swinster** [comment]
Sorted - don't spend it all at once :)

**Comment by rmbolger** [comment]
Ok, just uploaded a draft of the Constellix plugin and guide to the main branch. Care to give it a spin assuming you already have access to Constellix?

**Comment by rmbolger** [comment]
@swinster Do you have the ability to test the plugin before I call it good?

**Comment by swinster** [comment]
Damn it - I meant to do this for you last week. Got sidetracked with a big migration project for this week. I will check this out over the Easter weekend.

**Comment by rmbolger** [comment]
@swinster Did you get a chance to test it out?

**Comment by rmbolger** [comment]
I decided to just make this live in the 4.4.0 release. Hope it works for you. Let me know if you run into issues.
