### ISSUE TITLE
Azure DNS has stopped working in Powershell 5

### ISSUE THREAD

**Issue by rwood42** [rmbolger/Posh-ACME#368]
We debugged this and it was using TLS 1.1, this is not supposed to be shut off for a few months yet, but is going away in a few months anyway. Forcing TLS 1.2 thusly fixed the issue:

do {
        Write-Debug "Querying zones list page"
        try {
            [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12;
            $response = Invoke-RestMethod $url -Headers $script:AZToken.AuthHeader @script:UseBasic
        } catch { throw }
        # grab the public zones from the response
        $zones += $response.value | Where-Object { $_.properties.zoneType -eq 'Public' }
        $url = $response.nextLink
    }

**Comment by rmbolger** [comment]
Hi @rwood42. Thanks for the report.

What's odd is that the module enables* TLS 1.2 when it first loads and that should affect all connections for the current PowerShell session. So individual plugins shouldn't need to touch TLS settings in order to work.

*Technically, the module doesn't enable TLS 1.2 explicitly. It enables all versions of TLS beyond whatever is currently set when the module is loaded. The code is here:*

https://github.com/rmbolger/Posh-ACME/blob/5e7c106360ed975764d9af501f59f041ab85e147/Posh-ACME/Private/InitTLS.ps1#L72-L80

Are you running this in conjunction with any other scripts or modules that might have also tried to tweak the TLS settings? Or are you perhaps trying to use the plugin as a standalone script rather than in conjunction with the module?

**Comment by rwood42** [comment]
I did not originally have anything changing TLS I (correctly I guess) assumed you would be doing it. I did try forcing TLS 1.2 in my script unsuccessfully before modifying the posh file directly.

**Comment by rmbolger** [comment]
Can you post your script (sanitized if necessary)? Also, do you have anything loading by default in your PowerShell profile? My next suggestion would be to try using the unmodified version of the plugin, but from a PowerShell session that was launched using `powershell.exe -NoProfile`.

Bottom line, you shouldn't need to touch the TLS settings under normal circumstances. So there's something different about your specific environment that's causing things to get weird.
