### ISSUE TITLE
POSH_ACME Certificate in 2 locations

### ISSUE THREAD

**Issue by proclia** [rmbolger/Posh-ACME#369]
Using `POSH-ACME` can i get a same certificate renewed at 2 different locations?
```
Set-PAServer $LEServer
New-PACertificate
```
Using the `New-PACertificate` cmdlet i am creating a certificate in one server and i would like to use the same certificate in another server, if i use `GET-PACertificate` in another server will i get the same renewed certificate in another server? or should i copy the certificate from server1 and use in server2

**Comment by rmbolger** [comment]
Hi @proclia, good question. You can actually do whichever method you prefer, both will work.

If you have Posh-ACME installed separately on both servers and request a cert with the same details on each one, you'll technically have two different certificates, private keys, and ACME accounts. But both certificates will be perfectly valid. For two servers this isn't a problem, but you may start running into [rate limits](https://letsencrypt.org/docs/rate-limits/) if it goes much beyond two.

A slightly more efficient version of this option is to setup Posh-ACME and create an ACME account on the first server (`New-PAAccount -AcceptTOS -Contact 'me@example.com'`). Then copy the config to the other server before requesting the cert for the first time. This way, both servers will be using the same ACME account. So during renewals, only the first server will have to re-validate the name(s) in the cert. The second server will immediately be authorized due to cached authorizations from the first.

Setting up Posh-ACME on only one server and then copying the resulting cert + private key to the other servers is also a perfectly valid strategy particularly if you have many servers that need the same cert. Just be wary that the private key is particularly sensitive, so you want to make sure your transfer method doesn't expose it to unauthorized folks. But since Posh-ACME doesn't rotate the private key by default on renewals, you technically only need to distribute it once during the initial cert request.

**Comment by proclia** [comment]
Thanks @rmbolger for the reply
```
If you have Posh-ACME installed separately on both servers and request a cert with the same details on each one, you'll technically have two different certificates, private keys, and ACME accounts. But both certificates will be perfectly valid. For two servers this isn't a problem, but you may start running into rate limits if it goes much beyond two.
```
If i understand this correctly, `*.exampledomain.com` cert can be installed twice with 2 different dates? but still can be used without any issues? 
my scenario is this, i am installing a new cert using `azure automation` and i may have upto `5` of them for same domain, since they need to reside in 5 different servers, so if i just delay the `same domain cert` creation by `n` number of days for `5` different locations it should be fine?

**Comment by rmbolger** [comment]
> If i understand this correctly, *.exampledomain.com cert can be installed twice with 2 different dates? but still can be used without any issues?

Yes, certificates are completely independent from each other even if they have the same names. They're either valid or not and you can copy and use them wherever you want for as long as they're valid. The machine that gets the cert doesn't even have to be the same machine that ultimately uses it.

With 5 servers, you may bump into the rate limit for "Duplicate Certificate limit of 5 per week" depending on how spread out the requests are. But even if you can stagger things enough to avoid the rate limit, I'd probably suggest the other strategy out of politeness for the free resources you'd be consuming from Let's Encrypt.

You only really need one cert. Since you're using Azure, your automation job could store it in Key Vault and the other servers could retrieve it from the same.
