### ISSUE TITLE
Expand option similar to certbot

### ISSUE THREAD

**Issue by t3hchipmunk** [rmbolger/Posh-ACME#377]
Hello!

First off, thank you for this module. It has made life so much easier for our expanding infrastructure and deploying certs to all of our machines.

I would be interested to know if there is an ability to add domains and/or subdomains to an already existing certificate? I did not see anything in the docs or code about this, though I may have missed it. I do see that certbot has this functionality using the [`--expand`](https://certbot.eff.org/docs/using.html#re-creating-and-updating-existing-certificates) arg.

By default I would assume that I could just do a New-PACertificate with the added domains, however, the certbot docs appear to indicate that doing this will cause the letsencrypt api to question what you actually intend to do and passing those arguments will specify the exact intent. However, it also seems vaguely worded as to what happens when a request is made with additional domains.

In any case, some guidance on this functionality within your library would be appreciated.

Thanks!

**Comment by rmbolger** [comment]
Hi @t3hchipmunk, thanks for reaching out. The first thing to understand is that an existing certificate can't technically be modified. It is cryptographically guaranteed to never change. The `--expand` option in certbot and various other commands that let you change the names in a cert is ultimately causing certbot to get a *new* certificate with the updated set of names. It's the same thing that happens during a normal renewal, except in that case the names don't change.

In any case, it is possible to "modify" the names in a cert with Posh-ACME. But it's not terribly well documented and it got slightly more cumbersome in the 4.7.0 release if you have customized your order names. Essentially, you re-run `New-PACertificate` and only specify the new set of names. If you're on 4.7+ and customized the order name, you also have to specify the `-Name` parameter with the customized name. 

So let's say you have an existing order called "website" that currently has the names `example.com` and `www.example.com` and you want to add `blog.example.com`. You'd run the following to add that name.

```powershell
New-PACertificate 'example.com','www.example.com','blog.example.com' -Name website
```

Under the hood, it will look for an existing order called "website", pick up the rest of the order config like plugin details, and proceed to get a new certificate with the updated set of names.

If you're still on 4.6 or earlier *or* you haven't customized the order name, you can omit the Name parameter. The only limitation is that the first domain in the list must be the same as the old certificate in order for it to find and use the config from the old one. Conversely in 4.7, as long as you specify the Name parameter, you can do whatever you want with the Domain list including changing or removing the first name.

P.S. I'm actually in the middle of revamping the docs for this module into a more comprehensive documentation site rather than just the Github wiki. So it's good timing on this sort of thing because I can add it to the list of doc stuff to tweak. 😉

**Comment by rmbolger** [comment]
To mimic the "expand" option in certbot, you could potentially do something like this to prep your parameters for `New-PACertificate` without needing to know the list of domains in the old order.

```powershell
$newCertParams = Get-PAOrder | Select-Object Name,@{L='Domain';E={@($_.MainDomain)+@($_.SANs)}}
$newCertParams.Domain += 'newname.example.com'
New-PACertificate @newCertParams
```

**Comment by t3hchipmunk** [comment]
That's great and thanks for the explanation, that makes a lot of sense.

Would you like for me to close this issue or leave it as a reminder for the docs?

Thanks again!

**Comment by rmbolger** [comment]
I made a note for myself elsewhere. Thanks though.
