### ISSUE TITLE
Missing assembly Org.BouncyCastle.Security.SecureRandom

### ISSUE THREAD

**Issue by echodreamz** [rmbolger/Posh-ACME#38]
Desktop works fine, however after installing on server, I am receiving...

> Cannot find type [Org.BouncyCastle.Security.SecureRandom]: verify that the assembly containing this type is loaded.

**Comment by echodreamz** [comment]
Kill this, simply add the BouncyCastle.Crypto.dll file to the GAC using gacutil.exe.

**Comment by rmbolger** [comment]
Adding to GAC shouldn't be necessary. Double check you have .NET 4.7.1 installed on the server.

The BouncyCastle DLL included with 2.2 is built against .NET Standard 2.0 so that it can work against both full .NET Framework and .NET Core. The earliest version of .NET that supports running .NET Standard 2.0 DLLs is .NET 4.6.1. But there are other compatibility reasons you need .NET 4.7.1.
