### ISSUE TITLE
Plugin for Core Networks

### ISSUE THREAD

**Issue by dwydler** [rmbolger/Posh-ACME#381]
Hello @rmbolger,
i try to write a Plugin for the german webhoster Core Networks. I have two questions about this:

1. According to the api documentation (https://beta.api.core-networks.de/doc/#functon_dnszones_commit) one or more changes must be commited. Only then are changes written from the database to the DNS zone. Is it possible that the function Save-DnsTXT get also the parameter `$RecordName` (optional)? I don't want to write my own function for it.

2. [UseBasicParsing](https://github.com/rmbolger/Posh-ACME/blob/c7ca310bf351636c3fd443e63cbfcac12e5d8568/docs/Plugins/Plugin-Development-Guide.md#usebasicparsing): Is that still recommended? If it's like that should i use `@script:UseBasic` or `$script:UseBasic`. In my tests (no matter which parameter of the two) the query no longer works. Here a query example of my tests:
 `Invoke-RestMethod -Method Post -Headers $headers -Body $JsonBody -ContentType "application/json" -Uri "$CoreNetworksApiRoot/dnszones/$CoreNetworkDnsZone/records/" @script:UseBasic`
What am I doing wrong?

**Comment by rmbolger** [comment]
Hey @dwydler, that's great! Happy to help answer your questions. Feel free to post additional ones as you have them.

Regarding the Save function, no. Since it's only called once for all change in an order, the only parameters that are sent to it are the ones passed by the user via `-PluginArgs`. However, if you need some data like `$RecordName`, you should be able to save it during the Add/Remove calls as a [script-scoped](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_scopes#powershell-scopes) variable which will still exist when Save is called. There's actually a decent example of this in the [Manual](https://github.com/rmbolger/Posh-ACME/blob/main/Posh-ACME/Plugins/Manual.ps1) plugin where it collects the records from each Add/Remove call and then displays them to the console during the Save call.

UseBasicParsing is still definitely recommended. The variable normally only exists in the module's scope. So if you're testing that `Invoke-RestMethod` call outside the scope of a running plugin, you'd have to create your own copy like this:

```powershell
$script:UseBasic = @{UseBasicParsing=$true}
```

The other somewhat confusing thing you might be running into is that the variable is `$script:UseBasic`, but when you're adding it to a function call like `Invoke-RestMethod`, you need to change the prefix to `@` because it's a hashtable that you're [splatting](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_splatting) onto the function.  `Invoke-RestMethod @script:UseBasic` is basically the equivalent of running `Invoke-RestMethod -UseBasicParsing:$true`.

**Comment by dwydler** [comment]
> Regarding the Save function, no. Since it's only called once for all change in an order, the only parameters that are sent to it are the ones passed by the user via -PluginArgs

In this case every change on the dns zone must be committed. It would be helpful if the function was execute after each Add-DnsTxt / Remove-DnsTxt. It is not the first and last provider which to do it that way. In this case i wrote a handler function.

> UseBasicParsing is still definitely recommended

I wasn't sure because of the descrption in the guide. I will consider it. 

---
I do some tests with [idn domains](https://github.com/rmbolger/Posh-ACME/blob/c7ca310bf351636c3fd443e63cbfcac12e5d8568/docs/Plugins/Plugin-Development-Guide.md#internationalized-domain-name-idn). For that i use follow command:
`New-PACertificate with follow parameter/value -Domain "übung1.example.com"` 

Powershell displays follow error:
_'übung1.example.com' contains incompatible characters. Please use only A-Z, a-z, 0-9, or any of '-._!'_
_In C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\4.8.1\Private\Test-ValidFriendlyName.ps1:23 Zeichen:9_

So it is not possible to catch this case in the plugin. What is your consideration/idea for that?

**Comment by rmbolger** [comment]
Yeah, saving changes after each Add is fine as long as the API provider doesn't end up rate limiting the number of connections. As you say, there are many other plugins that do this. Batching the changes and saving them all at once is more of an advanced workflow.

For IDN domains, the ACME server expects to receive the Punycode version of the name. So in your example, you would pass `xn--bung1-jva.example.com` instead of `übung1.example.com`. But your DNS provider may or may not expect the non-punycode version. So you might have to convert it back within the plugin.

**Comment by rmbolger** [comment]
After looking more closely at their API docs, their Commit method only requires the zone name rather than the individual record name which makes sense. And when you Add a record, you also need the zone name. So I'd probably recommend saving the zone name as a script variable during the Add method and then running the Commit method during Save.

**Comment by dwydler** [comment]
> For IDN domains, the ACME server expects to receive the Punycode version of the name. So in your example, you would pass xn--bung1-jva.example.com instead of übung1.example.com

Okay, that make sense. Perhaps you can add this (important) information to the [Plugin Development Guide](https://github.com/rmbolger/Posh-ACME/blob/c7ca310bf351636c3fd443e63cbfcac12e5d8568/docs/Plugins/Plugin-Development-Guide.md#internationalized-domain-name-idn).

> So I'd probably recommend saving the zone name as a script variable during the Add method and then running the Commit method during Save.
Thanks for your idea. I'm not a big fan of global variables. But i will think about it again.

**Comment by rmbolger** [comment]
> Perhaps you can add this (important) information to the Plugin Development Guide.

Excellent suggestion. I'll do that.

> I'm not a big fan of global variables.

It's not technically global since it's only accessible from within the module's scope and not the caller's scope. But I get it. As long as you use a plugin-specific variable name, you shouldn't have any conflicts with other stuff.

**Comment by dwydler** [comment]
> I just checked and it's already in there, second sentence in the first paragraph in the IDN section. https://poshac.me/docs/v4/Plugins/Plugin-Development-Guide/#internationalized-domain-name-idn

Thank you, wasn't clear enough for me.

If you have the time, take a look at my [first branch](https://github.com/rmbolger/Posh-ACME/compare/main...dwydler:Added-Plugin-for-core-networks.de?expand=1). I'm looking forward to your feedback.

**Comment by rmbolger** [comment]
No worries, I'll try and make some tweaks to make it more obvious.

I might get a chance to look at the code this weekend, but you're competing with another plugin request at the moment.

**Comment by rmbolger** [comment]
If you want to submit a preliminary pull request from your branch, we can collaborate further in there. A few minor suggestions I've got so far just skimming.

- You can delete the `CoreNetworks-Readme.md` file in the main Plugins folder that points to the doc site version. Those are only needed for plugins that existed in the module prior to 4.8. (I think I need to update the dev guide about this as well)
- The `title:` at the top of the actual CoreNetworks.md file should match the name of the plugin rather than the more formal name of the provider. It affects the URL that the doc site uses for that page.
- I know the current API url is labeled as "beta" and I like that you made `CoreNetworksApiRoot` a parameter. But if the beta URL is the only currently valid URL, it probably makes more sense to take away the Mandatory flag and give it a default value of the current beta URL. One less thing for users to care about until the provider forces them to.
- Not sure if you're using the literal `-UseBasicParsing` switch just for testing, but it will need to be changed to `@script:UseBasic` prior to merging.
- For getting the short `$DnsTxtName` variable, I've tried to normalize all the plugins on a specific way of doing this to avoid some edge case bugs I've previously run into. Take a look at the example in the [Aliyun plugin](https://github.com/dwydler/Posh-ACME/blob/d799be558d759d06ea2fb25224124e178b71214f/Posh-ACME/Plugins/Aliyun.ps1#L29-L31) and keep in mind that it's possible for the record name and the zone name to be equivalent when using a DnsAlias.

**Comment by rmbolger** [comment]
> Originally, I am following the variant you described. From my point of view there are two potential sources of error. So i decid for the variable CoreNetworksApiRoot as PluginArgument. So the change only has to be made at one point. What do you think about?

When you say two potential sources of error, do you mean it's possible to typo the URL in the plugin's code? While that's technically true, even the most basic publish/unpublish testing would identify them before pushing a release based on the code. But if you force a bunch of users to all input that value separately, they are more likely to individually mess it up.

Being a parameter with a default value is basically the best of both worlds. It will work without user intervention until CoreNetworks ever changes the URL. If they add a non-beta URL and remove the beta URL without warning, users will break until they update their plugin args with the updated URL. But what I'd guess is more likely is that they'll publish a non-beta URL and have it working side-by-side with the beta URL for a while before removing the beta URL. That gives "us" time to update the plugin with the new default value. Then users just have to update the module and they'll be fixed if the beta URL goes away.

**Comment by rmbolger** [comment]
Congrats on the plugin! This should be available in the next release.
