### ISSUE TITLE
New Certificate Requests still have the expiring Intermediate Certificate R3

### ISSUE THREAD

**Issue by seanomat** [rmbolger/Posh-ACME#383]
I just requested a new certificate, and when imported into the computer store, it still shows the R3 and DST Root and intermediate Certificates in it's chain, that are expiring end of this this month.
Am I doing something wrong or is this a bug?
I would have expected LetsEncrypt to always use the newest Certificate to sign my request.

**Comment by rmbolger** [comment]
Hey @seanomat. You're not doing anything wrong. Unfortunately, it's also not a bug. This is a symptom of how Windows currently chooses to build the trust chain for Let's Encrypt certificates.

The underlying cause is that there are multiple versions of the R3 issuing certificate. There's the one you're seeing that was issued by DST and expires at the end of the month and there's the one issued by Let's Encrypt's own ISRG root CA that doesn't expire until 2025. They're both backed by the same private key which means they're both valid parents for your leaf certificate. The reason Windows is choosing the expiring DST one is because its *start* date is more recent than the ISRG one.

We've been told by various community members and Microsoft that Windows will just flip over to the ISRG issued R3 as soon as the DST issued one expires. But there's no real way to test that in advance. The best I've been able to do is set the server's clock forward to October first and check again. But this seems to require either tweaking the SSL binding in IIS or just rebooting the server for it to take effect.

@webprofusion-chrisc has done a bunch more testing than I have on this topic and has a nice community forum post if you want some additional info.
https://community.certifytheweb.com/t/upcoming-expiry-of-dst-root-ca-x3-and-r3-intermediate-for-lets-encrypt/1480

His post talks about disabling the expiring R3 in order to force Windows to use the newer one prior to the expiration. But on the 2019 servers I've been testing against with Posh-ACME, the expiring copy of R3 doesn't even exist in the local computer's cert store that I can find. Oddly on the 2022 servers I've tested on, they also don't have any R3 certs in the local computer's cert store, but they serve the ISRG issued R3 by default. So it seems like this is ultimately going to be something that is OS specific to a certain extent.

**Comment by seanomat** [comment]
Thank you so much for your comment! You confirm my suspicion, that this is more or less just a display problem.
I was in a panic yesterday, since I missed to get a new certificate on time, and installed the seemingly faulty certificate anyway. Since it is not really mission critical I will follow webprofusion's advice and "wait and see".

**Comment by webprofusion-chrisc** [comment]
One trick I like is to make the old R3 untrusted (which is also easy to undo):
- Open certlm.msc, expand Untrusted Certificates > Certificates, and Intermediate Certification Authorities > Certificates
- locate "R3 Issued by DST Root CA X3" (**not** the one issued by ISRG Root X1). Drag it from intermediate to untrusted. 
- optionally, reboot.

**Comment by webprofusion-chrisc** [comment]
I have found it will occasionally start working on its own (after making this change), no idea what the trigger for that is, so I generally suggest rebooting. Likewise with the normal expiry of R3 (no intervention) I did have to reboot - I could have been testing incorrectly a it's tricky to get the timing right (e.g. clock tick over to new expired time frame).

I also found that the LocalUser CA Store for Local System also had the intermediate, which is why untrusting the cert instead of just deleting it was necessary. You can see this by using psexec to run cmd as system, then open certmgr.msc, but yes, there are probably other magical ways it will re-instate a deleted R3 (until that one expires).

The biggest source of confusion for me was I assumed because I stored a PFX that was Leaf > R3 > ISRG Root X1 that's the chain I'd get, when in fact windows ignores all that (it does store the new R3 etc, it just doesn't use it for it's served chain and builds its own preferred chain instead).

**Comment by rmbolger** [comment]
Ooh, you probably hit on something with the System account's CurrentUser store. Intuitively, you'd think it wouldn't need one being System and all. But from an OS perspective, the System account is just another user, so of course it has its own store. So when it builds a chain and pulls down whatever intermediates it needs, they end up there rather than the LocalMachine store...just like what happens when you visit a secure website from a normal user account.

Need to find more time to test this stuff before next Wednesday.

**Comment by rmbolger** [comment]
Confirmed. Leaving the LocalMachine\CA store alone (which didn't contain anything LE related on my 2019 box) and focusing on the System's CurrentUser\CA store definitely made it possible to reliably switch back and forth between having IIS serve the DST R3 and the ISRG R3. As you had previously mentioned, moving the DST R3 into the CurrentUser\Disallowed store and then either rebooting or tweaking the site binding in IIS (like toggling HTTP/2 support off and then back on again) causes it to re-build the necessary chain in CurrentUser\CA. The ISRG R3 gets automatically downloaded and stored in LocalMachine\CA which then shows up in CurrentUser\CA as well on my 2019 box.

I saw you posted various CLI ways to do the DST R3 disable on the system account. Importing this registry file should work as well.
[Disable-DST-R3-for-SYSTEM.reg.txt](https://github.com/rmbolger/Posh-ACME/files/7208474/Disable-DST-R3-for-SYSTEM.reg.txt)

Now to find a benign way to tweak the IIS binding programmatically. I also need to test whether having multiple sites with multiple bindings requires tweaking on all of them or just one.

**Comment by webprofusion-chrisc** [comment]
Cool, I actually didn't find that changing bindings always made a difference, not sure if it's worth scripting that or not.

**Comment by webprofusion-chrisc** [comment]
Also interesting is that ISRG Root X1 is not installed by default on a fresh copy of Server 2022 (and azure anyway), and you'd think it would be..

**Comment by rmbolger** [comment]
I think this goes back to that community thread where people were talking about how Windows does lazy loading of certs on demand. A 2022 box I just built that has done nothing but run Windows Update doesn't have ISRG Root X1 or even DST Root CA X3 in Trusted Roots. But the first time I launch Edge and it loads all that News garbage homepage stuff, something in there is using an LE cert and all of a sudden DST Root CA X3 is now in Trusted Roots (among a few others that weren't there previously). Though interestingly, nothing got added to the Intermediates.

**Comment by rmbolger** [comment]
Bonus info. While you only need to Disallow the DST R3 in order to force Windows to serve a chain with the ISRG R3, it's only the short non-Android compatible chain. But you can make it serve the longer/default Android compatible chain by adding the cross-signed ISRG Root X1 cert into LocalMachine\CA. You can explicitly add the ISRG R3 cert as well, but if not it'll get pulled in automatically.

**Comment by webprofusion-chrisc** [comment]
Ha, yeah, to be honest I've lost track of all the different things I've tried and the resulting outcomes but yes, it's difficult on Windows as you need to decide for the whole server whether you want the android compatible chain or not, then you need to mess around with adding or deleting the various versions of the roots/intermediates. 

On linux your chain is per website and pretty much controlled by the acme client that generates the chain pem, on windows it's just what Windows decides is the most valid chain based on the paths it can see. 

Then there is also Windows Client vs Windows Server, as they are both trying to verify based on their own trust stores (the server chain may make no difference in some cases, I don't entirely know). Meanwhile Firefox will do it's own thing as well (again building it's own chain from it's own trust store).

**Comment by rmbolger** [comment]
It's kind of a mess compounded by the fact that behavior is not well documented and seems to vary between OS versions and even patch levels.
