### ISSUE TITLE
Errors with Digicert ACME endpoint

### ISSUE THREAD

**Issue by Stan-Tastic** [rmbolger/Posh-ACME#394]
Hi,
I'm trying to use posh-acme with Digicert, and I've run into significant issue - Digicert seems to only accept POST requests, and for GET it just says "HTTP 405".

I had this issue before with win-acme, but the author pointed to its PostAsGet option (https://www.win-acme.com/reference/settings#postasget), and using it solved the problem. Unfortunately, I don't see that option in posh-acme. If it doesn't exist, is this a huge problem to implement it?

And I also asked Digicert if they can fix it on their side.

**Comment by webprofusion-chrisc** [comment]
Alternatively, perhaps Digicert could update their implementation, they make something like $200M a year so they can probably find someone to update their code.

**Comment by rmbolger** [comment]
Yeah, looks like you might have gotten the non modified version for some reason. I pushed another commit to the branch that shows a warning about being in the dev build when you run `Get-PAServer`. Try downloading it again and running `Get-PAServer` to make sure you're on the right copy.

**Comment by rmbolger** [comment]
Well, boo. There's clearly still a code path somewhere that's trying to refresh the account details. I'm also not seeing any Verbose logs in there. Can you try again making sure to run the command with the `-Verbose` switch. Also, post the (sanitized) actual command you ran.

**Comment by rmbolger** [comment]
Ooh, I think I found the rogue refresh and pushed an update to the branch to remove it. Try again (and also with the Verbose switch and a copy of the command).

**Comment by rmbolger** [comment]
That pretty much confirms my suspicion about the account endpoint being the main issue. The call that's failing now is the `Set-PAAccount` call trying to update the email address associated with the account. You *shouldn't* need that call since you already created the account with the proper email address in the `New-PAAccount` call earlier. But it does mean Digicert doesn't currently support changing the account email once it's set at creation time (at least not via ACME).

So if you go straight from `New-PAAccount` to either `New-PACertificate` or `New-PAOrder`, you should be ok.

**Comment by Stan-Tastic** [comment]
You're right! That seems to do the trick, it works now.

I have a meeting with Digicert's ACME team in about 2 hours, anything you'd like me to discuss with them? :-)

**Comment by rmbolger** [comment]
Doh, looks like I might be a bit late. But mostly just ask them what the deal is with being able to query or send updates to account endpoints.

**Comment by Stan-Tastic** [comment]
I actually did, Digicert is investigating this now.

wt., 2 lis 2021 o 16:36 Ryan Bolger ***@***.***> napisał(a):

**Comment by rmbolger** [comment]
Hey @Stan-Tastic, did you ever get any updates on the issue from Digicert?

**Comment by Stan-Tastic** [comment]
Terribly sorry, I forgot to update the thread. Here's what Digicert has to say:

_1.	POSH-acme client mainline doesn’t work, however following branch (sslcom-compat) works with digicert acme service.
2.	Digicert acme service does not support updating of account info like email. ( Users can create a new account / avoid updating of email )
3.	Digicert acme service does not support Post-As-Get method for account and order objects._

I don't know ACME specs enough to say if this is within-spec or not, not sure about (3). It makes sense that I can't update account info from here, as the account info is "static" (defined in contract with Digicert, this is not an open ACME endpoint).

**Comment by rmbolger** [comment]
> 2. Digicert acme service does not support updating of account info like email. ( Users can create a new account / avoid updating of email )

This is annoying, but technically allowed by the spec and shouldn't generally affect client compatibility other than throwing errors if the user tries to update account info.

> 3. Digicert acme service does not support Post-As-Get method for account and order objects.

This is the main one that messes with things and totally violates the spec as I understand it. There's a lot of "MUST" language in the POST-as-GET section of the spec. Their statement is also inaccurate for order objects. They *do* support POST-as-GET for order objects or else the sslcom-compat branch wouldn't work either since the only modifications I made are preventing account object refreshes.

In any case, I haven't had much traction with ssl.com either. So realistically, I'm going to need to find a usable workaround for both. It will probably involve a switch/flag on the account object config to tell the module whether it's allowed to do account level refreshes. There's one other thing the spec allows for that might work as an alternative to a direct account refresh that I was going to test first though. If I get it working with ssl.com, I'll let you know and you can try it against digitcert as well.

**Comment by rmbolger** [comment]
Hey @Stan-Tastic. I just pushed an update to the sslcom-compat branch that changes how the account refreshes are queried that fixes compatibility with ssl.com and may also fix it for DigiCert. Do you have any time to test it for me? Ultimately, I just need you to run the following from an existing DigiCert account context, verify it doesn't throw errors, and ideally post the output.

```
$DebugPreference = 'Continue'
Get-PAAccount -Refresh
```

**Comment by rmbolger** [comment]
The fix is now live in 4.14.0
