### ISSUE TITLE
Support providing access tokens to the Azure provider

### ISSUE THREAD

**Issue by perbergland** [rmbolger/Posh-ACME#40]
In support of Managed Service Identities and generally when you'd rather not create a service principal, I'd like to see support for sending in an access token to the provider instead of tenant and credentials. 

I will be sending in a PR for this based on my fork at https://github.com/bokio/Posh-ACME when I've verified that it works and we can have discussions in the PR about the implementation.

**Comment by rmbolger** [comment]
Sounds good. More options are always welcome. The service principal did seem pretty cumbersome when I was originally writing it.

Based on the work you've already done, I'd suggest a minor tweak to how the function parameters work by using parameter sets to let PowerShell do more of the validation work for you. Rather than adding an additional parameter and making the Tenant/Credential non-mandatory, you can split the Tenant/Credential and ProvidedToken into different parameter sets where both are mandatory depending on which you use. For example:

```powershell
    param(
        [Parameter(Mandatory,Position=0)]
        [string]$RecordName,
        [Parameter(Mandatory,Position=1)]
        [string]$TxtValue,
        [Parameter(Mandatory,Position=2)]
        [string]$AZSubscriptionId,
        [Parameter(ParameterSetName='SvcPrincipal',Mandatory,Position=3)]
        [string]$AZTenantId,
        [Parameter(ParameterSetName='SvcPrincipal',Mandatory,Position=4)]
        [pscredential]$AZAppCred,
        [Parameter(ParameterSetName='Token',Mandatory,Position=3)]
        [string]$AZProvidedToken,
        [Parameter(ValueFromRemainingArguments)]
        $ExtraParams
    )
```

Then you can replace a lot of the code checking for valid arguments with a simple check against the parameter set like this.

```powershell
if ('SvcPrincipal' -eq $PSCmdlet.ParameterSetName) {
    # do stuff with $AZTenantId and $AZAppCred
} else {
    # do stuff with $AZProvidedToken
}
```

You can do the same thing with the dependent functions like `Connect-AZTenant`.

**Comment by perbergland** [comment]
#42 created

**Comment by rmbolger** [comment]
And merged. Thanks again for this.
