### ISSUE TITLE
Creating a certificate with an 'ec-256' key length uses the SHA384 hash algorithm

### ISSUE THREAD

**Issue by plrusek** [rmbolger/Posh-ACME#400]
I'm using New-PACertificate to create a certificate with an ECDSA key, ec-256 length. As stated in the comments of multiple source files, like New-PAAccount or New-Jws, an appropriate hash algorithm is set based on the key length. SHA256 for key length 256, SHA384 for key length 384 and SHA512 for key length 521.

In my specific case, I'm looking to create a certificate with the length 256 and the SHA256 hash algorithm. It creates the certificate successfully, however the hash algorithm is SHA384 instead. So far I'm looking where in the source files this problem is occuring but everything seems to be set correctly - the account's $alg value is ES256.

![image](https://user-images.githubusercontent.com/18425248/139838897-eecb0819-d58c-4167-9317-acc947d767a0.png)

**Comment by rmbolger** [comment]
Hi, @plrusek. The signature algorithm in the certificate request (CSR) that gets sent to the ACME server is set in [Private\New-Csr.ps1](https://github.com/rmbolger/Posh-ACME/blob/main/Posh-ACME/Private/New-Csr.ps1). As you've seen, it gets set based on the size of the key for EC based keys. But that CSR is as much control as a client gets over the final certificate. The ACME server generates the signed certificate based on its own code and the client can't really control how it does that.

To be honest, I'm not sure why LE's ACME server would be changing the signature algorithm from what's in the request. But I plan on asking about it in the community forums to maybe find out.

**Comment by rmbolger** [comment]
To follow up, this appears to be just how certificate signing works.

https://community.letsencrypt.org/t/question-re-signature-algorithms/164588

**Comment by plrusek** [comment]
Thank you for following up on the matter and asking the question on LE forums. 

In essence then, it wouldn't be possible for me to create a staging certificate with the sha256 hash algorithm due to issuing CA - E1.
 
The device I'm working with that allows me to upload my own certificate for it's web config site is very picky sadly. Demands this in specific:
"TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256_P256 private key and certificate."

And of course there's a limit to how many production certificates I can create. Although I'm still kinda confused on why the sha256RSA algorithm is being used on the production environment. I've created certificates with RSA keys before and yes, the R3 being the issuing CA made sense there (both staging and production), but how does it here?

**Comment by rmbolger** [comment]
May I ask what device you're working with? And is there any online documentation?

> TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256_P256

This string looks like a TLS cipher suite which would be part of a web server's configuration rather than something that is related to the actual certificate being served. Is the cert actually being rejected by the device with this message? I'm wondering if it's just a bad error message and there's something else wrong with the cert that it doesn't like...such as being a staging cert it doesn't trust.

**Comment by plrusek** [comment]
The issue might very well be with it being a staging cert, as I haven't tried it with a production cert yet.

The cert is being rejected by the device's web config, yes, with this error basically saying "Wrong file, only accepts [...]".

The device is a PDU by Aten, PE8202G. I've already been in talks with the support, just takes some time. There's very little documentation about the certificate, only how to upload one from the device manual.

**Comment by rmbolger** [comment]
A production cert might help. Though the docs don't mention anything about being able to update a trust store and they imply a self-signed cert will work just as well.  Have you tried uploading a custom-made self-signed cert by any chance?

You might also try an RSA cert rather than an EC cert since they tend to be more compatible with stuff.

Also, have you been selecting `cert.cer` or `fullchain.cer` to upload for the certificate file? Whichever one you've been using, you might try the other. Some things want chains included and others don't. And some really weird things want the cert + chain + root which you'd have to download and create your own copy of.

**Comment by plrusek** [comment]
I managed to upload my own created self-signed certificate, made with X509Certificate2 classes and methods. I took a glance at the default self-signed certficate of the device and managed to recreate the properties of it. I saved it as .pfx and extracted the .crt and .key files using openssl pkcs12 commands.

It's hash algorithm must be sha256ECDSA. No RSA allowed here - it rejects certificates with RSA keys as well. So much for compatibility.

Oh, also there was no way making that LE signed certificate work with the device, staging or production. It refused fullchain.cer as well. I suppose it's just really picky. 

It sucks because the self-signed certificate solution is not ideal for me... no more ideas though, if the LE certificate will always have sha384ECDSA on staging and sha256RSA on production then I cannot use those certificates with this device.

**Comment by plrusek** [comment]
I just got word from Atne support that they expect only self-signed certificates to be created and uploaded on the device. Well... that's that then.

**Comment by rmbolger** [comment]
There are a few other public CAs offering free ACME certs that you might try as well just to see if they happen to use a signature algorithm that works with the device. BuyPass is the easiest because it doesn't require external account binding like LE. ZeroSSL you have to setup an account on their website first and generate external account binding information to use with `New-PAAccount`. SSL.com technically doesn't work with Posh-ACME yet because they're not implementing the ACME protocol quite right.

https://poshac.me/docs/v4/Guides/ACME-CA-Comparison/

**Comment by plrusek** [comment]
Alright, thanks for all the help and suggestions. I think my fight has to continue with the customer support for now.

**Comment by plrusek** [comment]
I was giving ZeroSSL a try (created an account there) but New-PACertificate throws this:
`New-PACertificate : The current ACME server requires external account credentials to create a new ACME account. Please
run New-PAAccount with the ExtAcctKID and ExtAcctHMACKey parameters.`

How am I supposed to pass these two things down to New-PACertificate, since it's the one calling New-PAAccount? Also I don't really know what these two things are - I have an API key that ZeroSSL provides in the Developer tab in their website but that doesn't seem to be it, judging by the name...

**Comment by plrusek** [comment]
I was giving ZeroSSL a try and using New-PACertificate just like with Let's Encrypt. How do I pass down the EAB credentials down to New-PACertificate, since it's the one calling New-PAAccount?

**Comment by rmbolger** [comment]
Here's a doc on EAB with the basics:
https://poshac.me/docs/v4/Guides/External-Account-Binding/

The short version is that you have to explicitly create the account first with `New-PAAccount` and then you can call `New-PACertificate` and it will use that existing account (as long as the account related parameters like AccountKeySize don't differ).

That positional parameter error is a weird one I haven't seen before. Weirder that it just went away without changing anything. I'd guess maybe there was a `+` in one of the tokens/keys that didn't get interpreted as a string when entered directly on the command line instead of being passed by a variable?
