### ISSUE TITLE
Cert Renewal Skip messages / output

### ISSUE THREAD

**Issue by StuHare** [rmbolger/Posh-ACME#405]
Hi @rmbolger 

I have expanded the automation using PoshAcme and Azure DevOps to complete installing the requested certificates to both KeyVault and Windows IIS servers.

After completing renewal testing and removing the -force command from New-PACertificate command I hit some issues with renewals.

In summary when the renewal occurs on the daily schedule and the certificate is not due for renewal yet, the task/script executes successfully in devops and proceeds to the next task to install the certificate. This ultimately fails as the certificate cannot be installed in the target store as it already exists.

Ideally it would be good to have condition in the yaml script that looks for response such as a Skipped message, and prevents the next install task from running. 

Judging by the output the following warning is thrown when the certificate does not require renewing:

`WARNING: This certificate order has already been completed. Use -Force to overwrite the current certificate.`

Instead of the job saying it completed successfully is it possible to throw a message or set a variable to say the renewal / order has been skipped?

If not what do you think is the best approach?

I am trying to avoid updating your existing script files.

**Comment by rmbolger** [comment]
Hey Stu, welcome back. The specific warning you're getting implies that you're calling `New-PACertificate` directly for renewals instead of `Submit-Renewal`. The latter would give a warning such as:

```
WARNING: Order 'example.com' is not recommended for renewal yet. Use -Force to override.
```

However, if I were you I'd avoid conditioning on the log outputs and instead condition on the function's main output object. Both `New-PACertificate` and `Submit-Renewal` will only output a certificate object if a new one was actually created as part of the command. So assuming the function completes without any other errors, you can safely assume the order was skipped if the output is `$null`.

I'm not exactly sure if this is feasible in the DevOps pipeline you've got setup, but this is how it might work in a standalone script:

```powershell
# This should work for calls to both New-PACertificate and Submit-Renewal
# Though depending on how you call Submit-Renewal, you may get more than 
# one cert output object if you're renewing multiple orders
try {
    if ($cert = New-PACertificate example.com) {
        # deploy the new cert using details in $cert
    } else {
        # not ready for renewal yet
    }
} catch {
    # there was an error
}
```

**Comment by StuHare** [comment]
Thanks for the swift response as always.

Good point on the script that's called. Maybe some logic is required to check if an order exists, then if it does, call Submit-Renewal instead. 

Ill give your suggestion a try and if not try the Submit-renewal option.
