### ISSUE TITLE
Validation says incorrect record, but shows correct record [AcmeDNS]

### ISSUE THREAD

**Issue by TomAafloen** [rmbolger/Posh-ACME#409]
Hello!

When I try to validate my domain during a **New-PACertificate** "workflow" using AcmeDNS, I get this error:

![image](https://user-images.githubusercontent.com/29425904/146574669-88907477-b613-4b13-9379-9c9f730d01ed.png)

As you can see, the record **found** is the same as the record I was asked to **create**, but is says incorrect?

One thing I noticed is that it says to create a **CNAME** record, but appears to be looking for a **TXT** record. 

But I tested and it did not work with either record type.

I have used this method for a long time without issues.

**Comment by rmbolger** [comment]
Hi @TomAafloen, thanks for reaching out. AcmeDns is a bit different than a typical DNS provider because it relies on redirecting the TXT record query from Let's Encrypt (or other ACME CA) to the AcmeDns server. It conceptually works like this:

- **Let's Encrypt:** Show me TXT records for `_acme-challenge.example.se`
- **Your DNS:** I don't have TXT for that name, but I have this CNAME pointing to `d6be46c2-a96e-4597-821e-ddfe7f46bbea.auth.acme-dns.io`. Go find that instead.
- **Let's Encrypt:** Show me TXT records for `d6be46c2-a96e-4597-821e-ddfe7f46bbea.auth.acme-dns.io`
- **AcmeDns Server:** Here you go

So when the plugin prompts you to create a CNAME and not a TXT record, that's not a mistake. If you created a TXT record with the value `d6be46c2-a96e-4597-821e-ddfe7f46bbea.auth.acme-dns.io`, delete it and create a CNAME instead.

The nice thing about this setup is that the prompt to create the CNAME only needs to happen once. When you eventually renew, the plugin will update the TXT record value with AcmeDns and you don't have to modify the CNAME record because the AcmeDns FQDN doesn't change.

**Comment by TomAafloen** [comment]
Hi, and thanks for the quick response!

As I wrote in my original question, I tried both TXT and CNAME, and it did not work with either record type (even though it showed the correct record). I tried both record type multiple times. 

But when I tried today the CNAME record worked!

It could either be multiple user errors, or maybe a temporary backend error at Acme-DNS?

Regardless, you can close this issue now.

Thanks again for your support and great tool!

**Comment by rmbolger** [comment]
It's possible were running into a DNS replication delay the first time you tried the CNAME. Like, even though you had created it, the change hadn't been propagated to the DNS server being queried by Let's Encrypt by the time it tried to validate.

Now that it's there and working, the nice thing about AcmeDns is that you don't have to worry about those delays anymore unless something goes wrong with the AcmeDns instance and you end up needing to change the CNAME after re-registering. Glad to hear you got things sorted out.
