### ISSUE TITLE
GCloudDns Issue - Unable to find type [Org.BouncyCastle.Crypto.AsymmetricCipherKeyPair]

### ISSUE THREAD

**Issue by darrengoulden** [rmbolger/Posh-ACME#41]
Any advice on how I can troubleshoot this? Tried both stable and dev versions.

```
PS C:\Users\Administrator> New-PACertificate darren.gdn -AcceptTOS -Contact xxxx@darren.gdn -DnsPlugin GCloud -PluginA
rgs @{GCKeyFile='C:\Certs\xxxxxxxxxxxxx.json'}
Connect-GCloudDns : Unable to find type [Org.BouncyCastle.Crypto.AsymmetricCipherKeyPair].
At C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\2.3.0\DnsPlugins\GCloud.ps1:18 char:5
+     Connect-GCloudDns $GCKeyFile $GCKeyObj
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Org.BouncyCastl...icCipherKeyPair:TypeName) [Connect-GCloudDns], Runt
   imeException
    + FullyQualifiedErrorId : TypeNotFound,Connect-GCloudDns

PS C:\Users\Administrator>
```

**Comment by rmbolger** [comment]
This type of error happens when PowerShell can't load the BouncyCastle DLL properly during the module import. The problem usually seems to be related to the .NET Framework version installed. You need .NET 4.7.1 or better for everything to work smoothly.

The easiest way to check what version you have, is run this registry query:

```powershell
gci 'HKLM:SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full\' | gpv -Name Release
```

The value returned is the build number of the .NET release installed on the system. For .NET 4.7.1, the value must be **461308** or higher. If it's less, you need to upgrade the framework.

**Comment by darrengoulden** [comment]
That sorted it, sorry it was a new install of Server 2016, thanks

**Comment by rmbolger** [comment]
No problem. Glad I could help.
