### ISSUE TITLE
Order computername.domain.de is expired. Skipping server refresh.

### ISSUE THREAD

**Issue by dwydler** [rmbolger/Posh-ACME#410]
On 21th Nov 2021 i write a script, which retrieved a SSL certificate from Lets Encrypt (Production). At this point Posh-ACME 4.9.0 was installed.  I use the CoreNetworks plugin. 

This time the script ran into an error:
```
DEBUG: Loading PAOrder list from disk
DEBUG: Exporting plugin args for order 'computername.domain.de' with plugins CoreNetworks
DEBUG: Loading PAOrder list from disk
ConvertTo-SecureString : Schlüssel ist im angegebenen Status nicht gültig.
In C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\4.9.0\Public\Get-PAPluginArgs.ps1:58 Zeichen:70
+ ... prop.Value.user,($prop.Value.pass | ConvertTo-SecureString @encParam)
+                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [ConvertTo-SecureString], CryptographicException
    + FullyQualifiedErrorId : ImportSecureString_InvalidArgument_CryptographicError,Microsoft.PowerShell.Commands.ConvertToSecureStringCommand
 
2021-12-18 13:51:04  - Error   - 	Das Argument kann nicht verarbeitet werden, da der Wert des Arguments "password" NULL ist. Ändern Sie den Wert des Arguments "password" in einen Wert ungleich NULL. 

Export-PluginArgs : Das Argument kann nicht verarbeitet werden, da der Wert des Arguments "password" NULL ist. Ändern Sie den Wert des Arguments "password" in einen Wert ungleich NULL.
In C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\4.9.0\Public\Set-PAOrder.ps1:136 Zeichen:17
+ ...               Export-PluginArgs -Order $order -PluginArgs $PluginArgs
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Export-PluginArgs], PSArgumentNullException
    + FullyQualifiedErrorId : PSArgumentNullException,Export-PluginArgs
```
Sorry that the messages are in German.

After that, I started the analysis. My workaround is to delete the Order manually over the Powershell:
`Remove-PAOrder -MainDomain "computername.domain.de". `

Now I've started my PowerShell script again. This time there was no error and a new Lets Encrypt certificate was obtained.
The same error happend if Posh-ACME is updated to the newst version.

So can you explain the behavior?

Regards,
Daniel

**Comment by rmbolger** [comment]
The primary error with `ConvertTo-SecureString` seems to be the german equivalent of, "Key not valid for use in specified state." This indicates there was a problem trying to decrypt the plugin arguments on the order using the native OS encryption libraries. The encryption keys are tied to both the specific Windows machine and user that created them. Usually when this happens, it's because you've either moved the Posh-ACME config to a different Windows machine or you're referencing the Posh-ACME config from a different user than it was originally created with. This might happen if you got the initial cert with your personal account and then created a scheduled task for renewals that runs as a different user.

Assuming that's the case, you have a couple options for preventing it in the future.

- Always run Posh-ACME as the same user from the same machine. Or if you need to move it to a different context, re-configure the plugin args for each order using `Set-PAOrder -Plugin CoreNetworks -PluginArgs @{blah}` in the new context after migration.
- Enable the alternative plugin encryption option on the associated account using `Set-PAAccount -UseAltPluginEncryption`. This saves a non-OS-specific encryption key to the account and uses that instead of the OS native keys.

**Comment by dwydler** [comment]
> The primary error with ConvertTo-SecureString seems to be the german equivalent of, "Key not valid for use in specified state." 

That could get there. 

> Always run Posh-ACME as the same user from the same machine. 

Both are still given. I run the script all times (when the error was issued and afterwards) on the same machine with the same user account - 100 percent. That’s why I’m irritated and opend this issue.

**Comment by dwydler** [comment]
> Did you have any OS upgrades between then and now like going from Windows 10 to Windows 11?

Unfortunately, no. It is a Windows Server 2012R2 Standard. Only the monthly Microsoft updates were installed at the end of November. Otherwise no changes.

I just see that I may not have posted the important debug issue. Follow lines are shown before all other output, that i posted in the initial thread:
```
DEBUG: Updated nonce: 0002md_o-CzLWap_CyllqA2eLEg9h5JmVnCN_Y8sXoec_-U
DEBUG: Loading PAAccount list from disk
DEBUG: Loading PAOrder list from disk
DEBUG: Order 'computername.domain.de' is expired. Skipping server refresh.
DEBUG: Loading PAOrder list from disk
DEBUG: Set order params:
```

Perhaps this will give you an idea of the problem?!

**Comment by rmbolger** [comment]
It's hard to tell just from that snippet of the debug output. But there does appear to be an order in your config that is expired. Though, keep in mind there's a difference between the order expiration and the cert expiration.  I believe the order object expires after a week regardless of whether it was successful or not. The debug message is just a note that the module won't be able to check for an updated status from the ACME server because most ACME servers delete expired orders from their database, so the call would likely fail.

Try this out to get a better picture of the orders in your current config and their ability to decrypt plugin args:

```powershell
Get-PAOrder -List | Select Name,MainDomain,@{L='PArgSuccess';E={try{$_|Get-PAPluginArgs -EA Stop}catch{$_.Exception.Message}}}
```

**Comment by dwydler** [comment]
> It's hard to tell just from that snippet of the debug output.

I don't want to post it here because of more or less sensitive data in the output. If you give my an email address i can sent you the whole debug output. 

> Try this out to get a better picture of the orders in your current config and their ability to decrypt plugin args:

I will do next week.

**Comment by rmbolger** [comment]
I don't think I'll need the full debug output. But you can send it to ryan-oss at xyto.cc if you'd like. The root of the problem definitely stems from the module not being able to decrypt the plugin arguments.  The questions I have are more around why. `ConvertTo-SecureString` and `ConvertFrom-SecureString` generally "just work" and the only thing that typically breaks them is changing the context of who's running them or from where.

**Comment by dwydler** [comment]
Here the output of the powershell command.
```
Get-PAOrder -List | Select Name,MainDomain,@{L='PArgSuccess';E={try{$_|Get-PAPluginArgs -EA S
top}catch{$_.Exception.Message}}}

Name          MainDomain    PArgSuccess
----          ----------    -----------
computername.domain.de computername.domain.de {CoreNetworksApiRoot, CoreNetworksCred}
```

What I have to say about it. We have changed the location for the files.
`$env:POSHACME_HOME = "C:\Jobs\posh-acme\vmware-computername-le-zertifikat"`

The contents of the directory are shown below.
```
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       21.11.2021     13:13                LE_PROD
d-----       21.11.2021     13:09                LE_STAGE
...
```
Everything looks correct to me...

**Comment by rmbolger** [comment]
That output looks good and the next renewal for that order should not fail with the same `ConvertTo-SecureString` error. However, is that the output while LE_PROD or LE_STAGE is the active ACME server? Can you run the same command with the other server active as well?

**Comment by dwydler** [comment]
> That output looks good and the next renewal for that order should not fail with the same ConvertTo-SecureString error. 
The error is still the same. I tested it for few minutes again.

> However, is that the output while LE_PROD or LE_STAGE is the active ACME server?
It is the output of the LE_PROD. In the tests I first used LE_STAGE. At some point in the analysis I manually deleted the PA order. To see if a new certificate can then be obtained without any problems. Therefore I have adjusted the behavior with LE_PROD to write this issue.

**Comment by rmbolger** [comment]
> The error is still the same. I tested it for few minutes again.

There's still an error relating to `ConvertTo-SecureString`?

**Comment by dwydler** [comment]
> There's still an error relating to ConvertTo-SecureString?

Unfortunately yes.

**Comment by rmbolger** [comment]
Can you email me the full log and I'll take a look?

**Comment by dwydler** [comment]
> Can you email me the full log and I'll take a look?

Sure. It's on the way.
For the script i need an approval by my superior.

**Comment by rmbolger** [comment]
The log output still makes it seem like there's something wrong with the data in the pluginargs.json file (despite the test I had you run that made it look like things were ok). So we're just going to delete it and have the module to re-create it. Assuming you have your plugin args in a variable called `$pArgs`, run the following.

```powershell
Remove-Item (Join-Path (Get-PAOrder).Folder 'pluginargs.json')
Set-PAOrder -Plugin CoreNetworks -PluginArgs $pArgs
```

Hopefully this should fix the problem and your normal script should work again.

**Comment by dwydler** [comment]
The problem do not occur anymore. Don't ask me what the cause is or was. I can not explain it.
