### ISSUE TITLE
[WebRoot Plugin] Write HttpChallenge to multiple network shares

### ISSUE THREAD

**Issue by ChickenDevs** [rmbolger/Posh-ACME#411]
We are using a load balancer setup with a single certificate and we don't know which server Let's Encrypt will get. We need to be able to write the http challenge to multiple network shares, to have it available on all servers.

**Comment by rmbolger** [comment]
Hi @ChickenDevs, thanks for reaching out. The most common solution to this sort of configuration is to set up a rule on the load balancer to detect requests to `/.well-known/acme-challenge/*` and always forward them to a specific web server rather than load balancing them.

That said, it probably wouldn't be too hard to tweak the WebRoot plugin so the `WRPath` parameter is capable of taking an array of strings that it would try to copy the challenge file to. I probably won't be able to really look at it until after the holidays though.

**Comment by rmbolger** [comment]
The dev/main branch now has an updated version of the WebRoot plugin that can take multiple paths in the `WRPath` parameter if you'd like to test it.

**Comment by ChickenDevs** [comment]
> The dev/main branch now has an updated version of the WebRoot plugin that can take multiple paths in the `WRPath` parameter if you'd like to test it.

Just tested it in our production environment, works great! Thank you!

**Comment by rmbolger** [comment]
Excellent. It will be included in the next release.
