### ISSUE TITLE
Question about Submit-Renewal

### ISSUE THREAD

**Issue by MichaelAllenMiller** [rmbolger/Posh-ACME#416]
Is it possible to renew a certificate in such a way that it will not prompt end-users to accept the new host key?

![image](https://user-images.githubusercontent.com/1903214/151070227-3ee5746d-abd3-481d-8637-6899f1d76d06.png)

**Comment by MichaelAllenMiller** [comment]
If I'm understanding this correctly, the answer to my question is no. I'm just not sure if I'm understanding it correctly. :)

https://github.com/rmbolger/Posh-ACME/issues/113#issuecomment-526872017

**Comment by rmbolger** [comment]
Hi @MichaelAllenMiller, I can't tell from the screenshot what the client is using as the "Fingerprints" value. Does it match the Thumbprint value from the cert? If so, then you're correct that there is no way to make that the same between renewals.

Also, the client here is connecting using FTPS (FTP-over-SSL) and not SFTP (SSH File Transfer Protocol), right? For FTPS, it seems odd that the client would treat the server certificate the same way it does an SSH host key because they're not really the same and the trust model is definitely different. Certificates are trusted because their issuing/parent CA (or chain of CAs) is trusted. But SSH host keys are usually self-generated on the fly at install time, don't expire, and are rarely changed. So you have to trust on first use or based on pre-knowledge of that key.

**Comment by MichaelAllenMiller** [comment]
Hi @rmbolger , thank you for the quick reply! 

The client is FileZilla (in this case), and the fingerprint matches what I get when I run `ssh-keygen.exe -lf .\cert.key`, but I still have a lot to learn, so I'm not sure what that's called other than a "fingerprint".

The server is ZFTPServer, and the protocol is SFTP (SSH File Transfer).  It sounds like instead of using a certificate from LetsEncrypt, I need to look into generating my own private/public key and using that instead.  Thank you for your help!

**Comment by rmbolger** [comment]
I'm not familiar with the server software. But yeah, it sounds like you just need a public/private keypair and not a full fledged certificate since you're using SSH. I'm also surprised the server software didn't generate one automatically. That said, it is possible to use certs with SSH. It's just not as common.

Thanks for the sponsorship, btw! 🎉
