### ISSUE TITLE
Any ideas on how to store state for a distributed/automated solution?

### ISSUE THREAD

**Issue by perbergland** [rmbolger/Posh-ACME#43]
Currently, the tooling stores all of its state including certificates in a folder in your home directory.
If you want several people or services being enabled to manage the certificates, the contents of that folder needs to be shared somehow.

Do you have any pointers to solutions around this, e.g. by storing/restoring the state in S3/Azure Blob or some other way.

**Comment by rmbolger** [comment]
Currently, the way that the module saves "secure" plugin arguments (`SecureString` and `PSCredential` objects primarily) to disk means the profile is not portable. PowerShell (on Windows) uses [DPAPI](https://msdn.microsoft.com/en-us/library/ms995355.aspx) under the hood to encrypt the secure data using keys that are tied to both the local machine and the current user.  So if you try to copy the Posh-ACME folder to another computer or another user's profile on the same machine, renewals that use plugins with secure data will start failing because the module can't decrypt the plugin arguments. It's fairly easy to fix by just re-running `New-PACertificate` and re-specifying the plugin args from the new location though.

In any case. My original assumption is that the only thing you would need to share around would be the finalized cert/key files if anything. The paths to all of those are included in the output object from successful calls to `New-PACertificate`, `Submit-Renewal`, and `Get-PACertificate`.

**Comment by perbergland** [comment]
Yeah well I was thinking along the lines of using a Windows nanoserver (until the azure dns plugin is supported on non-windows) docker image with [powershell](https://github.com/PowerShell/PowerShell/blob/master/docker/release/windowsservercore/Dockerfile) and then map in a drive (e.g. from an azure storage account) to the container for persistent storage.
I'll see if I ever get to doing this... There are bound to be gotchas for running stuff in nanoserver, of course.

**Comment by rmbolger** [comment]
I haven't done any Nano specific testing with the module. But if I recall correctly, the PowerShell/.NET bits on 2012 R2 based nano weren't sufficient to run it. No clue about 2016 nano. If you do any testing, I'd love to hear about it though.
