### ISSUE TITLE
GoDaddy Find-GDZone function unable to locate zone when using a delegated sub-zone

### ISSUE THREAD

**Issue by n-ber** [rmbolger/Posh-ACME#430]
I'll preface this by saying that this is my first github issue, so please let me know if there's a better way to go about things.

The issue I'm having seems very similar to #254 in that the Find-GDZone function in the GoDaddy plugin cannot locate the zone I'm working with. The domain is not hosted by GoDaddy but I've added authority for it to manage a specific subdomain through the Domain Manager.

Despite the changes that have been implemented as of the last issue, I'm still having some trouble. When I try to query the zone via GoDaddy's API myself it can't find it either. Here's what it returns:
`{"code":"NOT_FOUND","message":"Domain auth.mydomain.com not found for shopper"}`

Here's what I've used to obtain that response:
```
curl -X 'GET' \
  'https://api.godaddy.com/v1/domains/auth.mydomain.com' \
  -H 'accept: application/json' \
  -H 'Authorization: sso-key api-key:api-secret'
```

I've created a quick workaround that resolves the issue by completely bypassing the Find-GDZone function in both Add-DnsTxt and Remove-DnsTxt functions. Still, it would be nice if there was an official solution for this, if this is indeed an issue and not just something on my own end. Here's a snippet from GoDaddy.ps1 to reflect my changes:

   ```
# $RecordName is _acme-challenge.auth.mydomain.com in this case.

 # if (-not ($zone = Find-GDZone $RecordName $headers $apiRoot)) {
#     throw "Unable to find matching zone for $RecordName."
# }
$zone = $RecordName.Substring(($RecordName.IndexOf(".") + 1))
```

Thank you in advance for any help and advice.

**Comment by rmbolger** [comment]
Hey @n-ber, thanks for reaching out. This def seems like a weird limitation in GoDaddy's API (and Web UI). I get the impression they don't really intend for you to delegate sub-domains to them even though it technically seems to work. Like, the My Domains section of the UI won't show it (though it does show delegated apex domains). On my account, I actually have to search for the zone in the DNS Management view in order to manage the records. I also wouldn't be surprised if this doesn't work for deeper sub-zone delegations like `auth.dev.example.com`.

That said, I think I might be able to work around the limitation by querying for the NS records on the zone instead of just the base domain info. Those records should exist on every GoDaddy hosted zone and would confirm the portion of the FQDN that is the zone name. Gimme a bit to tinker and see what I can figure out.

P.S. If you're looking for an alternative free DNS host that can better support sub-zone delegations, give DigitalOcean a try. https://www.digitalocean.com/

**Comment by rmbolger** [comment]
I pushed an updated version of the plugin to the main/dev branch. Can you give it a test for me? It seems to work for me. I just want a second set of eyes before I include it in a new release.

**Comment by n-ber** [comment]
I've tried it out and it looks like it's working great. It isn't getting stuck on locating the zone anymore and I'm able to successfully generate a cert.

Thank you so much for the quick response and fix!

**Comment by rmbolger** [comment]
Excellent. I'll try to get this out in an official release soon.

**Comment by rmbolger** [comment]
This is now live in 4.14.0
