### ISSUE TITLE
Multiple users creating certificates using multiple PAAccounts

### ISSUE THREAD

**Issue by pontuskindh** [rmbolger/Posh-ACME#433]
Hello,
We have set the POSHACME_HOME env variable and as a result of that we end up with an issue that when multiple users are creating certificates sometimes they order a certificate on the wrong PAAccount because another user has Set-PAAccount somewhere in the middle of the other users process.
Is there any way around this maybe you can set another env variable per user that points to their own current-account.txt file?

BR

**Comment by rmbolger** [comment]
Hi @pontuskindh, thanks for reaching out. To be honest, the Posh-ACME config isn't really intended to be used by multiple users (particularly not at the same time). That's why it defaults to the per-user local AppData location. The POSHACME_HOME environment variable is already a workaround for folks who want to put the config in a central location. But if you're going to have an ACME account per-user anyway, why not just let that config live in a user-specific folder so there are no conflicts?

Out of curiosity though, if the config is central, why does there need to be an ACME account per user? Why not just one ACME account that everyone uses?

**Comment by pontuskindh** [comment]
Hello @rmbolger ! Thanks for the fast response. 
We are a small team of admins that use posh acme to create LetsEncrypt certificates for our customers.
Each customer has their own PAAccount. And to keep all the customers and their certificates in a central location for all of us to be able to take over from another admin or see what certificates has been created before we use the POSHACME_HOME env var. 

BR

**Comment by rmbolger** [comment]
Sorry for the delayed response. I totally lost track of this issue. Unfortunately, simultaneous use of the same config from different PowerShell sessions isn't really something the module is designed to accommodate.

The best thing I can suggest would probably be to use the existing POSHACME_HOME environment variable and create a separate config location per-customer. You could even create a script to make it easier to switch between customers that would set a new value for the environment variable and force reload the module on the fly.

**Comment by pontuskindh** [comment]
Okey will take a look into it. Thanks for the help!
