### ISSUE TITLE
Has anyone set up something automated around this tooling?

### ISSUE THREAD

**Issue by perbergland** [rmbolger/Posh-ACME#44]
Now that I got my first certificate set up for Azure (this tooling is awesome - it just worked) I want to build something automated around it, e.g. by creating a web service or a VM or something else that can run periodically and refresh certificates and then upload them to Keyvault, app services, wherever needed.

Are there any recipes to follow or advise to be had?

**Comment by rmbolger** [comment]
Unfortunately, there's nothing solid yet. I've deliberately tried to keep this module focused on certificate issuance rather than deployment. But I have started working on a companion module for various deployment scenarios. It's still a pretty early concept though.
https://github.com/rmbolger/Posh-ACME.Deploy

Right now, the idea is that you have a custom deployment function that accepts the pipeline output of `Get-PACertificate` which is the same output that `New-PACertificate` and `Submit-Renewal` give. So in a scheduled task, the command might look something like this.

```powershell
Submit-Renewal | Set-IISCertificate -SiteName 'My Site' -RemoveOldCert
```

Or if you have multiple certs in that profile, you might need to select the one you're working with first.

```powershell
Set-PACertificate site1.example.com; Submit-Renewal | Set-IISCertificate -SiteName 'My Site' -RemoveOldCert
```
