### ISSUE TITLE
Let's Encrypt sends email notifications on orders that have been removed

### ISSUE THREAD

**Issue by stevenvolckaert** [rmbolger/Posh-ACME#450]
I've noticed that Let's Encrypt sends email notifications on orders that have been removed with the `Remove-PAOrder` cmdlet.

The script that does this (which I've written myself) is doing this with the `-Force -ErrorAction SilentlyContinue` options though, so an error might have come by which I haven't noticed.

I was wondering if there is a way to disable the notifications, when a certificate is no longer needed?

Perhaps I should revoke the certificate before removing it?

**Comment by rmbolger** [comment]
Hey @stevenvolckaert. Unfortunately, not. Remove-PAOrder ultimately just deletes the reference to the order from the local config. But it still exists in the CA's database for however long their normal processes would keep it (presumably at least until the order expires) and the ACME protocol doesn't have a supported method to request an order be deleted from the CA. The closest thing would probably be revocation, but revocation is discouraged unless the cert has actually been compromised because it costs additional resources on the CA side to process and host revocation info for.

For Let's Encrypt specifically, I'm not sure revoking would even prevent the expiration notifications. You might want to post on the [community forums](https://community.letsencrypt.org/) asking about that. There's an unsubscribe link in the expiration email, but that's a global unsubscribe for all messages from LE to that email address and lasts for a year with no way to re-subscribe. LE has previously acknowledged that their current email processes need some work.

The other thing you could do is change or disassociate the email address associated with the PAAccount that generated the certificate. But that would also stop or redirect legit warnings for other certs registered from that same account.

```powershell
Set-PAAccount -Contact 'newaddress@example.com'
Set-PAAccount -Contact $null
```

**Comment by stevenvolckaert** [comment]
Hi @rmbolger, and thanks for your thorough explanation.

I've opened a new feature request in the Let's Encrypt community forums: [How can I unsubscribe from certificate expiration notifications for a specific certificate?](https://community.letsencrypt.org/t/how-can-i-unsubscribe-from-certificate-expiration-notifications-for-a-specific-certificate/182973?u=stevenvolckaert).

If I hear any news I'll report back here.

**Comment by webprofusion-chrisc** [comment]
@stevenvolckaert notifications will stop after the cert expires, so just let it expire.

**Comment by rmbolger** [comment]
Good job on the community forum post. It seems the LE admins agree that revocation in your situation is acceptable and it sounds like that would also then avoid the expiration warnings.

https://community.letsencrypt.org/t/how-can-i-unsubscribe-from-certificate-expiration-notifications-for-a-specific-certificate/182973/3?u=rmbolger

**Comment by stevenvolckaert** [comment]
I confirm that in this use case, one should **revoke** the certificate **with reason `cessationOfOperation`**.

See the [Revoking Certificates - Let's Encrypt](https://letsencrypt.org/docs/revoking/#specifying-a-reason-code) page for more information.
