### ISSUE TITLE
GCloud should make the DNS project/zone configurable.

### ISSUE THREAD

**Issue by lukeschlather** [rmbolger/Posh-ACME#451]
In reading your docs I was a little bemused by the instructions to create a custom role - great in principle but in practice I'm not sure the "smaller" role really reduces the scope significantly from DNS Administrator.

However, it is possible to create a hosted zone in a separate project, and only grant your service account access to DNS administrator in that project, which is much more useful. You can even in principle create a hosted zone just for _acme-challenge.example.com and give it access to that.

Incidentally, I am using a service account in a separate project and spent several hours puzzling over why I was getting "403 Forbidden" until I realized that Posh ACME was incorrectly inferring the project from my service account's project and listing hosted zones in that project (rather than the DNS Project which contains my hosted zone.) I think the error messaging here could be better, but also I think explicitly configuring the project and hosted zone (maybe with an option to infer them) would be a better API.

i.e.

```
    $certificate = New-PACertificate -CSRPath $csr_file `
      -Plugin GCloud     `
      -PluginArgs @{GCKeyFile=$serviceAccountFile,GCProject=<myproject>,GCHostedZone=<zone>} `
      -DirectoryURL ZEROSSL_PROD `
      -verbose -debug
```

**Comment by rmbolger** [comment]
Hey @lukeschlather, thanks for the suggestion! I actually had no idea you could do cross-project access like that. It's been a while since I looked at this particular plugin's code, so it's probably due for a refresh anyway. But it seems like it would be pretty straightforward to add an optional project argument. It could plausibly take an array so you could specify multiple projects.

> In reading your docs I was a little bemused by the instructions to create a custom role - great in principle but in practice I'm not sure the "smaller" role really reduces the scope significantly from DNS Administrator.

I mean...it's better than nothing given the options. While compromised credentials would still allow someone malicious to mess up your existing zones, at least they won't be able to create new zones (costing you money) or delete existing zones. Azure has everyone beat in their DNS permissions model except maybe OVH which allows permissions down to the individual record. Though that's pretty cumbersome to make work.

**Comment by rmbolger** [comment]
Hey @lukeschlather, have a look at PR #452 and see if the [updated plugin file](https://github.com/rmbolger/Posh-ACME/blob/ba199ce84f98d6c1c604ee8bddf3c6a99209d6ef/Posh-ACME/Plugins/GCloud.ps1) works for you.

**Comment by rmbolger** [comment]
This is now live in 4.15.0
