### ISSUE TITLE
Conflict with Az.KeyVault module's BouncyCastle library

### ISSUE THREAD

**Issue by 0-0-082** [rmbolger/Posh-ACME#453]
Hi guys, 

I run the powershell script on Azure hosted agent (linux) to generate certificate. I'm having problem with the latest version of POSH-ACME (4.15.0). It appears the latest version somewhat conflicts with Az.KeyVault module 
I get this error message 

'Get-AzKeyVaultCertificate' command was found in the 'Az.KeyVault', but the module could not be loaded.

If I use POSH-ACME 4.14.0, that error does not happen. 

BTW, thanks for the work you guys have done. This module is great.

**Comment by rmbolger** [comment]
Hey @0-0-082, this appears to be a library dependency conflict between Posh-ACME and Az.KeyVault. Both rely on the [BouncyCastle](https://www.bouncycastle.org/csharp/) crypto library. Posh-ACME 4.15.0 upgraded the embedded library version from 1.8.8.2 to 1.9.0, but Az.KeyVault still uses 1.8.8. (which is why it worked previously and apparently a single PowerShell session can't load two different versions of the same library at the same time.

I ran into this a while ago with another Microsoft module that had bundled BouncyCastle and I thought I had worked around the problem by renaming the copy in Posh-ACME to something less generic. But I guess it's not the file name that matters.

At the moment, I don't know of anything I can do except back-rev the version of the library. But that will only fix things until Az.KeyVault upgrades their copy and then it will break again until I match versions again. I'll have to do some research to see if there's anything else I can do to avoid these types of library conflicts between modules.

**Comment by StuHare** [comment]
Having the same issues here.

We have 14 pipelines that all started failing at 0400hrs on Saturday UK time, which seems to coincide with the new release.

     | The 'Get-AzKeyVaultCertificate' command was found in the
     | module 'Az.KeyVault', but the module could not be loaded. For
     | more information, run 'Import-Module Az.KeyVault'.

Running the module & command-let using a new YAML tasks works fine just not in the script.

Is there a workaround we can use for now?

Cheers

**Comment by StuHare** [comment]
> Having the same issues here.
> 
> We have 14 pipelines that all started failing at 0400hrs on Saturday UK time, which seems to coincide with the new release.
> 
> ```
>  | The 'Get-AzKeyVaultCertificate' command was found in the
>  | module 'Az.KeyVault', but the module could not be loaded. For
>  | more information, run 'Import-Module Az.KeyVault'.
> ```
> 
> Running the module & command-let using a new YAML tasks works fine just not in the script.
> 
> Is there a workaround we can use for now?
> 
> Cheers

OK i have resolved by installing version 4.14.0.

Thanks

**Comment by rmbolger** [comment]
Yes, the easiest workaround for now is to limit the module version to v4.14.0. Anything else is going to involve modifying either Posh-ACME or Az.KeyVault.

It should be noted that this only seems to affect PowerShell 6+ (regardless of platform). Windows PowerShell 5.1 apparently silently ignores the conflict and just lets both modules use whichever version was loaded first.

More background info on the problem:
https://devblogs.microsoft.com/powershell/resolving-powershell-module-assembly-dependency-conflicts/
https://stackoverflow.com/a/72509967/75772

Unfortunately, all of the suggested workarounds other than matching library versions with the conflicting module are "non-trivial" and only seem to apply to binary/compiled modules rather than script modules like Posh-ACME.

**Comment by 0-0-082** [comment]
Thanks for the update. :)

I will use 4.14.0 for now.

**Comment by rmbolger** [comment]
I submitted a [feature request](https://github.com/Azure/azure-powershell/issues/19375) to the Azure PowerShell repo to implement one of the workarounds. From what I can tell, they only barely use BouncyCastle in Az.KeyVault to begin with and it's a binary module that can actually use the suggested workaround. We'll see how that goes.

Since the BouncyCastle library is so permissive (MIT variant), it's also possible that I could just embed a forked/customized version of the library in this module that would never conflict with anyone else. But I'm not sure what edge case weirdness I might be opening myself up to by doing that. It also seems a bit sketchy to be publishing a modified version of a crypto module even if the changes are superficial like altering the AssemblyName and possibly root Namespace.

**Comment by webprofusion-chrisc** [comment]
@rmbolger I was looking at bouncycastle recently regarding the variety of variants on nuget and it's already the wild-west (there's not even really an official distro on there), so I'd say it's fine to distribute your own if required, I'm guessing yours wouldn't need to be on nuget anyway. Only thing I'd say from the point of view of Certify The Web (which bundles Posh-ACME for DNS providers) is that we load our version of the dll, not yours, to make our distribution slightly smaller, so namespace changes would probably affect that, but that's not your problem. We don't use the Azure providers because we already have those outside of Posh-ACME.

**Comment by rmbolger** [comment]
Yeah, I recall seeing a variety of BC nuget packages as well. But I def wouldn’t need to add mine there. I did some very brief testing with a forked version this afternoon and found that all I needed to modify was the assembly name in the project and then PS 7.2 would let both modules load without issue. I have no idea how it decides which copy to use considering both use the same namespace though. More thorough testing needed.

It also feels like a more correct solution would be to make a stand-alone BouncyCastle module whose only purpose is to use as a module dependency for other modules instead of every module embedding their own copy. Then you get a bit better dependency management by being able to specify the minimum version necessary for your module. The downside is that you have to convince everyone to use it instead of embedding their own or else you’re back to square one.

**Comment by rmbolger** [comment]
I think I'm going to revert the BouncyCasstle library version change for the time being so it matches Az.KeyVault. This will give me more time to evaluate the alternative workarounds without holding back the folks who need to be using both modules.

**Comment by rmbolger** [comment]
Now live in 4.15.1
