### ISSUE TITLE
Plugin for Active24 (DNS provider from Czech Republic) 

### ISSUE THREAD

**Issue by pastelka** [rmbolger/Posh-ACME#455]
Hi, I have prepared a DNS-1 plugin for DNS provider from Czech Republic - Active24 (www.active24.cz).

[Active24.zip](https://github.com/rmbolger/Posh-ACME/files/9639600/Active24.zip)

**Comment by rmbolger** [comment]
Hi @pastelka. Thanks for the submission! Could you possibly submit this new plugin as a Github pull request instead of just attaching the file to this issue? It will make it easier to review and make changes if necessary.

If you're not familiar with the pull request process, there are a number of tutorials available out there with a quick web search. Here's a good one from AdaFruit:

https://learn.adafruit.com/an-introduction-to-collaborating-with-version-control/submitting-a-pull-request-on-github

**Comment by pastelka** [comment]
Hi @rmbolger, I done it.

**Comment by rmbolger** [comment]
Implemented in PR #456
