### ISSUE TITLE
Manual DNS

### ISSUE THREAD

**Issue by centuryx476** [rmbolger/Posh-ACME#46]
Hello,
Not sure if it is an issue or just how it works now. 
In the previous versions when I will submit a new Cert it will give the "TXT" record value.
I will then submit it to my domain registrar and complete the process.

But now in version 2.4.0 I request a Cert it does not give me the "TXT" record value and just makes the cert. 
Is that suppose to be happening ? 

Thanks

**Comment by rmbolger** [comment]
It depends on how long it has been since the original cert was generated. The challenges that you previously successfully validated have a window of time that they're good for. So if you request a new cert with names that have non-expired validations, you won't have to answer any new challenges for them. But if you add any new names, you'd have to answer challenges for them.

I believe the challenge validations used to be good for 60 days, but maybe a year ago they dropped to 30 days.
