### ISSUE TITLE
Support for multiple PluginArgs

### ISSUE THREAD

**Issue by sevmonster** [rmbolger/Posh-ACME#462]
I am attempting to create a certificate that communicates with two separate Windows DNS servers, each necessitating separate `PluginArgs`. Unless there is something I am missing, it seems that this configuration is not supported, and the order-global `PluginArgs` are splatted to the `Add-DnsTxt` every time. It would be very useful to have each call use a unique hashtable, just like how you can have a list of unique plugins and domains line up with eachother.

For example:
```powershell
New-PACertificate `
  -Domain example.com, *.example.com `
  -Plugin Windows, Windows `
  -PluginArgs @{
    WinServer = 'MyServer1'
    WinCred = (Get-Credentials -Username 'SomeUser')
  }, @{
    WinServer = 'MyServer2'
    WinCred = (Get-Credentials -Username 'SomeOtherUser')
  }
```

**Comment by rmbolger** [comment]
Hi @sevmonster. Thanks for the suggestion! Unfortunately, changing the way `PluginArgs` works to support an array of hashtables instead of a single one would be a pretty significant code change to support. But I don't think it's a common enough use-case to justify that effort. That said, there are a couple ways I can think of to do what you're trying to do without any code changes. 

The first one is a bit hacky and takes advantage of the cached validations on the ACME CA. You would essentially be pulling all of the names that require one set of PluginArgs into their own dummy order and validating those challenges. Then you'd create a second real order that contains the names from both the dummy order and the rest that require the second set of PluginArgs. Since the names from the dummy order will already be valid, the only challenges to validate in the real order will be the ones using the second set of credentials. So something like this:

```powershell
$dummyOrder = @{
    Domain = 'example.com'
    Plugin = 'Windows'
    PluginArgs = @{
        WinServer = 'MyServer1'
        WinCred = (Get-Credential -Username 'SomeUser')
    }
}
New-PACertificate @dummyOrder

$realOrder = @{
    Domain = @('example.com','example.org')
    Plugin = 'Windows'
    PluginArgs = @{
        WinServer = 'MyServer2'
        WinCred = (Get-Credential -Username 'SomeOtherUser')
    }
}
New-PACertificate @realOrder
```

As long as the dummy order is renewed successfully prior to the real order being renewed, everything should work.

The second way is more code but doesn't waste CA resources with extra dummy orders. Instead of using `New-PACertificate` as a single command, you'd build the order and publish the challenges manually using the other public module functions. See [this guide](https://poshac.me/docs/v4/Guides/Custom-Challenge-Validation/) for a deeper explanation. But generally something like this:

```powershell
# this code assumes you've already run Set-PAServer and New-PAAccount

# setup our differing sets of plugin args
$pArgs1 = @{
    WinServer = 'MyServer1'
    WinCred = (Get-Credential -Username 'SomeUser')
}
$pArgs2 = @{
    WinServer = 'MyServer2'
    WinCred = (Get-Credential -Username 'SomeOtherUser')
}

# create the order and grab the authorizations
$domains = 'example.com','example.org'
$order = New-PAOrder $domains
$auths = $order | Get-PAAuthorization

# publish the TXT record using the appropriate credentials for each pending authorization
$pubParams = $auths | ForEach-Object {
    if ($_.DNS01Status -eq 'pending') {
        $pub = @{
            Domain = $_.fqdn
            Account = (Get-PAAccount)
            Token = $_.DNS01Token
            Plugin = 'Windows'
        }
        # adjust the logic here however it makes sense to determine which arg set gets added
        if ($_.fqdn -eq 'example.com') {
            $pub.PluginArgs = $pArgs1
        else {
            $pub.PluginArgs = $pArgs2
        }
        Write-Output $pub
}
$pubParams | ForEach-Object { Publish-Challenge @_ }

# sleep long enough for changes to be live and then send the challenge ACKs
Start-Sleep 120
$auths | ?{ $_.DNS01Status -eq 'pending' } | Select -Expand DNS01Url | Send-ChallengeAck

# wait a bit more for the validation servers to check the records and then re-check your authorizations
Start-Sleep 30
$auths = $order | Get-PAAuthorization
if ($auths | Where-Object { $_.status -ne 'valid' }) {
    # one or more authorizations didn't change to valid status, throw an error or retry
} else {
    # now that our authorizations are all valid, let New-PACertificate pick up where we left off
    New-PACertificate $domains
}
```
