### ISSUE TITLE
posh-acme generate a certificate to customize the generated path?

### ISSUE THREAD

**Issue by uranus829** [rmbolger/Posh-ACME#471]
Can posh-acme generate a certificate to customize the generated path? The default is under %localappdata%, but if you log in with another user in a domain environment, you will not be able to access this path.

**Comment by rmbolger** [comment]
Hi @uranus829. The default config location is intentional because the default encryption used to secure the plugin variables is tied to both the current user and current machine. So even if another domain user could read the files, they couldn't use the saved plugin variables. The private key associated with a cert is also supposed to generally be kept secret and not readily accessible to any user.

However, there are options to work around both of those issues. It's possible to change the root location of the module config using the `POSHACME_HOME` environment variable. There's a more in depth guide about that, [here](https://poshac.me/docs/v4/Guides/Using-an-Alternate-Config-Location/). It also explains how to change the default encryption type for plugin variables so other users can theoretically use the module from the same location. But it all you need is access to the resulting cert files, that's not technically necessary.

**Comment by uranus829** [comment]
Thanks for @rmbolger the reply, what I need to do is nginx calls the certificate file.
1. My purpose is to copy the certificate file to another directory, but the consequence of this is that after the certificate is automatically updated, nginx will not automatically update it.
2. I need to log in to windows with a designated user, and the nginx will point to the certificate to take effect.

**Comment by uranus829** [comment]
> Hi @uranus829. The default config location is intentional because the default encryption used to secure the plugin variables is tied to both the current user and current machine. So even if another domain user could read the files, they couldn't use the saved plugin variables. The private key associated with a cert is also supposed to generally be kept secret and not readily accessible to any user.
> 
> However, there are options to work around both of those issues. It's possible to change the root location of the module config using the `POSHACME_HOME` environment variable. There's a more in depth guide about that, [here](https://poshac.me/docs/v4/Guides/Using-an-Alternate-Config-Location/). It also explains how to change the default encryption type for plugin variables so other users can theoretically use the module from the same location. But it all you need is access to the resulting cert files, that's not technically necessary.

**Comment by uranus829** [comment]
> Hi @uranus829. The default config location is intentional because the default encryption used to secure the plugin variables is tied to both the current user and current machine. So even if another domain user could read the files, they couldn't use the saved plugin variables. The private key associated with a cert is also supposed to generally be kept secret and not readily accessible to any user.
> 
> However, there are options to work around both of those issues. It's possible to change the root location of the module config using the `POSHACME_HOME` environment variable. There's a more in depth guide about that, [here](https://poshac.me/docs/v4/Guides/Using-an-Alternate-Config-Location/). It also explains how to change the default encryption type for plugin variables so other users can theoretically use the module from the same location. But it all you need is access to the resulting cert files, that's not technically necessary.

Thanks for @rmbolger the reply, what I need to do is nginx calls the certificate file.

My purpose is to copy the certificate file to another directory, but the consequence of this is that after the certificate is automatically updated, nginx will not automatically update it.
I need to log in to windows with a designated user, and the nginx will point to the certificate to take effect.

**Comment by rmbolger** [comment]
It sounds like you need to add a couple lines to your renewal script. The first would copy the cert files to wherever they should be for nginx. The second would run whatever command is necessary to reload the nginx config and pick up the cert change. So something like this:

```powershell
if ($cert = Submit-Renewal example.com) {
    Copy-Item $cert.FullChainFile '/path/to/public/cert.pem' -Force
    Copy-Item $cert.KeyFile '/path/to/private/cert.key' -Force
    & service nginx reload
}
```
