### ISSUE TITLE
ErrorAction doesn't seem to be honored

### ISSUE THREAD

**Issue by lazynooblet** [rmbolger/Posh-ACME#499]
I can't seem to be able ot use try {} catch {} statements around the cmdlets.

For example, checking if we have an available PAAccount, (when we dont).

try { $a = Get-PAAccount -ErrorAction Stop}
catch { New-PAAccount }

Results in no caught exception, just a red-text output for "Get-PAAccount : No ACME server configured. Run Set-PAServer first."

Get-PAAccount -ErrorAction SilentlyContinue

Results in red-text to console.

I've tried a few other commands with similar test results.

**Comment by rmbolger** [comment]
Hey @lazynooblet, thanks for reaching out. In this particular case, that "No ACME server configured" is being thrown by *both* `Get-PAAccount` and `New-PAAccount` because you can't do either action without a server configured.

So your try/catch *is* actually catching the first error with `Get-PAAccount`. But then another one is being thrown within your catch block when `New-PAAccount` is called.

**Comment by lazynooblet** [comment]
Yes, you're right, its right there in the text as well. I was implementing Posh-ACME in a rush and now that its up and running I do indeed to Set-PAServer at the beginning of the script.

Thanks for the reply, sorry for the noise.

**Comment by rmbolger** [comment]
No problem. We all occasionally miss stuff that seems obvious in retrospect. Sometimes it just takes another pair of eyes.
