### ISSUE TITLE
How to use with PowerDNS, can't fins DNS-plugin?

### ISSUE THREAD

**Issue by ballou-git** [rmbolger/Posh-ACME#524]
Hi, this looks very good.
But since we use PowerDNS I wonder if this is missing or if I miss some information.
Can you please advice?

**Comment by webprofusion-chrisc** [comment]
If a plugin doesn't exist you generally need to write it and submit a Pull Request for it to be considered for acceptance into the project.

 There are _thousands_ of DNS providers in the world, this project supports the ones under https://github.com/rmbolger/Posh-ACME/tree/main/Posh-ACME/Plugins because those are the ones that have been written or contributed so far.

**Comment by ballou-git** [comment]
Thank you for the quick response.
I'll have to wait and see if this will be added in the future.
I just thought that this would be here already since the PowerDNS is a common setup.

**Comment by rmbolger** [comment]
PowerDNS appears to have limited support for RFC2136 based Dynamic updates which you could plausibly use with the RFC2136 plugin until a PowerDNS specific plugin is written.
https://doc.powerdns.com/authoritative/dnsupdate.html

The main reason no dedicated plugin exists yet is that no one has asked for it until now. It's also a slightly more complicated provider to support because it's self-hosted instead of cloud-hosted which means I'd have to learn how to deploy my own instance unless someone spun up a test instance for me to use.

**Comment by ballou-git** [comment]
Thank you, I think that module wont work for us.
If you have time I can setup a server for you to elaborate with.
I can setup a Rocky Linux latest with latest PowerDNS.

**Comment by rmbolger** [comment]
That would be amazing, @ballou-git, and certainly speed up the implementation of a plugin. The test instance doesn't even have to host real zone data. They can be test zones that no public DNS actually points to.

**Comment by ballou-git** [comment]
This is really great news.
Is there a way I can contact you? Telegram etc?
I have a server up and running.

**Comment by rmbolger** [comment]
You can email me at ryan-oss at xyto.cc

**Comment by ballou-git** [comment]
Mail sent

**Comment by rmbolger** [comment]
Hey @ballou-git, I pushed a powerdns branch with a first attempt at the plugin. You should be able to grab the [plugin file](https://github.com/rmbolger/Posh-ACME/blob/powerdns/Posh-ACME/Plugins/PowerDNS.ps1) and drop it into the Plugins folder on your existing installation to test it out. The usage guide can also be viewed [here](https://github.com/rmbolger/Posh-ACME/blob/powerdns/docs/Plugins/PowerDNS.md).

**Comment by ballou-git** [comment]
@rmbolger I can't thank you enough.
I've setup a proxy to use only https, just as you wrote.
I'll give this a test in a few hours and give you a comment again.

**Comment by ballou-git** [comment]
Hi again.
It's working great during my tests.
Thank you again and I hope to see it in certifytheweb app as well.

**Comment by rmbolger** [comment]
New plugin is live in 4.20.0
