### ISSUE TITLE
DNSPod Argument Names

### ISSUE THREAD

**Issue by webprofusion-chrisc** [rmbolger/Posh-ACME#552]
While reviewing https://github.com/webprofusion/certify/issues/677 I'm wondering what the correct arguments are for DNSPod, I had them mapped as `DNSPodKeyID` and `DNSPodToken` but it looks like the script is expecting `DNSPodKeyId` and `DNSPodKeyToken` (not sure if case matters, but I can see how `DNSPodToken` would work). 

Weirdly some users seem to be managing to use it ok in Certify (?), and some don't but that could just be a side-effect of something else.

**Comment by rmbolger** [comment]
As far as I can tell, the correct arguments have always been `DNSPodKeyID` and either `DNSPodKeyToken` or `DNSPodKeyTokenInsecure`. Case shouldn't matter. However, the *plugin guide* is wrong in the example code.

PowerShell does allow you to shorten parameter names as long as the shortened version is still unique among the rest. But I don't see how `DNSPodToken` would have ever worked because it's not a shortened version of anything.

**Comment by rmbolger** [comment]
Doc fix is live.
