### ISSUE TITLE
How do you check for current installed version of Posh-ACME client and how do you upgrade the Posh-ACME client

### ISSUE THREAD

**Issue by jskang-netex** [rmbolger/Posh-ACME#558]
I apologize in advance for my lack of knowledge on how the Posh-ACME module works. I've looked through the v4 docs and FAQs and didn't see any reference to my specific questions. I also tried searching the issues already reported here as well. 

How do you go about seeing what version of the Posh-ACME module is currently installed? 

How do you check to see if the module was installed for all users or current user?

How do you keep the Posh-ACME module updated? Is there a built-in command that does this or do you just run "Install-Module -Name Posh-ACME -Scope <desired_install_scope>" whenever you want to update to the latest version?

Thanks in advance!

**Comment by rmbolger** [comment]
Hi @jskang-netex, thanks for reaching out. The info you're looking for is not in the docs because it's more general PowerShell knowledge than anything specific to the Posh-ACME module. But I'm glad to help out.

To check what version (or versions) of the module are installed and where, use this command. The directory shown should indicate which scope it was installed to (within a user profile or in a system-wide folder).

```powershell
Get-Module Posh-ACME -ListAvailable
```

To check what version of the module is currently loaded, use the same command but without the `-ListAvailable` parameter. If nothing is returned, it just means it hasn't been imported yet.

```powershell
Get-Module Posh-ACME
```

Updating the module depends on how you originally installed it. But if you used the recommended `Install-Module` approach, there's a corresponding `Update-Module` command that you can use like this. There are additional parameters you can use if you want a specific version.

```powershell
Update-Module Posh-ACME
```

The `Update-Module` command won't uninstall the old version and PowerShell will automatically import the new version in your next session. But if you want to get rid of the old version as well, you'll need the `Uninstall-Module` command for the specific version you want to get rid of. For example:

```powershell
Uninstall-Module Posh-ACME -RequiredVersion 4.15.0
```

**Comment by jskang-netex** [comment]
Yes, I am very much a very basic and infrequent user of PowerShell. lol. 

Yes, I installed it based on the documented directions here so everything you've spelled out should work for me. 

Thanks so much for the quick reply and help. It's greatly appreciated!

**Comment by rmbolger** [comment]
Feel free to come back with any additional questions.
