### ISSUE TITLE
cert+key+chain in pem format

### ISSUE THREAD

**Issue by istvanmate** [rmbolger/Posh-ACME#565]
WeeChat (and probably other software) supports only combined cert+key+chain and in PEM format only.
Is there a way to generate it along with the others?
Is there a way to invoke an extra PowerShell command to combine the content of fullchain.cer with cert.key and save it?

**Comment by rmbolger** [comment]
Hi @istvanmate. Yes, you can combine the `KeyFile` and `FullChainFile` that are part of the cert output object returned by New-PACertificate, Get-PACertificate, and Submit-Renewal.

I actually do this myself in a renewal script for an HAProxy instance. Concatenating the key and full chain files looks like this:

```powershell
# assumes you have a $cert object already as output from one of the functions above
$combined = (Get-Content $cert.KeyFile -Raw) + (Get-Content $cert.FullChainFile -Raw)
$combined | Out-File "/path/to/wherever/combined.pem" -Encoding ascii -Force
```

**Comment by istvanmate** [comment]
Thanks, the method was more or less done, my question is if it is possible to hook the script to the successful renewal process and not run it manually?

**Comment by rmbolger** [comment]
Generally, renewals are already part of a larger script that you'd just add this code to. There's are a couple examples in the tutorial here:
https://poshac.me/docs/v4/Tutorial/#task-scheduler-cron

But no, there's no native function result hooking like you'd find in some other clients because that's not really a common thing to do in PowerShell.

**Comment by istvanmate** [comment]
Thank you!
