### ISSUE TITLE
fullchain.pfx does not contain all certificates

### ISSUE THREAD

**Issue by mikkebjo** [rmbolger/Posh-ACME#581]
It seems like the fullchain.pfx only contains two certificates in stead of three. 
![image](https://github.com/user-attachments/assets/3c751c15-00bd-42b4-809b-e3134f4bfde3)

this is what it used to look like:
![image](https://github.com/user-attachments/assets/948d15f2-8482-4a0b-8f45-c085e2db1453)

Is this expected or a bug? :)

**Comment by rmbolger** [comment]
Hey @mikkebjo, thanks for reaching out. The two screenshots you posted are technically from different CAs (Let's Encrypt Prod vs Let's Encrypt Staging). That said, the chain of trust for Let's Encrypt certs has become shorter somewhat recently due to the expiration of the cross-signed root issued by `DST Root CA X3`. The latest you would have seen the change should have been around June 2024 when LE stopped issuing certs with that chain. However, the cross-sign didn't actually expire until the end of September.

More info on the whole thing is here:
https://letsencrypt.org/2023/07/10/cross-sign-expiration/
