### ISSUE TITLE
Some order parameters are not saved when Order status 'ready' immediately following creation

### ISSUE THREAD

**Issue by hutch120** [rmbolger/Posh-ACME#60]
Hi Guys,

Thanks for all your work on this module. 

Just wondering if I'm missing a step... after running `New-PACertificate ...` it generates a file called order.json which contains a bunch of JSON, but the DNSPlugin name is set to null. It works though, and saves the certificates.

But then calls to Submit-Renewal fail with the error: `New-PACertificate : Cannot validate argument on parameter 'DnsPlugin'`

To get it working I had to manually edit `Submit-Renewal.ps1` line 74 and set ` $certParams.DnsPlugin = "Route53"`

Note that updating order.json worked (one time) and then got changed back to null again!

I've traced though the code, but I can't see why it isn't saving the DnsPlugin value in order.json, any ideas?

Cheers,
Simon

**Comment by rmbolger** [comment]
That's a weird one. Just a few quick questions so I can try to reproduce the issue. What OS and PowerShell version are you running this on and what version of the module?

The fact that the order.json gets written but the DnsPlugin value is blank is really weird especially if the order completed successfully. Had you previously requested the same cert (or a cert with the same primary name) using a different plugin or no plugin?

**Comment by rmbolger** [comment]
Oy, there's definitely something funky going on. On my machine, it seems to be triggered specifically by `Submit-Renewal` and it appears to wipe out a bunch of the order parameters. It's most likely not limited to the Route53 plugin either. But I'm not positive yet.

Thanks for the heads up. I'm looking into this now.

**Comment by rmbolger** [comment]
I think I've narrowed it down to a bug that is ultimately caused by a [functionality change](https://community.letsencrypt.org/t/acmev2-order-ready-status/62866) on the Let's Encrypt servers that went live some time after Posh-ACME 2.4.0 was released.

It's a subtle logic bug that would affect any calls to `New-PACertificate` or `Submit-Renewal` where the name or names in the cert were previously validated successfully and those validations haven't expired yet. So in your case, I'm guessing you were probably testing `Submit-Renewal` with `-Force` to override the suggested renewal window. So the names in the cert were still valid from the recent call to `New-PACertificate` and triggered the bug.

Hoping to have a fix pushed out soon.

**Comment by rmbolger** [comment]
So this fix won't repair an already broken order (one where DnsPlugin is null). But it should prevent new orders from getting broken in the first place. The fix will definitely go out with version 2.5.0 that I'm hoping to push within the next day or so. I may try to push a 2.4.1 version tonight with just this fix as well.

If you don't want to wait, you can try the dev version using the `instdev.ps1` instructions in the readme.
