### ISSUE TITLE
Renewal without using the challenge/response method

### ISSUE THREAD

**Issue by perbergland** [rmbolger/Posh-ACME#73]
Reading the [letsencrypt documentation](https://letsencrypt.org/how-it-works/), it seems that once you have a valid authorized key pair for a domain you can use it also for renewal of ssl certificates without needing to re-validate the domain.

That would be nice to not have to use any DNSPlugin functionality for certificate renewals.

**Comment by rmbolger** [comment]
Unfortunately, that's not entirely true. The challenge validations for a given account key must be re-validated after a period of time. I believe the current amount is 30 days. So if you force a renewal sometime between day 1 and day 29, you'll see that the module skips the challenge validations because they come back as pre-validated when creating the new order. But doing a renewal like that doesn't extend the validation window. So by day 31, the validations have still expired and the next renewal will need to re-validate them.

**Comment by perbergland** [comment]
Thanks for the clarification. It did seem weird
