### ISSUE TITLE
Update "Manual" dns plugin (or add new) that is non-interactive

### ISSUE THREAD

**Issue by mithrandyr** [rmbolger/Posh-ACME#82]
This is similar to my previous enhancement (asking for wiki page on doing DNS validation by hand) -- but it would be really nice if the "Manual" dns plugin -- instead of prompting the user.. would just output the txtvalue needed and then somehow allow the user to notify "yup, its done, continue your process".  Perhaps the "manual" dns plugin to accept a scriptblock  and the user could put the code in there to create the DNS record?

Anyways, some thoughts and thanks for developing this incredibly useful PowerShell module! -- I've been excited about LE for 2 years now, but wasn't able to start using it until I came across this module!  Also, thanks for being very responsive on issues!

**Comment by rmbolger** [comment]
I'm honestly not sure if it will be possible to create a "semi-manual" plugin like you're describing. It does sound useful though. So let me stew on it for a bit and see what's doable.

**Comment by mithrandyr** [comment]
So, I was giving this more thought.  Instead of passing in a scriptblock, what if there was a plugin (manual/otherwise) that would simply output the TXT record value and then quit -- leaving the order in a known state.  The user would do whatever they need to and then rerun "New-PACertificate" with the same values, the internally logic would pick up the state and finish the process (so submitting the challenge, completing the order, etc).

```powershell
#This will setup the order and determine the proper challenge value to be stored in TXT record, outputting as a hashtable both the name and value for of the TXT record.
[hashtable]$txtRecord = New-PACertificate site1.example.com -DNSPlugin "DoItYourSelf"

#some fictitious function that will create a DNS record against whatever DNS provider is being used....
Create-DnsRecord -Name $txtRecord.Name -Type TXT -Value $txtRecord.Data

Start-Sleep -Seconds 120

# This will recognize that the order is in a pending state and (I'm guessing b/c of the DnsPlugin associated to the order?) will know that it needs to do the challenge and complete the order... resulting in a completed certificate.
New-PACertificate site1.example.com
```

**Comment by rmbolger** [comment]
Without complicating the plugin architecture and potentially needing to tweak all the existing plugins to accommodate the change, I feel like the only way to make this work is actually a switch on `New-PACertificate` that basically says "quit after creating the order". But then what's the difference between that and just calling `New-PAOrder` directly?

And if you're already writing your own environment specific `Create-DnsRecord` function, why not just make it a plugin? Have you checked out the [plugin development guide](https://github.com/rmbolger/Posh-ACME/blob/master/Posh-ACME/DnsPlugins/README.md) yet? It can be totally custom to your environment with hard coded values for everything and not intended to ever be submitted as a pull-request back to the main project. You basically just have to follow the naming convention for the file and functions and drop the file in the DnsPlugins folder on your machine.

The only hassle might be upgrading the module. Not sure if PowerShellGet's `Update-Module` would delete the custom plugin or not. But if so, I could probably modify things so that you could specify a full path to a plugin ps1 file that lives outside the module folder.
